# Generated by Django 4.2.7 on 2025-12-07 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# backend.apps.project_center.migrations.0005_servicetype_paymentplan_condition_detail_and_more
# backend.apps.project_center.migrations.0010_projectteam_unit_projectteamchangelog_unit_and_more

SERVICE_TYPE_DEFINITIONS = [
    ('result_optimization', '结果优化', ['结构', '构造', '地库减面积', '地库加车位', '停车效率', '节能', '门窗栏杆', '幕墙', '总坪景观', '电气', '给排水', '暖通', '市政道路']),
    ('process_optimization', '过程优化', ['结构', '停车效率']),
    ('detailed_review', '精细化审图', ['结构', '建筑', '电气', '给排水', '暖通']),
    ('full_process_consulting', '全过程咨询', ['结构', '建筑', '电气', '给排水', '暖通']),
]

PROFESSION_CODE_MAP = {
    '结构': 'structure', '构造': 'construction', '地库减面积': 'basement_reduce_area',
    '地库加车位': 'basement_add_parking', '停车效率': 'parking_efficiency',
    '建筑地库': 'basement_parking_layout', '节能': 'energy_saving',
    '门窗栏杆': 'doors_windows_railings', '幕墙': 'curtain_wall',
    '总坪景观': 'landscape', '电气': 'electrical',
    '给排水': 'water_supply_drainage', '暖通': 'hvac',
    '市政道路': 'municipal_road', '建筑': 'architecture',
}

LEGACY_PROFESSION_ALIAS = {'建筑地库': '停车效率'}


def seed_service_data(apps, schema_editor):
    """从0005迁移复制：初始化服务类型数据"""
    ServiceType = apps.get_model('project_center', 'ServiceType')
    ServiceProfession = apps.get_model('project_center', 'ServiceProfession')
    Project = apps.get_model('project_center', 'Project')
    service_type_cache = {}
    for order, (code, name, professions) in enumerate(SERVICE_TYPE_DEFINITIONS, start=1):
        service_type, _ = ServiceType.objects.update_or_create(code=code, defaults={'name': name, 'order': order})
        service_type_cache[code] = service_type
        for prof_order, profession_name in enumerate(professions, start=1):
            profession_code = PROFESSION_CODE_MAP.get(profession_name, profession_name)
            ServiceProfession.objects.update_or_create(
                service_type=service_type, code=profession_code,
                defaults={'name': profession_name, 'order': prof_order}
            )
    for project in Project.objects.all():
        service_type_code = getattr(project, 'service_type_code', None)
        legacy_professions = getattr(project, 'service_professions_legacy', []) or []
        service_type = service_type_cache.get(service_type_code)
        if service_type:
            project.service_type = service_type
            project.save(update_fields=['service_type'])
        if legacy_professions:
            normalized_names = [LEGACY_PROFESSION_ALIAS.get(name, name) for name in legacy_professions]
            if service_type and normalized_names:
                professions_qs = ServiceProfession.objects.filter(service_type=service_type, name__in=normalized_names)
                project.service_professions.set(professions_qs)
            else:
                project.service_professions.clear()


def assign_units(apps, schema_editor):
    """从0010迁移复制：为项目团队成员分配单位"""
    ProjectTeam = apps.get_model('project_center', 'ProjectTeam')
    ProjectTeamChangeLog = apps.get_model('project_center', 'ProjectTeamChangeLog')
    role_unit_map = {
        'business_manager': 'business', 'project_manager': 'management',
        'professional_leader': 'internal_tech', 'engineer': 'internal_tech',
        'technical_assistant': 'internal_tech', 'external_leader': 'external_tech',
        'external_engineer': 'external_tech', 'cost_reviewer_civil': 'internal_cost',
        'cost_reviewer_installation': 'internal_cost', 'cost_engineer_civil': 'internal_cost',
        'cost_engineer_installation': 'internal_cost', 'external_cost_reviewer_civil': 'external_cost',
        'external_cost_reviewer_installation': 'external_cost', 'external_cost_engineer_civil': 'external_cost',
        'external_cost_engineer_installation': 'external_cost',
    }
    external_units = {'external_tech', 'external_cost'}
    for team in ProjectTeam.objects.all():
        unit = role_unit_map.get(team.role, 'management')
        if team.unit != unit or team.is_external != (unit in external_units):
            team.unit = unit
            team.is_external = unit in external_units
            team.save(update_fields=['unit', 'is_external'])
    for log in ProjectTeamChangeLog.objects.all():
        unit = role_unit_map.get(log.role, 'management')
        if log.unit != unit:
            log.unit = unit
            log.save(update_fields=['unit'])


class Migration(migrations.Migration):

    replaces = [('project_center', '0001_initial'), ('project_center', '0002_add_project_fields'), ('project_center', '0003_update_project_fields'), ('project_center', '0004_allow_null_service_fields'), ('project_center', '0005_servicetype_paymentplan_condition_detail_and_more'), ('project_center', '0006_alter_projectteam_unique_together_and_more'), ('project_center', '0007_projectteamchangelog'), ('project_center', '0008_projectteamnotification'), ('project_center', '0009_projectteamnotification_operator_context'), ('project_center', '0010_projectteam_unit_projectteamchangelog_unit_and_more'), ('project_center', '0011_projectdrawingreview_projectdrawingsubmission_and_more'), ('project_center', '0012_project_flow_deadline_project_flow_payload_and_more'), ('project_center', '0013_remove_project_contract_amount_and_more'), ('project_center', '0014_project_client_leader_project_design_leader'), ('project_center', '0015_alter_projectteam_role_alter_projectteam_unit_and_more'), ('project_center', '0016_projectmeetingrecord_projectdesignreply')]

    dependencies = [
        ('system_management', '0001_initial'),
        ('customer_management', '0001_initial_squashed_0015_remove_client_blacklist_details_remove_client_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('service_type_code', models.CharField(blank=True, choices=[('result_optimization', '结果优化'), ('process_optimization', '过程优化'), ('detailed_review', '精细化审图'), ('full_process_consulting', '全过程咨询')], max_length=50, null=True, verbose_name='服务类型')),
                ('business_type', models.CharField(blank=True, choices=[('residential', '住宅'), ('complex', '综合体'), ('commercial', '商业'), ('office', '写字楼'), ('school', '学校'), ('hospital', '医院'), ('industrial', '工业厂房'), ('municipal', '市政'), ('other', '其他')], max_length=50, null=True, verbose_name='项目业态')),
                ('design_stage', models.CharField(blank=True, choices=[('construction_drawing_unreviewed', '施工图（未审图）'), ('construction_drawing_reviewed', '施工图（已审图）'), ('preliminary_design', '初设阶段'), ('extended_preliminary', '扩初阶段'), ('detailed_planning', '详规阶段'), ('construction_phase', '施工阶段')], max_length=50, null=True, verbose_name='图纸阶段')),
                ('design_company', models.CharField(blank=True, max_length=200, verbose_name='设计单位名称')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('waiting_receive', '待接收'), ('configuring', '配置中'), ('waiting_start', '待开工'), ('in_progress', '进行中'), ('suspended', '暂停'), ('completed', '已完工'), ('archived', '已归档'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='项目状态')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预估成本')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
                ('aboveground_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='地上面积(㎡)')),
                ('aboveground_floors', models.IntegerField(blank=True, null=True, verbose_name='地上层数')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='项目别名')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='建筑面积(㎡)')),
                ('building_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建筑高度(米)')),
                ('business_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='商务经理')),
                ('client_address', models.CharField(blank=True, max_length=500, verbose_name='通讯地址')),
                ('client_company_name', models.CharField(blank=True, max_length=200, verbose_name='甲方公司名称')),
                ('client_contact_person', models.CharField(blank=True, max_length=100, verbose_name='甲方项目负责人')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱')),
                ('client_special_requirements', models.TextField(blank=True, verbose_name='甲方特殊要求')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='签约日期')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='project_contracts/%Y/%m/', verbose_name='合同附件')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('design_contact_person', models.CharField(blank=True, max_length=100, verbose_name='设计方项目负责人')),
                ('design_email', models.EmailField(blank=True, max_length=254, verbose_name='设计方电子邮箱')),
                ('design_phone', models.CharField(blank=True, max_length=20, verbose_name='设计方联系电话')),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计节省金额')),
                ('project_address', models.CharField(blank=True, max_length=500, verbose_name='项目地址')),
                ('risk_assessment', models.TextField(blank=True, verbose_name='项目风险预判')),
                ('service_professions_legacy', models.JSONField(blank=True, default=list, verbose_name='服务专业')),
                ('structure_type', models.CharField(blank=True, max_length=100, verbose_name='结构形式')),
                ('subsidiary', models.CharField(choices=[('sichuan', '四川维海科技有限公司'), ('chongqing', '重庆维海科技有限公司'), ('xian', '西安维海科技有限公司'), ('hejian_chengdu', '禾间成都建筑设计咨询有限公司'), ('hongtian', '成都宏天升荣科技有限公司')], default='sichuan', max_length=50, verbose_name='子公司')),
                ('technical_difficulties', models.TextField(blank=True, verbose_name='技术难点说明')),
                ('underground_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='地下面积(㎡)')),
                ('underground_floors', models.IntegerField(blank=True, null=True, verbose_name='地下层数')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project_center_project',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, verbose_name='里程碑描述')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('completion_rate', models.IntegerField(default=0, verbose_name='完成率')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目里程碑',
                'verbose_name_plural': '项目里程碑',
                'db_table': 'project_center_milestone',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('document_type', models.CharField(choices=[('contract', '合同文件'), ('design', '设计文件'), ('report', '报告文件'), ('meeting', '会议纪要'), ('other', '其他文件')], max_length=50, verbose_name='文档类型')),
                ('file', models.FileField(upload_to='project_documents/%Y/%m/', verbose_name='文档文件')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project_center.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
                'db_table': 'project_center_document',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(max_length=50, unique=True, verbose_name='归档编号')),
                ('archive_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='归档时间')),
                ('archive_version', models.IntegerField(default=1, verbose_name='归档版本')),
                ('archive_content', models.JSONField(default=dict, verbose_name='归档内容')),
                ('view_permissions', models.JSONField(blank=True, default=list, verbose_name='查看权限')),
                ('download_permissions', models.JSONField(blank=True, default=list, verbose_name='下载权限')),
                ('modify_permissions', models.JSONField(blank=True, default=list, verbose_name='修改权限')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='归档人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目归档',
                'verbose_name_plural': '项目归档',
                'db_table': 'project_center_archive',
                'ordering': ['-archive_time'],
                'unique_together': {('project', 'archive_version')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('business_manager', '商务经理'), ('project_manager', '项目负责人'), ('professional_leader', '专业负责人'), ('engineer', '专业工程师'), ('technical_assistant', '技术助理'), ('cost_reviewer_civil', '土建造价审核人'), ('cost_reviewer_installation', '安装造价审核人'), ('cost_engineer_civil', '土建造价师'), ('cost_engineer_installation', '安装造价师'), ('external_engineer', '外部专业工程师'), ('external_leader', '外部专业负责人'), ('external_cost_reviewer_civil', '外部土建造价审核人'), ('external_cost_reviewer_installation', '外部安装造价审核人'), ('external_cost_engineer_civil', '外部土建造价师'), ('external_cost_engineer_installation', '外部安装造价师')], max_length=50, verbose_name='角色')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外部成员')),
                ('join_date', models.DateField(verbose_name='加入日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离开日期')),
                ('responsibility', models.TextField(blank=True, verbose_name='职责描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='project_center.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '项目团队',
                'verbose_name_plural': '项目团队',
                'db_table': 'project_center_team',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='服务类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='服务类型名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
                'db_table': 'project_center_service_type',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='服务专业编码')),
                ('name', models.CharField(max_length=100, verbose_name='服务专业名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='project_center.servicetype', verbose_name='所属服务类型')),
            ],
            options={
                'verbose_name': '服务专业',
                'verbose_name_plural': '服务专业',
                'db_table': 'project_center_service_profession',
                'ordering': ['service_type__order', 'order', 'id'],
                'unique_together': {('service_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100, verbose_name='回款阶段')),
                ('phase_description', models.TextField(blank=True, verbose_name='阶段描述')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划金额')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际金额')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('pending', '待回款'), ('partial', '部分回款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='project_center.project', verbose_name='项目')),
                ('condition_detail', models.CharField(default='', max_length=200, verbose_name='付款条件详情')),
                ('trigger_condition', models.CharField(choices=[('contract_signed', '合同签订'), ('consultation_report', '咨询意见书'), ('tripartite_result', '三方沟通成果'), ('review_report', '核图意见书'), ('preliminary_settlement', '结算初审'), ('final_settlement', '结算定案'), ('main_structure_completed', '主体封顶'), ('presale_license', '预售证'), ('completion_acceptance', '竣工验收'), ('completion_filing', '竣工备案')], default='contract_signed', max_length=50, verbose_name='触发条件')),
            ],
            options={
                'verbose_name': '回款计划',
                'verbose_name_plural': '回款计划',
                'db_table': 'project_center_payment_plan',
                'ordering': ['planned_date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_center.servicetype', verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_professions',
            field=models.ManyToManyField(blank=True, related_name='projects', to='project_center.serviceprofession', verbose_name='服务专业'),
        ),
        migrations.RunPython(
            code=seed_service_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_type_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_professions_legacy',
        ),
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='service_profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_center.serviceprofession', verbose_name='所属专业'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='加入日期'),
        ),
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together={('project', 'user', 'role', 'service_profession')},
        ),
        migrations.CreateModel(
            name='ProjectTeamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('team_change', '团队变更')], default='team_change', max_length=50, verbose_name='通知分类')),
                ('action_url', models.CharField(blank=True, max_length=300, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notifications', to='project_center.project', verbose_name='项目')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文信息')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '项目团队通知',
                'verbose_name_plural': '项目团队通知',
                'db_table': 'project_center_team_notification',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='projectteam',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.CreateModel(
            name='ProjectTeamChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='角色')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外部成员')),
                ('action', models.CharField(choices=[('added', '新增'), ('removed', '移除')], max_length=20, verbose_name='操作类型')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_change_logs', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_change_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_change_logs', to='project_center.project', verbose_name='项目')),
                ('service_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_center.serviceprofession', verbose_name='所属专业')),
                ('unit', models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队')], default='management', max_length=32, verbose_name='所属团队')),
            ],
            options={
                'verbose_name': '项目团队变更日志',
                'verbose_name_plural': '项目团队变更日志',
                'db_table': 'project_center_team_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('business_manager', '商务经理'), ('project_manager', '项目经理'), ('professional_leader', '内部专业负责人'), ('engineer', '内部专业工程师'), ('technical_assistant', '技术助理'), ('external_leader', '外部专业负责人'), ('external_engineer', '外部专业工程师'), ('cost_reviewer_civil', '内部土建审核人'), ('cost_reviewer_installation', '内部安装审核人'), ('cost_engineer_civil', '内部土建造价师'), ('cost_engineer_installation', '内部安装造价师'), ('external_cost_reviewer_civil', '外部土建审核人'), ('external_cost_reviewer_installation', '外部安装审核人'), ('external_cost_engineer_civil', '外部土建造价师'), ('external_cost_engineer_installation', '外部安装造价师')], max_length=50, verbose_name='角色'),
        ),
        migrations.RunPython(
            code=assign_units,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ProjectDrawingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', '待处理'), ('approved', '通过'), ('changes_requested', '需修改')], default='pending', max_length=30, verbose_name='预审结果')),
                ('comment', models.TextField(blank=True, verbose_name='预审意见')),
                ('reviewed_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预审时间')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_reviews', to=settings.AUTH_USER_MODEL, verbose_name='预审人')),
            ],
            options={
                'verbose_name': '项目图纸预审记录',
                'verbose_name_plural': '项目图纸预审记录',
                'db_table': 'project_center_drawing_review',
                'ordering': ['-reviewed_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDrawingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='提交标题')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='提交说明')),
                ('submitter_role', models.CharField(blank=True, max_length=100, verbose_name='提交人角色')),
                ('submitted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('submitted', '待预审'), ('in_review', '预审中'), ('changes_requested', '需补充资料'), ('approved', '预审通过'), ('cancelled', '已取消')], default='submitted', max_length=30, verbose_name='预审状态')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='预审截止时间')),
                ('client_notified', models.BooleanField(default=False, verbose_name='是否已通知甲方')),
                ('client_notified_time', models.DateTimeField(blank=True, null=True, verbose_name='甲方通知时间')),
                ('client_notification_channel', models.CharField(blank=True, max_length=30, verbose_name='甲方通知渠道')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('latest_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project_center.projectdrawingreview', verbose_name='最新预审记录')),
            ],
            options={
                'verbose_name': '项目图纸提交',
                'verbose_name_plural': '项目图纸提交',
                'db_table': 'project_center_drawing_submission',
                'ordering': ['-submitted_time'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='drawing_precheck_completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='图纸预审完成时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='handover_submitted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='商务移交时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_status',
            field=models.CharField(choices=[('handover_pending', '待商务移交'), ('awaiting_drawings', '待图纸上传'), ('precheck_in_progress', '预审中'), ('changes_requested', '待补充资料'), ('ready_to_start', '待开工通知'), ('started', '已开工')], default='handover_pending', max_length=30, verbose_name='项目启动状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_status_updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='启动状态更新时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_notice_sent_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开工通知时间'),
        ),
        migrations.CreateModel(
            name='ProjectStartNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='通知主题')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('channel', models.CharField(choices=[('system', '系统通知'), ('email', '邮件'), ('sms', '短信'), ('manual', '线下确认')], default='system', max_length=30, verbose_name='通知渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('acknowledged', '已确认')], default='pending', max_length=30, verbose_name='通知状态')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='接收人姓名')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='接收人电话')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='接收人邮箱')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('acknowledged_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_notices_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_notices', to='project_center.project', verbose_name='项目')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_start_notices', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_notices', to='project_center.projectdrawingsubmission', verbose_name='关联图纸提交')),
            ],
            options={
                'verbose_name': '项目开工通知',
                'verbose_name_plural': '项目开工通知',
                'db_table': 'project_center_start_notice',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='projectdrawingsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_submissions', to='project_center.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectdrawingsubmission',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='projectdrawingreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project_center.projectdrawingsubmission', verbose_name='图纸提交'),
        ),
        migrations.CreateModel(
            name='ProjectDrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('category', models.CharField(choices=[('general', '通用资料'), ('architecture', '建筑'), ('structure', '结构'), ('mep', '机电'), ('civil', '土建'), ('other', '其他')], default='general', max_length=30, verbose_name='文件分类')),
                ('file', models.FileField(upload_to='project_drawings/%Y/%m/', verbose_name='文件')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_center.projectdrawingsubmission', verbose_name='图纸提交')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目图纸文件',
                'verbose_name_plural': '项目图纸文件',
                'db_table': 'project_center_drawing_file',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='flow_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='当前步骤截止时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='flow_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='流程上下文'),
        ),
        migrations.AddField(
            model_name='project',
            name='flow_step',
            field=models.CharField(choices=[('pending_documents', '等待资料上传'), ('precheck', '资料预审'), ('start_notice', '开工通知'), ('opinions', '意见编制'), ('internal_review', '内部审核'), ('ready_to_push', '待推送'), ('pushed', '报告已推送')], default='pending_documents', max_length=40, verbose_name='当前流程步骤'),
        ),
        migrations.AddField(
            model_name='project',
            name='flow_step_started_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='步骤开始时间'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='trigger_condition',
            field=models.CharField(choices=[('business_commission_letter', '业务委托书'), ('contract_signed', '合同签订'), ('consultation_report', '咨询意见书'), ('tripartite_result', '三方沟通成果'), ('review_report', '核图意见书'), ('optimized_drawings', '优化后图纸'), ('settlement_declaration', '结算申报'), ('preliminary_settlement', '结算初步审核报告'), ('final_settlement', '结算定案报告'), ('construction_drawing_review', '施工图审图报告'), ('construction_drawing_release', '施工图正式出图'), ('construction_permit', '施工许可证'), ('predicted_area_report', '预测面积报告'), ('presale_license', '预售证'), ('foundation_completion', '基础施工完成'), ('basement_completion', '地下室施工完成'), ('main_structure_completed', '主体封顶'), ('completion_acceptance', '验工验收合格'), ('completion_filing', '验工验收备案')], default='contract_signed', max_length=50, verbose_name='触发条件'),
        ),
        migrations.AlterField(
            model_name='projectteamnotification',
            name='category',
            field=models.CharField(choices=[('team_change', '团队变更'), ('quality_alert', '质量提醒')], default='team_change', max_length=50, verbose_name='通知分类'),
        ),
        migrations.CreateModel(
            name='ProjectFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('advance', '流程流转'), ('note', '备注')], default='advance', max_length=30, verbose_name='动作类型')),
                ('from_step', models.CharField(blank=True, max_length=40, verbose_name='原步骤')),
                ('to_step', models.CharField(blank=True, max_length=40, verbose_name='目标步骤')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_flow_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目流程日志',
                'verbose_name_plural': '项目流程日志',
                'db_table': 'project_center_flow_log',
                'ordering': ['-created_time'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_number',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.AddField(
            model_name='project',
            name='client_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to=settings.AUTH_USER_MODEL, verbose_name='甲方负责人账号'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_projects', to=settings.AUTH_USER_MODEL, verbose_name='设计方负责人账号'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('business_manager', '商务经理'), ('project_manager', '项目经理'), ('professional_leader', '内部专业负责人'), ('engineer', '内部专业工程师'), ('technical_assistant', '技术助理'), ('external_leader', '外部专业负责人'), ('external_engineer', '外部专业工程师'), ('cost_reviewer_civil', '内部土建审核人'), ('cost_reviewer_installation', '内部安装审核人'), ('cost_engineer_civil', '内部土建造价师'), ('cost_engineer_installation', '内部安装造价师'), ('external_cost_reviewer_civil', '外部土建审核人'), ('external_cost_reviewer_installation', '外部安装审核人'), ('external_cost_engineer_civil', '外部土建造价师'), ('external_cost_engineer_installation', '外部安装造价师'), ('client_lead', '甲方项目负责人'), ('client_engineer', '甲方专业工程师'), ('design_lead', '设计方项目负责人'), ('design_engineer', '设计方专业工程师')], max_length=50, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队'), ('client_side', '甲方团队'), ('design_side', '设计团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.AlterField(
            model_name='projectteamchangelog',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队'), ('client_side', '甲方团队'), ('design_side', '设计团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('task_type', models.CharField(choices=[('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知')], max_length=64, verbose_name='任务类型')),
                ('description', models.TextField(blank=True, verbose_name='任务说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('assigned_role', models.CharField(blank=True, max_length=50, verbose_name='指派角色')),
                ('target_unit', models.CharField(blank=True, max_length=32, verbose_name='目标团队')),
                ('due_time', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='取消操作人')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_completed', to=settings.AUTH_USER_MODEL, verbose_name='完成操作人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目任务',
                'verbose_name_plural': '项目任务',
                'db_table': 'project_center_task',
                'ordering': ['due_time', 'created_time'],
                'indexes': [models.Index(fields=['project', 'task_type'], name='project_cen_project_dca81f_idx'), models.Index(fields=['project', 'status'], name='project_cen_project_a1ad67_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(default=django.utils.timezone.now, verbose_name='会议日期')),
                ('topic', models.CharField(max_length=200, verbose_name='会议主题')),
                ('client_decision', models.TextField(blank=True, verbose_name='甲方意见')),
                ('design_decision', models.TextField(blank=True, verbose_name='设计方意见')),
                ('consultant_decision', models.TextField(blank=True, verbose_name='我方意见')),
                ('conclusions', models.TextField(blank=True, verbose_name='结论 / 待办')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_records', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '三方会议记录',
                'verbose_name_plural': '三方会议记录',
                'db_table': 'project_center_meeting_record',
                'ordering': ['-meeting_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDesignReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200, verbose_name='事项 / 问题')),
                ('status', models.CharField(choices=[('agree', '同意优化'), ('reject', '不同意优化'), ('partial', '部分同意')], default='agree', max_length=20, verbose_name='回复结果')),
                ('response_detail', models.TextField(blank=True, verbose_name='回复说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_replies', to='project_center.project', verbose_name='项目')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_replies', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '设计方回复',
                'verbose_name_plural': '设计方回复',
                'db_table': 'project_center_design_reply',
                'ordering': ['-created_time'],
            },
        ),
    ]
