# Generated by Django 4.2.7 on 2025-11-06 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('service_type', models.CharField(choices=[('design_optimization', '设计优化'), ('detailed_review', '精细化审图'), ('full_process_consulting', '全过程设计咨询')], max_length=50, verbose_name='服务类型')),
                ('business_type', models.CharField(max_length=100, verbose_name='业态类型')),
                ('design_stage', models.CharField(max_length=100, verbose_name='图纸阶段')),
                ('design_company', models.CharField(max_length=200, verbose_name='设计单位')),
                ('client_contact', models.CharField(blank=True, max_length=100, verbose_name='客户联系人')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='客户电话')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('waiting_approval', '待审批'), ('approved', '已审批'), ('in_progress', '进行中'), ('suspended', '暂停'), ('completed', '已完成'), ('archived', '已归档'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='项目状态')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预估成本')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project_center_project',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, verbose_name='里程碑描述')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('completion_rate', models.IntegerField(default=0, verbose_name='完成率')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目里程碑',
                'verbose_name_plural': '项目里程碑',
                'db_table': 'project_center_milestone',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('document_type', models.CharField(choices=[('contract', '合同文件'), ('design', '设计文件'), ('report', '报告文件'), ('meeting', '会议纪要'), ('other', '其他文件')], max_length=50, verbose_name='文档类型')),
                ('file', models.FileField(upload_to='project_documents/%Y/%m/', verbose_name='文档文件')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project_center.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
                'db_table': 'project_center_document',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100, verbose_name='回款阶段')),
                ('phase_description', models.TextField(blank=True, verbose_name='阶段描述')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划金额')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际金额')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('pending', '待回款'), ('partial', '部分回款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '回款计划',
                'verbose_name_plural': '回款计划',
                'db_table': 'project_center_payment_plan',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('project_manager', '项目经理'), ('technical_director', '技术总监'), ('professional_leader', '专业负责人'), ('engineer', '工程师'), ('reviewer', '审核人'), ('external_expert', '外部专家')], max_length=50, verbose_name='角色')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外部成员')),
                ('join_date', models.DateField(verbose_name='加入日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离开日期')),
                ('responsibility', models.TextField(blank=True, verbose_name='职责描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='project_center.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '项目团队',
                'verbose_name_plural': '项目团队',
                'db_table': 'project_center_team',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
