# Generated by Django 4.2.7 on 2025-11-07 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0001_initial'),
        ('project_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_contact',
        ),
        migrations.AddField(
            model_name='project',
            name='aboveground_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='地上面积(㎡)'),
        ),
        migrations.AddField(
            model_name='project',
            name='aboveground_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='地上层数'),
        ),
        migrations.AddField(
            model_name='project',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目别名'),
        ),
        migrations.AddField(
            model_name='project',
            name='building_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='建筑面积(㎡)'),
        ),
        migrations.AddField(
            model_name='project',
            name='building_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建筑高度(米)'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='商务经理'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='通讯地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='甲方公司名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='甲方项目负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_special_requirements',
            field=models.TextField(blank=True, verbose_name='甲方特殊要求'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='签约日期'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='project_contracts/%Y/%m/', verbose_name='合同附件'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='合同编号'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='设计方项目负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='设计方电子邮箱'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='设计方联系电话'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计节省金额'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='项目地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_assessment',
            field=models.TextField(blank=True, verbose_name='项目风险预判'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_professions',
            field=models.JSONField(blank=True, default=list, verbose_name='服务专业'),
        ),
        migrations.AddField(
            model_name='project',
            name='structure_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='结构形式'),
        ),
        migrations.AddField(
            model_name='project',
            name='subsidiary',
            field=models.CharField(choices=[('sichuan', '四川维海'), ('chongqing', '重庆维海'), ('xian', '西安维海'), ('hejian_chengdu', '禾间成都'), ('hongtian', '宏天升荣')], default='sichuan', max_length=50, verbose_name='子公司'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_difficulties',
            field=models.TextField(blank=True, verbose_name='技术难点说明'),
        ),
        migrations.AddField(
            model_name='project',
            name='underground_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='地下面积(㎡)'),
        ),
        migrations.AddField(
            model_name='project',
            name='underground_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='地下层数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_type',
            field=models.CharField(choices=[('residential', '住宅'), ('commercial', '商业'), ('complex', '综合体'), ('office', '办公'), ('industrial', '工业'), ('other', '其他')], max_length=50, verbose_name='项目业态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_management.client', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='设计单位名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_stage',
            field=models.CharField(choices=[('construction_drawing', '施工图'), ('preliminary_design', '初设阶段'), ('conceptual_design', '方案设计'), ('other', '其他')], max_length=50, verbose_name='图纸阶段'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(choices=[('result_optimization', '结果优化'), ('process_optimization', '过程优化'), ('detailed_review', '精细化审图'), ('full_process_consulting', '全过程咨询')], max_length=50, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('waiting_receive', '待接收'), ('configuring', '配置中'), ('waiting_start', '待开工'), ('in_progress', '进行中'), ('suspended', '暂停'), ('completed', '已完工'), ('archived', '已归档'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='项目状态'),
        ),
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(max_length=50, unique=True, verbose_name='归档编号')),
                ('archive_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='归档时间')),
                ('archive_version', models.IntegerField(default=1, verbose_name='归档版本')),
                ('archive_content', models.JSONField(default=dict, verbose_name='归档内容')),
                ('view_permissions', models.JSONField(blank=True, default=list, verbose_name='查看权限')),
                ('download_permissions', models.JSONField(blank=True, default=list, verbose_name='下载权限')),
                ('modify_permissions', models.JSONField(blank=True, default=list, verbose_name='修改权限')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='归档人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目归档',
                'verbose_name_plural': '项目归档',
                'db_table': 'project_center_archive',
                'ordering': ['-archive_time'],
                'unique_together': {('project', 'archive_version')},
            },
        ),
    ]
