# Generated by Django 4.2.7 on 2025-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0002_add_project_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_type',
            field=models.CharField(choices=[('residential', '住宅'), ('complex', '综合体'), ('commercial', '商业'), ('office', '写字楼'), ('school', '学校'), ('hospital', '医院'), ('industrial', '工业厂房'), ('municipal', '市政'), ('other', '其他')], max_length=50, verbose_name='项目业态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_stage',
            field=models.CharField(choices=[('construction_drawing_unreviewed', '施工图（未审图）'), ('construction_drawing_reviewed', '施工图（已审图）'), ('preliminary_design', '初设阶段'), ('extended_preliminary', '扩初阶段'), ('detailed_planning', '详规阶段'), ('construction_phase', '施工阶段')], max_length=50, verbose_name='图纸阶段'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subsidiary',
            field=models.CharField(choices=[('sichuan', '四川维海科技有限公司'), ('chongqing', '重庆维海科技有限公司'), ('xian', '西安维海科技有限公司'), ('hejian_chengdu', '禾间成都建筑设计咨询有限公司'), ('hongtian', '成都宏天升荣科技有限公司')], default='sichuan', max_length=50, verbose_name='子公司'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('business_manager', '商务经理'), ('project_manager', '项目负责人'), ('professional_leader', '专业负责人'), ('engineer', '专业工程师'), ('technical_assistant', '技术助理'), ('cost_reviewer_civil', '土建造价审核人'), ('cost_reviewer_installation', '安装造价审核人'), ('cost_engineer_civil', '土建造价师'), ('cost_engineer_installation', '安装造价师'), ('external_engineer', '外部专业工程师'), ('external_leader', '外部专业负责人'), ('external_cost_reviewer_civil', '外部土建造价审核人'), ('external_cost_reviewer_installation', '外部安装造价审核人'), ('external_cost_engineer_civil', '外部土建造价师'), ('external_cost_engineer_installation', '外部安装造价师')], max_length=50, verbose_name='角色'),
        ),
    ]
