# Generated by Django 4.2.7 on 2025-11-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0003_update_project_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_type',
            field=models.CharField(blank=True, choices=[('residential', '住宅'), ('complex', '综合体'), ('commercial', '商业'), ('office', '写字楼'), ('school', '学校'), ('hospital', '医院'), ('industrial', '工业厂房'), ('municipal', '市政'), ('other', '其他')], max_length=50, null=True, verbose_name='项目业态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_stage',
            field=models.CharField(blank=True, choices=[('construction_drawing_unreviewed', '施工图（未审图）'), ('construction_drawing_reviewed', '施工图（已审图）'), ('preliminary_design', '初设阶段'), ('extended_preliminary', '扩初阶段'), ('detailed_planning', '详规阶段'), ('construction_phase', '施工阶段')], max_length=50, null=True, verbose_name='图纸阶段'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(blank=True, choices=[('result_optimization', '结果优化'), ('process_optimization', '过程优化'), ('detailed_review', '精细化审图'), ('full_process_consulting', '全过程咨询')], max_length=50, null=True, verbose_name='服务类型'),
        ),
    ]
