# Generated by Django 4.2.7 on 2025-11-08 12:17

from django.db import migrations, models
import django.db.models.deletion


SERVICE_TYPE_DEFINITIONS = [
    (
        'result_optimization',
        '结果优化',
        [
            '结构', '构造', '地库减面积', '地库加车位', '停车效率', '节能',
            '门窗栏杆', '幕墙', '总坪景观', '电气', '给排水', '暖通', '市政道路'
        ],
    ),
    (
        'process_optimization',
        '过程优化',
        [
            '结构', '停车效率',
        ],
    ),
    (
        'detailed_review',
        '精细化审图',
        [
            '结构', '建筑', '电气', '给排水', '暖通',
        ],
    ),
    (
        'full_process_consulting',
        '全过程咨询',
        [
            '结构', '建筑', '电气', '给排水', '暖通',
        ],
    ),
]

PROFESSION_CODE_MAP = {
    '结构': 'structure',
    '构造': 'construction',
    '地库减面积': 'basement_reduce_area',
    '地库加车位': 'basement_add_parking',
    '停车效率': 'parking_efficiency',
    '建筑地库': 'basement_parking_layout',
    '节能': 'energy_saving',
    '门窗栏杆': 'doors_windows_railings',
    '幕墙': 'curtain_wall',
    '总坪景观': 'landscape',
    '电气': 'electrical',
    '给排水': 'water_supply_drainage',
    '暖通': 'hvac',
    '市政道路': 'municipal_road',
    '建筑': 'architecture',
}

LEGACY_PROFESSION_ALIAS = {
    '建筑地库': '停车效率',
}


def seed_service_data(apps, schema_editor):
    ServiceType = apps.get_model('project_center', 'ServiceType')
    ServiceProfession = apps.get_model('project_center', 'ServiceProfession')
    Project = apps.get_model('project_center', 'Project')

    service_type_cache = {}

    for order, (code, name, professions) in enumerate(SERVICE_TYPE_DEFINITIONS, start=1):
        service_type, _ = ServiceType.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'order': order,
            },
        )
        service_type_cache[code] = service_type

        for prof_order, profession_name in enumerate(professions, start=1):
            profession_code = PROFESSION_CODE_MAP.get(profession_name, profession_name)
            ServiceProfession.objects.update_or_create(
                service_type=service_type,
                code=profession_code,
                defaults={
                    'name': profession_name,
                    'order': prof_order,
                },
            )

    for project in Project.objects.all():
        service_type_code = getattr(project, 'service_type_code', None)
        legacy_professions = getattr(project, 'service_professions_legacy', []) or []

        service_type = service_type_cache.get(service_type_code)
        project.service_type = service_type
        project.save(update_fields=['service_type'])

        if legacy_professions:
            normalized_names = [LEGACY_PROFESSION_ALIAS.get(name, name) for name in legacy_professions]
        else:
            normalized_names = []

        if service_type and normalized_names:
            professions_qs = ServiceProfession.objects.filter(
                service_type=service_type,
                name__in=normalized_names,
            )
            project.service_professions.set(professions_qs)
        else:
            project.service_professions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0004_allow_null_service_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='服务类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='服务类型名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
                'db_table': 'project_center_service_type',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='服务专业编码')),
                ('name', models.CharField(max_length=100, verbose_name='服务专业名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='project_center.servicetype', verbose_name='所属服务类型')),
            ],
            options={
                'verbose_name': '服务专业',
                'verbose_name_plural': '服务专业',
                'db_table': 'project_center_service_profession',
                'ordering': ['service_type__order', 'order', 'id'],
                'unique_together': {('service_type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='condition_detail',
            field=models.CharField(default='', max_length=200, verbose_name='付款条件详情'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='trigger_condition',
            field=models.CharField(choices=[('contract_signed', '合同签订'), ('consultation_report', '咨询意见书'), ('tripartite_result', '三方沟通成果'), ('review_report', '核图意见书'), ('preliminary_settlement', '结算初审'), ('final_settlement', '结算定案'), ('main_structure_completed', '主体封顶'), ('presale_license', '预售证'), ('completion_acceptance', '竣工验收'), ('completion_filing', '竣工备案')], default='contract_signed', max_length=50, verbose_name='触发条件'),
        ),
        migrations.RenameField(
            model_name='project',
            old_name='service_type',
            new_name='service_type_code',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='service_professions',
            new_name='service_professions_legacy',
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_center.servicetype', verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_professions',
            field=models.ManyToManyField(blank=True, related_name='projects', to='project_center.serviceprofession', verbose_name='服务专业'),
        ),
        migrations.RunPython(seed_service_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='service_type_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_professions_legacy',
        ),
    ]
