# Generated by Django 4.2.7 on 2025-11-08 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0005_servicetype_paymentplan_condition_detail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='service_profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_center.serviceprofession', verbose_name='所属专业'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='加入日期'),
        ),
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together={('project', 'user', 'role', 'service_profession')},
        ),
    ]
