# Generated by Django 4.2.7 on 2025-11-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0006_alter_projectteam_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='角色')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外部成员')),
                ('action', models.CharField(choices=[('added', '新增'), ('removed', '移除')], max_length=20, verbose_name='操作类型')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_change_logs', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_change_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_change_logs', to='project_center.project', verbose_name='项目')),
                ('service_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_center.serviceprofession', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '项目团队变更日志',
                'verbose_name_plural': '项目团队变更日志',
                'db_table': 'project_center_team_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
