# Generated by Django 4.2.7 on 2025-11-10 10:45

from django.db import migrations, models


def assign_units(apps, schema_editor):
    ProjectTeam = apps.get_model('project_center', 'ProjectTeam')
    ProjectTeamChangeLog = apps.get_model('project_center', 'ProjectTeamChangeLog')
    role_unit_map = {
        'business_manager': 'business',
        'project_manager': 'management',
        'professional_leader': 'internal_tech',
        'engineer': 'internal_tech',
        'technical_assistant': 'internal_tech',
        'external_leader': 'external_tech',
        'external_engineer': 'external_tech',
        'cost_reviewer_civil': 'internal_cost',
        'cost_reviewer_installation': 'internal_cost',
        'cost_engineer_civil': 'internal_cost',
        'cost_engineer_installation': 'internal_cost',
        'external_cost_reviewer_civil': 'external_cost',
        'external_cost_reviewer_installation': 'external_cost',
        'external_cost_engineer_civil': 'external_cost',
        'external_cost_engineer_installation': 'external_cost',
    }
    external_units = {'external_tech', 'external_cost'}

    for team in ProjectTeam.objects.all():
        unit = role_unit_map.get(team.role, 'management')
        if team.unit != unit or team.is_external != (unit in external_units):
            team.unit = unit
            team.is_external = unit in external_units
            team.save(update_fields=['unit', 'is_external'])

    for log in ProjectTeamChangeLog.objects.all():
        unit = role_unit_map.get(log.role, 'management')
        if log.unit != unit:
            log.unit = unit
            log.save(update_fields=['unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0009_projectteamnotification_operator_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.AddField(
            model_name='projectteamchangelog',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('business_manager', '商务经理'), ('project_manager', '项目经理'), ('professional_leader', '内部专业负责人'), ('engineer', '内部专业工程师'), ('technical_assistant', '技术助理'), ('external_leader', '外部专业负责人'), ('external_engineer', '外部专业工程师'), ('cost_reviewer_civil', '内部土建审核人'), ('cost_reviewer_installation', '内部安装审核人'), ('cost_engineer_civil', '内部土建造价师'), ('cost_engineer_installation', '内部安装造价师'), ('external_cost_reviewer_civil', '外部土建审核人'), ('external_cost_reviewer_installation', '外部安装审核人'), ('external_cost_engineer_civil', '外部土建造价师'), ('external_cost_engineer_installation', '外部安装造价师')], max_length=50, verbose_name='角色'),
        ),
        migrations.RunPython(assign_units, migrations.RunPython.noop),
    ]
