# Generated by Django 4.2.7 on 2025-11-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0010_projectteam_unit_projectteamchangelog_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDrawingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', '待处理'), ('approved', '通过'), ('changes_requested', '需修改')], default='pending', max_length=30, verbose_name='预审结果')),
                ('comment', models.TextField(blank=True, verbose_name='预审意见')),
                ('reviewed_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预审时间')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_reviews', to=settings.AUTH_USER_MODEL, verbose_name='预审人')),
            ],
            options={
                'verbose_name': '项目图纸预审记录',
                'verbose_name_plural': '项目图纸预审记录',
                'db_table': 'project_center_drawing_review',
                'ordering': ['-reviewed_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDrawingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='提交标题')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='提交说明')),
                ('submitter_role', models.CharField(blank=True, max_length=100, verbose_name='提交人角色')),
                ('submitted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('submitted', '待预审'), ('in_review', '预审中'), ('changes_requested', '需补充资料'), ('approved', '预审通过'), ('cancelled', '已取消')], default='submitted', max_length=30, verbose_name='预审状态')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='预审截止时间')),
                ('client_notified', models.BooleanField(default=False, verbose_name='是否已通知甲方')),
                ('client_notified_time', models.DateTimeField(blank=True, null=True, verbose_name='甲方通知时间')),
                ('client_notification_channel', models.CharField(blank=True, max_length=30, verbose_name='甲方通知渠道')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('latest_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project_center.projectdrawingreview', verbose_name='最新预审记录')),
            ],
            options={
                'verbose_name': '项目图纸提交',
                'verbose_name_plural': '项目图纸提交',
                'db_table': 'project_center_drawing_submission',
                'ordering': ['-submitted_time'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='drawing_precheck_completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='图纸预审完成时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='handover_submitted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='商务移交时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_status',
            field=models.CharField(choices=[('handover_pending', '待商务移交'), ('awaiting_drawings', '待图纸上传'), ('precheck_in_progress', '预审中'), ('changes_requested', '待补充资料'), ('ready_to_start', '待开工通知'), ('started', '已开工')], default='handover_pending', max_length=30, verbose_name='项目启动状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_status_updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='启动状态更新时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_notice_sent_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开工通知时间'),
        ),
        migrations.CreateModel(
            name='ProjectStartNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='通知主题')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('channel', models.CharField(choices=[('system', '系统通知'), ('email', '邮件'), ('sms', '短信'), ('manual', '线下确认')], default='system', max_length=30, verbose_name='通知渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('acknowledged', '已确认')], default='pending', max_length=30, verbose_name='通知状态')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='接收人姓名')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='接收人电话')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='接收人邮箱')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('acknowledged_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_notices_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_notices', to='project_center.project', verbose_name='项目')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_start_notices', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_notices', to='project_center.projectdrawingsubmission', verbose_name='关联图纸提交')),
            ],
            options={
                'verbose_name': '项目开工通知',
                'verbose_name_plural': '项目开工通知',
                'db_table': 'project_center_start_notice',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='projectdrawingsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_submissions', to='project_center.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectdrawingsubmission',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='projectdrawingreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project_center.projectdrawingsubmission', verbose_name='图纸提交'),
        ),
        migrations.CreateModel(
            name='ProjectDrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('category', models.CharField(choices=[('general', '通用资料'), ('architecture', '建筑'), ('structure', '结构'), ('mep', '机电'), ('civil', '土建'), ('other', '其他')], default='general', max_length=30, verbose_name='文件分类')),
                ('file', models.FileField(upload_to='project_drawings/%Y/%m/', verbose_name='文件')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_center.projectdrawingsubmission', verbose_name='图纸提交')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目图纸文件',
                'verbose_name_plural': '项目图纸文件',
                'db_table': 'project_center_drawing_file',
                'ordering': ['-uploaded_time'],
            },
        ),
    ]
