# Generated by Django 4.2.7 on 2025-11-14 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0011_projectdrawingreview_projectdrawingsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flow_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='当前步骤截止时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='flow_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='流程上下文'),
        ),
        migrations.AddField(
            model_name='project',
            name='flow_step',
            field=models.CharField(choices=[('pending_documents', '等待资料上传'), ('precheck', '资料预审'), ('start_notice', '开工通知'), ('opinions', '意见编制'), ('internal_review', '内部审核'), ('ready_to_push', '待推送'), ('pushed', '报告已推送')], default='pending_documents', max_length=40, verbose_name='当前流程步骤'),
        ),
        migrations.AddField(
            model_name='project',
            name='flow_step_started_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='步骤开始时间'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='trigger_condition',
            field=models.CharField(choices=[('business_commission_letter', '业务委托书'), ('contract_signed', '合同签订'), ('consultation_report', '咨询意见书'), ('tripartite_result', '三方沟通成果'), ('review_report', '核图意见书'), ('optimized_drawings', '优化后图纸'), ('settlement_declaration', '结算申报'), ('preliminary_settlement', '结算初步审核报告'), ('final_settlement', '结算定案报告'), ('construction_drawing_review', '施工图审图报告'), ('construction_drawing_release', '施工图正式出图'), ('construction_permit', '施工许可证'), ('predicted_area_report', '预测面积报告'), ('presale_license', '预售证'), ('foundation_completion', '基础施工完成'), ('basement_completion', '地下室施工完成'), ('main_structure_completed', '主体封顶'), ('completion_acceptance', '验工验收合格'), ('completion_filing', '验工验收备案')], default='contract_signed', max_length=50, verbose_name='触发条件'),
        ),
        migrations.AlterField(
            model_name='projectteamnotification',
            name='category',
            field=models.CharField(choices=[('team_change', '团队变更'), ('quality_alert', '质量提醒')], default='team_change', max_length=50, verbose_name='通知分类'),
        ),
        migrations.CreateModel(
            name='ProjectFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('advance', '流程流转'), ('note', '备注')], default='advance', max_length=30, verbose_name='动作类型')),
                ('from_step', models.CharField(blank=True, max_length=40, verbose_name='原步骤')),
                ('to_step', models.CharField(blank=True, max_length=40, verbose_name='目标步骤')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_flow_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目流程日志',
                'verbose_name_plural': '项目流程日志',
                'db_table': 'project_center_flow_log',
                'ordering': ['-created_time'],
            },
        ),
    ]
