# Generated by Django 4.2.7 on 2025-11-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0012_project_flow_deadline_project_flow_payload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_number',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
