# Generated by Django 4.2.7 on 2025-11-14 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0013_remove_project_contract_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to=settings.AUTH_USER_MODEL, verbose_name='甲方负责人账号'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_projects', to=settings.AUTH_USER_MODEL, verbose_name='设计方负责人账号'),
        ),
    ]
