# Generated by Django 4.2.7 on 2025-11-15 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0014_project_client_leader_project_design_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('business_manager', '商务经理'), ('project_manager', '项目经理'), ('professional_leader', '内部专业负责人'), ('engineer', '内部专业工程师'), ('technical_assistant', '技术助理'), ('external_leader', '外部专业负责人'), ('external_engineer', '外部专业工程师'), ('cost_reviewer_civil', '内部土建审核人'), ('cost_reviewer_installation', '内部安装审核人'), ('cost_engineer_civil', '内部土建造价师'), ('cost_engineer_installation', '内部安装造价师'), ('external_cost_reviewer_civil', '外部土建审核人'), ('external_cost_reviewer_installation', '外部安装审核人'), ('external_cost_engineer_civil', '外部土建造价师'), ('external_cost_engineer_installation', '外部安装造价师'), ('client_lead', '甲方项目负责人'), ('client_engineer', '甲方专业工程师'), ('design_lead', '设计方项目负责人'), ('design_engineer', '设计方专业工程师')], max_length=50, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队'), ('client_side', '甲方团队'), ('design_side', '设计团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.AlterField(
            model_name='projectteamchangelog',
            name='unit',
            field=models.CharField(choices=[('management', '管理团队'), ('business', '商务团队'), ('internal_tech', '内部技术团队'), ('external_tech', '外部技术团队'), ('internal_cost', '内部结算团队'), ('external_cost', '外部结算团队'), ('client_side', '甲方团队'), ('design_side', '设计团队')], default='management', max_length=32, verbose_name='所属团队'),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('task_type', models.CharField(choices=[('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知')], max_length=64, verbose_name='任务类型')),
                ('description', models.TextField(blank=True, verbose_name='任务说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('assigned_role', models.CharField(blank=True, max_length=50, verbose_name='指派角色')),
                ('target_unit', models.CharField(blank=True, max_length=32, verbose_name='目标团队')),
                ('due_time', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='取消操作人')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_completed', to=settings.AUTH_USER_MODEL, verbose_name='完成操作人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目任务',
                'verbose_name_plural': '项目任务',
                'db_table': 'project_center_task',
                'ordering': ['due_time', 'created_time'],
                'indexes': [models.Index(fields=['project', 'task_type'], name='project_cen_project_dca81f_idx'), models.Index(fields=['project', 'status'], name='project_cen_project_a1ad67_idx')],
            },
        ),
    ]
