# Generated by Django 4.2.7 on 2025-11-15 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0015_alter_projectteam_role_alter_projectteam_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(default=django.utils.timezone.now, verbose_name='会议日期')),
                ('topic', models.CharField(max_length=200, verbose_name='会议主题')),
                ('client_decision', models.TextField(blank=True, verbose_name='甲方意见')),
                ('design_decision', models.TextField(blank=True, verbose_name='设计方意见')),
                ('consultant_decision', models.TextField(blank=True, verbose_name='我方意见')),
                ('conclusions', models.TextField(blank=True, verbose_name='结论 / 待办')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_records', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '三方会议记录',
                'verbose_name_plural': '三方会议记录',
                'db_table': 'project_center_meeting_record',
                'ordering': ['-meeting_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDesignReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200, verbose_name='事项 / 问题')),
                ('status', models.CharField(choices=[('agree', '同意优化'), ('reject', '不同意优化'), ('partial', '部分同意')], default='agree', max_length=20, verbose_name='回复结果')),
                ('response_detail', models.TextField(blank=True, verbose_name='回复说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_replies', to='project_center.project', verbose_name='项目')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_replies', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '设计方回复',
                'verbose_name_plural': '设计方回复',
                'db_table': 'project_center_design_reply',
                'ordering': ['-created_time'],
            },
        ),
    ]
