# Generated by Django 4.2.7 on 2025-11-15 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        # ('production_quality', '0004_opinion_closed_at_opinion_cycle_time_hours_and_more'),  # 已删除production_quality模块
        ('project_center', '0016_projectmeetingrecord_projectdesignreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('agree', '同意'), ('reject', '不同意'), ('partial', '部分同意'), ('pending', '待确认')], default='pending', max_length=20, verbose_name='会议结论')),
                ('client_comment', models.TextField(blank=True, verbose_name='甲方意见')),
                ('design_comment', models.TextField(blank=True, verbose_name='设计方意见')),
                ('consultant_comment', models.TextField(blank=True, verbose_name='我方意见')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '三方会议结论',
                'verbose_name_plural': '三方会议结论',
                'db_table': 'project_center_meeting_decision',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='projectdesignreply',
            name='opinion_id',
            field=models.IntegerField(null=True, blank=True, verbose_name='关联意见ID', help_text='已删除生产质量模块，此字段保留用于历史数据'),
        ),
        migrations.AddIndex(
            model_name='projectdesignreply',
            index=models.Index(fields=['project', 'opinion_id'], name='project_cen_project_ff9332_idx'),
        ),
        migrations.AddField(
            model_name='projectmeetingdecision',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='project_center.projectmeetingrecord', verbose_name='会议记录'),
        ),
        migrations.AddField(
            model_name='projectmeetingdecision',
            name='opinion_id',
            field=models.IntegerField(null=True, blank=True, verbose_name='关联意见ID', help_text='已删除生产质量模块，此字段保留用于历史数据'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmeetingdecision',
            unique_together={('meeting', 'opinion_id')},
        ),
    ]
