# Generated by Django 4.2.7 on 2025-11-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0017_projectmeetingdecision_projectdesignreply_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_type',
            field=models.CharField(choices=[('project_complete_info', '完善项目信息'), ('configure_team', '配置项目团队'), ('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知')], max_length=64, verbose_name='任务类型'),
        ),
    ]
