# Generated by Django 4.2.7 on 2025-11-21 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0018_add_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='our_company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='我方单位名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='项目编号'),
        ),
    ]
