# Generated by Django 4.2.7 on 2025-11-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0019_project_initiation_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_batches',
            field=models.JSONField(blank=True, default=list, verbose_name='项目规模（分批次）'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_scope',
            field=models.CharField(blank=True, max_length=500, verbose_name='服务范围'),
        ),
    ]
