# Generated by Django 4.2.7 on 2025-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0020_project_project_batches_project_service_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='our_company_name',
        ),
        migrations.AddField(
            model_name='project',
            name='client_company_type',
            field=models.CharField(blank=True, choices=[('project_company', '项目公司'), ('regional_company', '区域公司'), ('group_company', '集团公司')], max_length=50, null=True, verbose_name='企业类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_credit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_enforcement_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='被执行人数量（启信宝公开数量）'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_established_date',
            field=models.DateField(blank=True, null=True, verbose_name='成立日期'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_final_case_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='终本案件数量（启信宝公开数量）'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_litigation_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='司法案件数量（启信宝公开数量）'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ownership_type',
            field=models.CharField(blank=True, choices=[('central_enterprise', '中央企业'), ('state_owned', '国有企业'), ('platform_company', '平台公司'), ('listed_company', '上市公司'), ('private_enterprise', '民营企业')], max_length=50, null=True, verbose_name='企业所有'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_registered_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_registered_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='注册资本（万元）'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_restriction_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='限制高消费数量（启信宝公开数量）'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_credit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='委托单位名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目负责人联系电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目负责人联系电话'),
        ),
    ]
