# Generated by Django 4.2.7 on 2025-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0021_remove_project_our_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（元）'),
        ),
    ]
