# Generated by Django 4.2.7 on 2025-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0022_add_contract_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='基本费（元）'),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('pure_rate', '纯费率计费'), ('base_fee_rate', '基本费+费率取费'), ('unit_price', '综合单价包干')], max_length=50, null=True, verbose_name='服务费取费方式'),
        ),
        migrations.AddField(
            model_name='project',
            name='fee_rate_coefficient',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='取费系数（%）'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_region',
            field=models.CharField(blank=True, choices=[('provincial_capital', '省会城市'), ('non_provincial_city', '非省会市级城市'), ('county_city', '县级城市'), ('tier1_city', '北京、上海、广州、深圳')], max_length=50, null=True, verbose_name='项目区域'),
        ),
        migrations.AddField(
            model_name='project',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='包干单价（元/平方米）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='structure_type',
            field=models.CharField(blank=True, choices=[('shear_wall', '剪力墙结构'), ('frame', '框架结构'), ('steel', '钢结构'), ('other', '其他')], max_length=50, null=True, verbose_name='结构形式'),
        ),
    ]
