# Generated by Django 4.2.7 on 2025-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0023_add_contract_calculation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='structure_type',
            field=models.CharField(blank=True, choices=[('shear_wall', '剪力墙结构'), ('frame', '框架结构'), ('steel', '钢结构'), ('other', '其他')], max_length=50, null=True, verbose_name='结构形式'),
        ),
    ]
