# Generated by Django 4.2.7 on 2025-11-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0024_allow_null_structure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteamnotification',
            name='category',
            field=models.CharField(choices=[('team_change', '团队变更'), ('quality_alert', '质量提醒'), ('approval', '审批通知')], default='team_change', max_length=50, verbose_name='通知分类'),
        ),
        migrations.AlterField(
            model_name='projectteamnotification',
            name='project',
            field=models.ForeignKey(blank=True, help_text='关联项目（可选，用于非项目相关通知时可为空）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_notifications', to='project_center.project', verbose_name='项目'),
        ),
    ]
