# Generated by Django 4.2.7 on 2025-12-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0019_project_initiation_document_and_more'),
        ('project_center', '0025_add_notification_confirmation'),
    ]

    operations = [
    ]
