# Generated by Django 4.2.7 on 2025-12-07 02:23

from django.db import migrations
from django.db.migrations.operations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0026_merge_20251204_1445'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- 只处理 project_center_project 表存在的字段
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_project') THEN
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS business_manager_id;
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS client_id;
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS client_leader_id;
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS created_by_id;
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS design_leader_id;
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS project_manager_id;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='project',
                    name='business_manager',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='client',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='client_leader',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='design_leader',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='project_manager',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS project_center_project_service_professions;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='project',
                    name='service_professions',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_project') THEN
                                ALTER TABLE project_center_project DROP COLUMN IF EXISTS service_type;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='project',
                    name='service_type',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- 检查表是否存在
                            IF EXISTS (
                                SELECT 1 FROM information_schema.tables 
                                WHERE table_name = 'project_center_archive'
                            ) THEN
                                -- 删除唯一约束（如果存在）
                                IF EXISTS (
                                    SELECT 1 FROM pg_constraint 
                                    WHERE conrelid = 'project_center_archive'::regclass 
                                    AND contype = 'u'
                                    AND conname LIKE '%project_id%archive_version%'
                                ) THEN
                                    ALTER TABLE project_center_archive 
                                    DROP CONSTRAINT IF EXISTS project_center_archive_project_id_archive_version_key;
                                END IF;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='projectarchive',
                    unique_together=None,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- 安全删除字段（如果表存在）
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_archive') THEN
                                ALTER TABLE project_center_archive DROP COLUMN IF EXISTS archived_by_id;
                                ALTER TABLE project_center_archive DROP COLUMN IF EXISTS project_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectdesignreply') THEN
                                ALTER TABLE project_center_projectdesignreply DROP COLUMN IF EXISTS opinion_id;
                                ALTER TABLE project_center_projectdesignreply DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectdesignreply DROP COLUMN IF EXISTS submitted_by_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectdocument') THEN
                                ALTER TABLE project_center_projectdocument DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectdocument DROP COLUMN IF EXISTS uploaded_by_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectdrawingfile') THEN
                                ALTER TABLE project_center_projectdrawingfile DROP COLUMN IF EXISTS submission_id;
                                ALTER TABLE project_center_projectdrawingfile DROP COLUMN IF EXISTS uploaded_by_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectdrawingreview') THEN
                                ALTER TABLE project_center_projectdrawingreview DROP COLUMN IF EXISTS reviewer_id;
                                ALTER TABLE project_center_projectdrawingreview DROP COLUMN IF EXISTS submission_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectdrawingsubmission') THEN
                                ALTER TABLE project_center_projectdrawingsubmission DROP COLUMN IF EXISTS latest_review_id;
                                ALTER TABLE project_center_projectdrawingsubmission DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectdrawingsubmission DROP COLUMN IF EXISTS submitter_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectflowlog') THEN
                                ALTER TABLE project_center_projectflowlog DROP COLUMN IF EXISTS actor_id;
                                ALTER TABLE project_center_projectflowlog DROP COLUMN IF EXISTS project_id;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='projectarchive',
                    name='archived_by',
                ),
                migrations.RemoveField(
                    model_name='projectarchive',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectdesignreply',
                    name='opinion',
                ),
                migrations.RemoveField(
                    model_name='projectdesignreply',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectdesignreply',
                    name='submitted_by',
                ),
                migrations.RemoveField(
                    model_name='projectdocument',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectdocument',
                    name='uploaded_by',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingfile',
                    name='submission',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingfile',
                    name='uploaded_by',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingreview',
                    name='reviewer',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingreview',
                    name='submission',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingsubmission',
                    name='latest_review',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingsubmission',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectdrawingsubmission',
                    name='submitter',
                ),
                migrations.RemoveField(
                    model_name='projectflowlog',
                    name='actor',
                ),
                migrations.RemoveField(
                    model_name='projectflowlog',
                    name='project',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.tables 
                                WHERE table_name = 'project_center_projectmeetingdecision'
                            ) THEN
                                ALTER TABLE project_center_projectmeetingdecision 
                                DROP CONSTRAINT IF EXISTS project_center_projectmeetingdecision_meeting_id_opinion_id_key;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='projectmeetingdecision',
                    unique_together=None,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectmeetingdecision') THEN
                                ALTER TABLE project_center_projectmeetingdecision DROP COLUMN IF EXISTS meeting_id;
                                ALTER TABLE project_center_projectmeetingdecision DROP COLUMN IF EXISTS opinion_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectmeetingrecord') THEN
                                ALTER TABLE project_center_projectmeetingrecord DROP COLUMN IF EXISTS created_by_id;
                                ALTER TABLE project_center_projectmeetingrecord DROP COLUMN IF EXISTS project_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectmilestone') THEN
                                ALTER TABLE project_center_projectmilestone DROP COLUMN IF EXISTS project_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectstartnotice') THEN
                                ALTER TABLE project_center_projectstartnotice DROP COLUMN IF EXISTS created_by_id;
                                ALTER TABLE project_center_projectstartnotice DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectstartnotice DROP COLUMN IF EXISTS recipient_user_id;
                                ALTER TABLE project_center_projectstartnotice DROP COLUMN IF EXISTS submission_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projecttask') THEN
                                ALTER TABLE project_center_projecttask DROP COLUMN IF EXISTS assigned_to_id;
                                ALTER TABLE project_center_projecttask DROP COLUMN IF EXISTS cancelled_by_id;
                                ALTER TABLE project_center_projecttask DROP COLUMN IF EXISTS completed_by_id;
                                ALTER TABLE project_center_projecttask DROP COLUMN IF EXISTS created_by_id;
                                ALTER TABLE project_center_projecttask DROP COLUMN IF EXISTS project_id;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='projectmeetingdecision',
                    name='meeting',
                ),
                migrations.RemoveField(
                    model_name='projectmeetingdecision',
                    name='opinion',
                ),
                migrations.RemoveField(
                    model_name='projectmeetingrecord',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='projectmeetingrecord',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectmilestone',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectstartnotice',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='projectstartnotice',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectstartnotice',
                    name='recipient_user',
                ),
                migrations.RemoveField(
                    model_name='projectstartnotice',
                    name='submission',
                ),
                migrations.RemoveField(
                    model_name='projecttask',
                    name='assigned_to',
                ),
                migrations.RemoveField(
                    model_name='projecttask',
                    name='cancelled_by',
                ),
                migrations.RemoveField(
                    model_name='projecttask',
                    name='completed_by',
                ),
                migrations.RemoveField(
                    model_name='projecttask',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='projecttask',
                    name='project',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.tables 
                                WHERE table_name = 'project_center_projectteam'
                            ) THEN
                                ALTER TABLE project_center_projectteam 
                                DROP CONSTRAINT IF EXISTS project_center_projectteam_project_id_service_profession_id_user_id_key;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='projectteam',
                    unique_together=None,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectteam') THEN
                                ALTER TABLE project_center_projectteam DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectteam DROP COLUMN IF EXISTS service_profession_id;
                                ALTER TABLE project_center_projectteam DROP COLUMN IF EXISTS user_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectteamchangelog') THEN
                                ALTER TABLE project_center_projectteamchangelog DROP COLUMN IF EXISTS member_id;
                                ALTER TABLE project_center_projectteamchangelog DROP COLUMN IF EXISTS operator_id;
                                ALTER TABLE project_center_projectteamchangelog DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectteamchangelog DROP COLUMN IF EXISTS service_profession_id;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_projectteamnotification') THEN
                                ALTER TABLE project_center_projectteamnotification DROP COLUMN IF EXISTS operator_id;
                                ALTER TABLE project_center_projectteamnotification DROP COLUMN IF EXISTS project_id;
                                ALTER TABLE project_center_projectteamnotification DROP COLUMN IF EXISTS recipient_id;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='projectteam',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectteam',
                    name='service_profession',
                ),
                migrations.RemoveField(
                    model_name='projectteam',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='projectteamchangelog',
                    name='member',
                ),
                migrations.RemoveField(
                    model_name='projectteamchangelog',
                    name='operator',
                ),
                migrations.RemoveField(
                    model_name='projectteamchangelog',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectteamchangelog',
                    name='service_profession',
                ),
                migrations.RemoveField(
                    model_name='projectteamnotification',
                    name='operator',
                ),
                migrations.RemoveField(
                    model_name='projectteamnotification',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectteamnotification',
                    name='recipient',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- serviceprofession 表可能不存在，跳过删除约束操作
                            -- 如果表存在，删除约束
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_serviceprofession') THEN
                                ALTER TABLE project_center_serviceprofession DROP CONSTRAINT IF EXISTS project_center_serviceprofession_service_type_id_code_key;
                            END IF;
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'production_management_service_profession') THEN
                                ALTER TABLE production_management_service_profession DROP CONSTRAINT IF EXISTS production_management_service_profession_service_type_id_code_key;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='serviceprofession',
                    unique_together=None,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- serviceprofession 表可能不存在，安全删除字段
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_center_serviceprofession') THEN
                                ALTER TABLE project_center_serviceprofession DROP COLUMN IF EXISTS service_type_id;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='serviceprofession',
                    name='service_type',
                ),
            ],
        ),
    ]
