# Generated by Django 4.2.7 on 2025-12-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_management', '0002_administrativearchive_archiveborrow_archivecategory_and_more'),
        ('project_center', '0027_remove_project_business_manager_and_more'),
        ('financial_management', '0002_alter_fundflow_project_receivableaccount_and_more'),
        ('resource_standard', '0006_alter_riskcase_project'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- 安全删除表（如果存在）
                            DROP TABLE IF EXISTS project_center_project CASCADE;
                            DROP TABLE IF EXISTS project_center_archive CASCADE;
                            DROP TABLE IF EXISTS project_center_projectdesignreply CASCADE;
                            DROP TABLE IF EXISTS project_center_projectdocument CASCADE;
                            DROP TABLE IF EXISTS project_center_projectdrawingfile CASCADE;
                            DROP TABLE IF EXISTS project_center_projectdrawingreview CASCADE;
                            DROP TABLE IF EXISTS project_center_projectdrawingsubmission CASCADE;
                            DROP TABLE IF EXISTS project_center_projectflowlog CASCADE;
                            DROP TABLE IF EXISTS project_center_projectmeetingdecision CASCADE;
                            DROP TABLE IF EXISTS project_center_projectmeetingrecord CASCADE;
                            DROP TABLE IF EXISTS project_center_projectmilestone CASCADE;
                            DROP TABLE IF EXISTS project_center_projectstartnotice CASCADE;
                            DROP TABLE IF EXISTS project_center_projecttask CASCADE;
                            DROP TABLE IF EXISTS project_center_projectteam CASCADE;
                            DROP TABLE IF EXISTS project_center_projectteamchangelog CASCADE;
                            DROP TABLE IF EXISTS project_center_projectteamnotification CASCADE;
                            DROP TABLE IF EXISTS project_center_serviceprofession CASCADE;
                            DROP TABLE IF EXISTS project_center_servicetype CASCADE;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Project',
                ),
                migrations.DeleteModel(
                    name='ProjectArchive',
                ),
                migrations.DeleteModel(
                    name='ProjectDesignReply',
                ),
                migrations.DeleteModel(
                    name='ProjectDocument',
                ),
                migrations.DeleteModel(
                    name='ProjectDrawingFile',
                ),
                migrations.DeleteModel(
                    name='ProjectDrawingReview',
                ),
                migrations.DeleteModel(
                    name='ProjectDrawingSubmission',
                ),
                migrations.DeleteModel(
                    name='ProjectFlowLog',
                ),
                migrations.DeleteModel(
                    name='ProjectMeetingDecision',
                ),
                migrations.DeleteModel(
                    name='ProjectMeetingRecord',
                ),
                migrations.DeleteModel(
                    name='ProjectMilestone',
                ),
                migrations.DeleteModel(
                    name='ProjectStartNotice',
                ),
                migrations.DeleteModel(
                    name='ProjectTask',
                ),
                migrations.DeleteModel(
                    name='ProjectTeam',
                ),
                migrations.DeleteModel(
                    name='ProjectTeamChangeLog',
                ),
                migrations.DeleteModel(
                    name='ProjectTeamNotification',
                ),
                migrations.DeleteModel(
                    name='ServiceProfession',
                ),
                migrations.DeleteModel(
                    name='ServiceType',
                ),
            ],
        ),
    ]
