# 所有模型已迁移到production_management模块
# 此文件提供向后兼容的导入，以避免迁移文件依赖问题
from backend.apps.production_management.models import (
    Project,
    ProjectTeam,
    ProjectTeamChangeLog,
    ProjectTeamNotification,
    ProjectTask,
    ProjectMilestone,
    ProjectDocument,
    ProjectArchive,
    ProjectDrawingSubmission,
    ProjectDrawingFile,
    ProjectDrawingReview,
    ProjectStartNotice,
    ProjectFlowLog,
    ProjectDesignReply,
    ProjectMeetingRecord,
    ServiceType,
    ServiceProfession,
    BusinessType,
    DesignStage,
    BusinessContract,
    BusinessPaymentPlan,
)

__all__ = [
    'Project',
    'ProjectTeam',
    'ProjectTeamChangeLog',
    'ProjectTeamNotification',
    'ProjectTask',
    'ProjectMilestone',
    'ProjectDocument',
    'ProjectArchive',
    'ProjectDrawingSubmission',
    'ProjectDrawingFile',
    'ProjectDrawingReview',
    'ProjectStartNotice',
    'ProjectFlowLog',
    'ProjectDesignReply',
    'ProjectMeetingRecord',
    'ServiceType',
    'ServiceProfession',
    'BusinessType',
    'DesignStage',
    'BusinessContract',
    'BusinessPaymentPlan',
]
