# Generated by Django 4.2.7 on 2025-12-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='api_call_lo_api_int_5f3522_idx',
            old_name='api_call_lo_api_int_pqr678_idx',
        ),
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='api_call_lo_status_e2e057_idx',
            old_name='api_call_lo_status_stu901_idx',
        ),
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='api_call_lo_called__a6d1e3_idx',
            old_name='api_call_lo_called__vwx234_idx',
        ),
        migrations.RenameIndex(
            model_name='apiinterface',
            new_name='api_interfa_code_8675eb_idx',
            old_name='api_interfa_code_789ghi_idx',
        ),
        migrations.RenameIndex(
            model_name='apiinterface',
            new_name='api_interfa_externa_206368_idx',
            old_name='api_interfa_externa_jkl012_idx',
        ),
        migrations.RenameIndex(
            model_name='apiinterface',
            new_name='api_interfa_method_f6eb0b_idx',
            old_name='api_interfa_method_mno345_idx',
        ),
        migrations.RenameIndex(
            model_name='apitestrecord',
            new_name='api_test_re_api_int_627b6b_idx',
            old_name='api_test_re_api_int_yza567_idx',
        ),
        migrations.RenameIndex(
            model_name='apitestrecord',
            new_name='api_test_re_status_4b2fdb_idx',
            old_name='api_test_re_status_bcd890_idx',
        ),
        migrations.RenameIndex(
            model_name='externalsystem',
            new_name='api_externa_code_50b599_idx',
            old_name='api_externa_code_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='externalsystem',
            new_name='api_externa_name_cf1ad4_idx',
            old_name='api_externa_name_456def_idx',
        ),
    ]
