# Generated by Django 4.2.7 on 2025-11-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryfeedback',
            new_name='delivery_fe_deliver_0bd1fe_idx',
            old_name='delivery_fe_deliver_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryfile',
            new_name='delivery_fi_deliver_6f15c1_idx',
            old_name='delivery_fi_deliver_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryrecord',
            new_name='delivery_re_status_afbf5f_idx',
            old_name='delivery_re_status_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryrecord',
            new_name='delivery_re_project_5c034b_idx',
            old_name='delivery_re_project_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryrecord',
            new_name='delivery_re_client__bf2f4c_idx',
            old_name='delivery_re_client_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryrecord',
            new_name='delivery_re_is_over_da8b56_idx',
            old_name='delivery_re_is_over_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverytracking',
            new_name='delivery_tr_deliver_097e00_idx',
            old_name='delivery_tr_deliver_idx',
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['delivery_number'], name='delivery_re_deliver_2dd305_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['deadline'], name='delivery_re_deadlin_0dc290_idx'),
        ),
    ]
