# Generated by Django 4.2.7 on 2025-12-11 13:42

import backend.apps.delivery_customer.models
from django.db import migrations, models


def rename_indexes_if_exist(apps, schema_editor):
    """只在索引存在时重命名索引"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 检查并重命名 filecategory 索引
        index_renames = [
            ('filecategory', 'file_catego_stage_s_idx', 'file_catego_stage_739c10_idx'),
            ('filecategory', 'file_catego_stage_i_idx', 'file_catego_stage_10f9d5_idx'),
            ('filetemplate', 'file_templat_stage_s_idx', 'file_templa_stage_fdc2ef_idx'),
            ('filetemplate', 'file_templat_stage_i_idx', 'file_templa_stage_390542_idx'),
            ('incomingdocument', 'incoming_do_stage_idx', 'incoming_do_stage_b9aef7_idx'),
            ('outgoingdocument', 'outgoing_do_stage_idx', 'outgoing_do_stage_76284f_idx'),
        ]
        
        for table_name, old_name, new_name in index_renames:
            # 检查索引是否存在
            cursor.execute("""
                SELECT COUNT(*) 
                FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [f'delivery_customer_{table_name}', old_name])
            
            if cursor.fetchone()[0] > 0:
                # 索引存在，执行重命名
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def reverse_rename_indexes(apps, schema_editor):
    """反向操作：恢复索引名称"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        index_renames = [
            ('filecategory', 'file_catego_stage_739c10_idx', 'file_catego_stage_s_idx'),
            ('filecategory', 'file_catego_stage_10f9d5_idx', 'file_catego_stage_i_idx'),
            ('filetemplate', 'file_templa_stage_fdc2ef_idx', 'file_templat_stage_s_idx'),
            ('filetemplate', 'file_templa_stage_390542_idx', 'file_templat_stage_i_idx'),
            ('incomingdocument', 'incoming_do_stage_b9aef7_idx', 'incoming_do_stage_idx'),
            ('outgoingdocument', 'outgoing_do_stage_76284f_idx', 'outgoing_do_stage_idx'),
        ]
        
        for table_name, new_name, old_name in index_renames:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [f'delivery_customer_{table_name}', new_name])
            
            if cursor.fetchone()[0] > 0:
                cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0008_add_client_contact_to_outgoing_document'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
        migrations.AlterField(
            model_name='filetemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='上传模板文件（Word、Excel、PDF等）', null=True, upload_to=backend.apps.delivery_customer.models.file_template_upload_path, verbose_name='模板文件'),
        ),
    ]
