# Generated by Django 4.2.7 on 2025-12-11 15:56

from django.db import migrations


def rename_indexes_if_exist(apps, schema_editor):
    """只在索引存在时重命名索引（因为0009迁移可能已经重命名了）"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 检查并重命名索引
        index_renames = [
            ('delivery_customer_filecategory', 'file_catego_stage_s_idx', 'file_catego_stage_739c10_idx'),
            ('delivery_customer_filecategory', 'file_catego_stage_i_idx', 'file_catego_stage_10f9d5_idx'),
            ('delivery_customer_filetemplate', 'file_templat_stage_s_idx', 'file_templa_stage_fdc2ef_idx'),
            ('delivery_customer_filetemplate', 'file_templat_stage_i_idx', 'file_templa_stage_390542_idx'),
            ('delivery_customer_incomingdocument', 'incoming_do_stage_idx', 'incoming_do_stage_b9aef7_idx'),
            ('delivery_customer_outgoingdocument', 'outgoing_do_stage_idx', 'outgoing_do_stage_76284f_idx'),
        ]
        
        for table_name, old_name, new_name in index_renames:
            # 检查旧索引是否存在
            cursor.execute("""
                SELECT COUNT(*) 
                FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [table_name, old_name])
            
            if cursor.fetchone()[0] > 0:
                # 索引存在，执行重命名
                cursor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}"')


def reverse_rename_indexes(apps, schema_editor):
    """反向操作：恢复索引名称"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        index_renames = [
            ('delivery_customer_filecategory', 'file_catego_stage_739c10_idx', 'file_catego_stage_s_idx'),
            ('delivery_customer_filecategory', 'file_catego_stage_10f9d5_idx', 'file_catego_stage_i_idx'),
            ('delivery_customer_filetemplate', 'file_templa_stage_fdc2ef_idx', 'file_templat_stage_s_idx'),
            ('delivery_customer_filetemplate', 'file_templa_stage_390542_idx', 'file_templat_stage_i_idx'),
            ('delivery_customer_incomingdocument', 'incoming_do_stage_b9aef7_idx', 'incoming_do_stage_idx'),
            ('delivery_customer_outgoingdocument', 'outgoing_do_stage_76284f_idx', 'outgoing_do_stage_idx'),
        ]
        
        for table_name, new_name, old_name in index_renames:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [table_name, new_name])
            
            if cursor.fetchone()[0] > 0:
                cursor.execute(f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0009_rename_file_catego_stage_s_idx_file_catego_stage_739c10_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
    ]
