# Generated by Django 4.2.7 on 2025-12-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0010_rename_file_catego_stage_s_idx_file_catego_stage_739c10_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='filecategory',
            new_name='file_catego_stage_739c10_idx',
            old_name='file_catego_stage_s_idx',
        ),
        migrations.RenameIndex(
            model_name='filecategory',
            new_name='file_catego_stage_10f9d5_idx',
            old_name='file_catego_stage_i_idx',
        ),
        migrations.RenameIndex(
            model_name='filetemplate',
            new_name='file_templa_stage_fdc2ef_idx',
            old_name='file_templat_stage_s_idx',
        ),
        migrations.RenameIndex(
            model_name='filetemplate',
            new_name='file_templa_stage_390542_idx',
            old_name='file_templat_stage_i_idx',
        ),
        migrations.RenameIndex(
            model_name='incomingdocument',
            new_name='incoming_do_stage_b9aef7_idx',
            old_name='incoming_do_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='outgoingdocument',
            new_name='outgoing_do_stage_76284f_idx',
            old_name='outgoing_do_stage_idx',
        ),
    ]
