-- 创建文件分类表
CREATE TABLE IF NOT EXISTS "file_category" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "code" varchar(50) NOT NULL DEFAULT '',
    "stage" varchar(20) NOT NULL,
    "description" text NOT NULL DEFAULT '',
    "sort_order" integer NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "created_by_id" bigint NULL
);

-- 创建索引
CREATE INDEX IF NOT EXISTS "file_category_stage_sort_idx" ON "file_category" ("stage", "sort_order");
CREATE INDEX IF NOT EXISTS "file_category_stage_active_idx" ON "file_category" ("stage", "is_active");
CREATE INDEX IF NOT EXISTS "file_category_stage_idx" ON "file_category" ("stage");
CREATE INDEX IF NOT EXISTS "file_category_created_at_idx" ON "file_category" ("created_at");

-- 创建唯一约束：同一阶段内分类名称唯一
CREATE UNIQUE INDEX IF NOT EXISTS "file_category_stage_name_unique" ON "file_category" ("stage", "name");

