# Generated by Django 4.2.7 on 2025-12-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0011_rename_file_catego_stage_s_idx_file_catego_stage_739c10_idx_and_more'),
        ('archive_management', '0002_administrativearchive_archiveborrow_archivecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
                'ordering': ['stage', 'sort_order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('delivery_customer.filecategory',),
        ),
    ]
