# Generated by Django 4.2.7 on 2025-11-09 15:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_management', '0004_remove_registrationrequest_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='标准编号')),
                ('name', models.CharField(max_length=200, verbose_name='标准名称')),
                ('standard_type', models.CharField(choices=[('client', '甲方标准'), ('company', '公司标准')], max_length=20, verbose_name='标准类型')),
                ('applicable_professions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ARCH', '建筑'), ('STRU', '结构'), ('ELEC', '电气'), ('WATR', '给排水'), ('HVAC', '暖通'), ('OTHR', '其他')], max_length=8), size=None, verbose_name='适用专业')),
                ('applicable_business_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('residential', '住宅'), ('complex', '综合体'), ('commercial', '商业'), ('office', '写字楼'), ('school', '学校'), ('hospital', '医院'), ('industrial', '工业厂房'), ('municipal', '市政'), ('other', '其他')], max_length=20), blank=True, default=list, size=None, verbose_name='适用业态')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('effective', '生效'), ('inactive', '停用')], default='draft', max_length=20, verbose_name='状态')),
                ('visible_scope', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('all', '全公司'), ('sichuan', '四川维海'), ('chongqing', '重庆维海'), ('xian', '西安维海'), ('hejian_chengdu', '禾间成都'), ('hongtian', '宏天升荣')], max_length=20), default=list, size=None, verbose_name='可见范围')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('editable_roles', models.ManyToManyField(blank=True, related_name='editable_standards', to='system_management.role', verbose_name='可编辑角色')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '审查标准',
                'verbose_name_plural': '审查标准',
                'db_table': 'resource_standard_standard',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='StandardReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200, verbose_name='部位名称')),
                ('review_point', models.TextField(verbose_name='审查要点')),
                ('issue_category', models.CharField(choices=[('compliance', '合规性'), ('drawing_quality', '图纸质量'), ('function', '功能性'), ('constructability', '可施工性'), ('other', '其他')], default='other', max_length=32, verbose_name='问题类别')),
                ('severity_level', models.CharField(choices=[('high', '重大'), ('medium', '一般'), ('low', '轻微')], default='medium', max_length=16, verbose_name='严重等级')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='resource_standard.standard', verbose_name='所属标准')),
            ],
            options={
                'verbose_name': '标准审查要点',
                'verbose_name_plural': '标准审查要点',
                'db_table': 'resource_standard_review_item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='材料编号')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(choices=[('m', '米'), ('m2', '平方米'), ('m3', '立方米'), ('t', '吨'), ('pcs', '个')], max_length=10, verbose_name='单位')),
                ('brand_requirement', models.CharField(blank=True, max_length=200, verbose_name='品牌要求')),
                ('applicable_regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sichuan', '四川'), ('chongqing', '重庆'), ('shaanxi', '陕西'), ('yunnan', '云南'), ('guizhou', '贵州'), ('other', '其他')], max_length=20), default=list, size=None, verbose_name='适用地区')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='综合单价')),
                ('price_type', models.CharField(choices=[('material', '材料价'), ('labor', '人工价'), ('machine', '机械价'), ('composite', '综合价')], default='material', max_length=20, verbose_name='价格类型')),
                ('price_source', models.CharField(choices=[('market', '市场价'), ('quota', '定额价'), ('client', '甲方确认价'), ('history', '历史项目价')], default='market', max_length=20, verbose_name='价格来源')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效时间')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='失效时间')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('change_note', models.TextField(blank=True, verbose_name='变更说明')),
                ('changed_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_prices_changed', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
            ],
            options={
                'verbose_name': '综合单价',
                'verbose_name_plural': '综合单价',
                'db_table': 'resource_standard_material_price',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CostIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='指标编号')),
                ('name', models.CharField(max_length=200, verbose_name='指标名称')),
                ('business_type', models.CharField(choices=[('residential', '住宅'), ('complex', '综合体'), ('commercial', '商业'), ('office', '写字楼'), ('school', '学校'), ('hospital', '医院'), ('industrial', '工业厂房'), ('municipal', '市政'), ('other', '其他')], max_length=20, verbose_name='业态类型')),
                ('building_type', models.CharField(blank=True, choices=[('high', '高层'), ('mid', '小高层'), ('low', '多层'), ('garage', '地下车库')], max_length=20, verbose_name='建筑类型')),
                ('region', models.CharField(choices=[('sichuan', '四川'), ('chongqing', '重庆'), ('shaanxi', '陕西'), ('yunnan', '云南'), ('guizhou', '贵州'), ('other', '其他')], max_length=20, verbose_name='地区')),
                ('data_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='数据年份')),
                ('steel_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='钢筋含量')),
                ('concrete_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='混凝土含量')),
                ('formwork_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='模板含量')),
                ('masonry_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='砌体含量')),
                ('door_window_index', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='门窗指标')),
                ('decoration_index', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='装饰指标')),
                ('reference_project', models.CharField(blank=True, max_length=200, verbose_name='参考项目')),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='样本数量')),
                ('data_reliability', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='数据可靠性')),
                ('update_frequency', models.CharField(choices=[('monthly', '月度'), ('quarterly', '季度'), ('yearly', '年度')], default='yearly', max_length=10, verbose_name='更新频率')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_indicators_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '成本指标',
                'verbose_name_plural': '成本指标',
                'db_table': 'resource_standard_cost_indicator',
                'ordering': ['-created_time'],
            },
        ),
    ]
