# Generated by Django 4.2.7 on 2025-11-09 15:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resource_standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='模板编号')),
                ('professional_type', models.CharField(choices=[('ARCH', '建筑'), ('STRU', '结构'), ('ELEC', '电气'), ('WATR', '给排水'), ('HVAC', '暖通'), ('OTHR', '其他')], max_length=32, verbose_name='专业类型')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('auto_fields', models.JSONField(blank=True, default=list, verbose_name='自动带出字段')),
                ('category_templates', models.JSONField(blank=True, default=dict, verbose_name='意见分类模板')),
                ('calculation_rules', models.JSONField(blank=True, default=dict, verbose_name='节省金额计算模板')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('default_review_points', models.ManyToManyField(blank=True, related_name='opinion_templates', to='resource_standard.standardreviewitem', verbose_name='默认审查要点')),
            ],
            options={
                'verbose_name': '意见书模板',
                'verbose_name_plural': '意见书模板',
                'db_table': 'resource_standard_opinion_template',
                'ordering': ['professional_type', 'name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='模板编号')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('consultation', '咨询意见书'), ('optimization', '优化报告'), ('review', '审图报告'), ('weekly', '每周快报')], max_length=30, verbose_name='模板类型')),
                ('service_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None, verbose_name='适用服务类型')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('cover_content', models.TextField(blank=True, verbose_name='封面设计')),
                ('header_footer', models.JSONField(blank=True, default=dict, verbose_name='页眉页脚设置')),
                ('sections', models.JSONField(blank=True, default=list, verbose_name='章节结构')),
                ('styles', models.JSONField(blank=True, default=dict, verbose_name='样式设置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报告模板',
                'verbose_name_plural': '报告模板',
                'db_table': 'resource_standard_report_template',
                'ordering': ['template_type', 'name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('cover_content', models.TextField(blank=True, verbose_name='封面设计')),
                ('header_footer', models.JSONField(blank=True, default=dict, verbose_name='页眉页脚设置')),
                ('sections', models.JSONField(blank=True, default=list, verbose_name='章节结构')),
                ('styles', models.JSONField(blank=True, default=dict, verbose_name='样式设置')),
                ('change_note', models.TextField(blank=True, verbose_name='变更说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='resource_standard.reporttemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '报告模板版本',
                'verbose_name_plural': '报告模板版本',
                'db_table': 'resource_standard_report_template_version',
                'ordering': ['template', '-version'],
                'unique_together': {('template', 'version')},
            },
        ),
        migrations.CreateModel(
            name='OpinionTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('auto_fields', models.JSONField(blank=True, default=list, verbose_name='自动带出字段')),
                ('category_templates', models.JSONField(blank=True, default=dict, verbose_name='意见分类模板')),
                ('calculation_rules', models.JSONField(blank=True, default=dict, verbose_name='节省金额计算模板')),
                ('change_note', models.TextField(blank=True, verbose_name='变更说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='resource_standard.opiniontemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '意见书模板版本',
                'verbose_name_plural': '意见书模板版本',
                'db_table': 'resource_standard_opinion_template_version',
                'ordering': ['template', '-version'],
                'unique_together': {('template', 'version')},
            },
        ),
    ]
