# Generated by Django 4.2.7 on 2025-11-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0009_projectteamnotification_operator_context'),
        ('resource_standard', '0002_opiniontemplate_reporttemplate_reporttemplateversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '知识标签',
                'verbose_name_plural': '知识标签',
                'db_table': 'resource_standard_knowledge_tag',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='方案编号')),
                ('name', models.CharField(max_length=200, verbose_name='方案名称')),
                ('domain', models.CharField(choices=[('structure', '结构'), ('architecture', '建筑'), ('mep', '机电'), ('geotechnical', '岩土'), ('other', '其他')], max_length=20, verbose_name='技术领域')),
                ('issue_type', models.CharField(blank=True, max_length=100, verbose_name='问题类型')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('problem_description', models.TextField(blank=True, verbose_name='问题描述')),
                ('traditional_method', models.TextField(blank=True, verbose_name='传统做法')),
                ('optimized_solution', models.TextField(verbose_name='优化方案')),
                ('technical_principle', models.TextField(blank=True, verbose_name='技术原理')),
                ('conditions', models.TextField(blank=True, verbose_name='适用条件')),
                ('cost_comparison', models.JSONField(blank=True, default=dict, verbose_name='成本对比')),
                ('saving_effect', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='节省效果')),
                ('difficulty', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='实施难度')),
                ('promotion_value', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='推广价值')),
                ('calculation_file', models.FileField(blank=True, upload_to='knowledge/solutions/', verbose_name='计算书')),
                ('drawing_sample', models.FileField(blank=True, upload_to='knowledge/solutions/', verbose_name='图纸示例')),
                ('effect_picture', models.ImageField(blank=True, upload_to='knowledge/solutions/', verbose_name='效果图')),
                ('reference_codes', models.TextField(blank=True, verbose_name='参考规范')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否已发布')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_solutions_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tags', models.ManyToManyField(blank=True, related_name='technical_solutions', to='resource_standard.knowledgetag')),
            ],
            options={
                'verbose_name': '技术解决方案',
                'verbose_name_plural': '技术解决方案',
                'db_table': 'resource_standard_technical_solution',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='RiskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='案例编号')),
                ('title', models.CharField(max_length=200, verbose_name='案例标题')),
                ('case_type', models.CharField(choices=[('technical', '技术风险'), ('schedule', '进度风险'), ('cost', '成本风险'), ('client', '客户风险')], max_length=20, verbose_name='案例类型')),
                ('occurred_on', models.DateField(blank=True, null=True, verbose_name='发生时间')),
                ('risk_description', models.TextField(verbose_name='风险描述')),
                ('root_cause', models.TextField(blank=True, verbose_name='根本原因')),
                ('impact_scope', models.TextField(blank=True, verbose_name='影响范围')),
                ('loss_estimation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='损失评估')),
                ('counter_measure', models.TextField(verbose_name='应对措施')),
                ('prevention', models.TextField(blank=True, verbose_name='预防措施')),
                ('outcome', models.TextField(blank=True, verbose_name='处理效果')),
                ('lessons', models.TextField(blank=True, verbose_name='经验教训')),
                ('recommend_score', models.PositiveSmallIntegerField(default=3, verbose_name='推荐指数')),
                ('applicable_scenarios', models.JSONField(blank=True, default=list, verbose_name='适用场景')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否已发布')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_cases_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_center.project', verbose_name='发生项目')),
                ('tags', models.ManyToManyField(blank=True, related_name='risk_cases', to='resource_standard.knowledgetag')),
            ],
            options={
                'verbose_name': '风险案例',
                'verbose_name_plural': '风险案例',
                'db_table': 'resource_standard_risk_case',
                'ordering': ['-created_time'],
            },
        ),
    ]
