# Generated by Django 4.2.7 on 2025-11-09 15:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0004_remove_registrationrequest_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resource_standard', '0003_knowledgetag_technicalsolution_riskcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='参数键')),
                ('value', models.CharField(max_length=200, verbose_name='参数值')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('category', models.CharField(default='business', max_length=50, verbose_name='分类')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'db_table': 'resource_standard_system_param',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('category', models.CharField(choices=[('architecture', '建筑'), ('structure', '结构'), ('mep', '机电'), ('landscape', '景观'), ('other', '其他')], default='other', max_length=20, verbose_name='专业类别')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('service_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None, verbose_name='适用服务类型')),
                ('workflow_template', models.CharField(blank=True, max_length=100, verbose_name='工作流模板')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_permissions', models.ManyToManyField(blank=True, related_name='professional_data_permissions', to='system_management.role', verbose_name='数据权限角色')),
                ('default_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_professional_categories', to=settings.AUTH_USER_MODEL, verbose_name='默认负责人')),
                ('operation_permissions', models.ManyToManyField(blank=True, related_name='professional_operation_permissions', to='system_management.role', verbose_name='操作权限角色')),
            ],
            options={
                'verbose_name': '专业分类',
                'verbose_name_plural': '专业分类',
                'db_table': 'resource_standard_professional_category',
                'ordering': ['order', 'code'],
            },
        ),
    ]
