# Generated by Django 4.2.7 on 2025-12-07 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0004_create_design_stage_model'),
        ('resource_standard', '0005_seed_professional_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_management.project', verbose_name='发生项目'),
        ),
    ]
