# Generated by Django 4.2.7 on 2026-01-23 14:30

from django.db import migrations, models


def add_category_field_if_not_exists(apps, schema_editor):
    """如果 category 字段不存在，则添加它"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 检查字段是否存在
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='admin_office_supply' 
            AND column_name='category'
        """)
        exists = cursor.fetchone()
        
        if not exists:
            # 字段不存在，添加它
            cursor.execute("""
                ALTER TABLE admin_office_supply 
                ADD COLUMN category VARCHAR(20) NOT NULL DEFAULT 'consumable'
            """)
            # 添加索引
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS admin_offic_categor_384180_idx 
                ON admin_office_supply (category, is_active)
            """)


def reverse_add_category_field(apps, schema_editor):
    """回滚操作：删除 category 字段"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 检查字段是否存在
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='admin_office_supply' 
            AND column_name='category'
        """)
        exists = cursor.fetchone()
        
        if exists:
            # 删除索引
            cursor.execute("""
                DROP INDEX IF EXISTS admin_offic_categor_384180_idx
            """)
            # 删除字段
            cursor.execute("""
                ALTER TABLE admin_office_supply 
                DROP COLUMN IF EXISTS category
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0002_administrativeaffair_affairprogressrecord_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_category_field_if_not_exists,
            reverse_add_category_field,
        ),
    ]
