# Generated by Django 4.2.7 on 2026-01-27 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrative_management', '0003_add_category_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealUsageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='seal_usage/documents/', verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='文件名称')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_seal_usage_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='administrative_management.sealusage', verbose_name='用印记录')),
            ],
            options={
                'verbose_name': '用印文件',
                'verbose_name_plural': '用印文件',
                'db_table': 'admin_seal_usage_file',
                'ordering': ['-uploaded_time'],
                'indexes': [models.Index(fields=['usage', 'uploaded_time'], name='admin_seal__usage_i_65aec0_idx')],
            },
        ),
    ]
