# Generated by Django 4.2.7 on 2026-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0005_seed_supply_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealusage',
            name='usage_count',
            field=models.IntegerField(default=1, verbose_name='用印份数'),
        ),
    ]
