# Generated by Django 4.2.7 on 2025-11-29 14:32

import backend.apps.litigation_management.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0001_initial'),  # 修复：project_center 已迁移到 production_management
        ('litigation_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitigationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('document_type', models.CharField(choices=[('complaint', '起诉状'), ('defense', '答辩状'), ('evidence', '证据材料'), ('legal_document', '法律文书'), ('other', '其他文档')], max_length=20, verbose_name='文档类型')),
                ('document_file', models.FileField(upload_to=backend.apps.litigation_management.models.litigation_document_upload_path, verbose_name='文档文件')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否最新版本')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '诉讼文档',
                'verbose_name_plural': '诉讼文档',
                'db_table': 'litigation_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200, verbose_name='费用名称')),
                ('expense_type', models.CharField(choices=[('litigation_fee', '诉讼费'), ('lawyer_fee', '律师费'), ('appraisal_fee', '鉴定费'), ('travel_fee', '差旅费'), ('other', '其他费用')], max_length=20, verbose_name='费用类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='费用金额')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='费用日期')),
                ('description', models.TextField(blank=True, verbose_name='费用说明')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('transfer', '转账'), ('check', '支票'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('payment_status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('reimbursed', '已报销'), ('written_off', '已核销')], default='pending', max_length=20, verbose_name='支付状态')),
                ('invoice_file', models.FileField(blank=True, upload_to='litigation_invoices/%Y/%m/%d/', verbose_name='发票文件')),
                ('reimbursement_applied', models.BooleanField(default=False, verbose_name='已申请报销')),
                ('reimbursement_status', models.CharField(blank=True, max_length=20, verbose_name='报销状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '诉讼费用',
                'verbose_name_plural': '诉讼费用',
                'db_table': 'litigation_expense',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigationNotificationConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trial_reminder', '开庭提醒'), ('preservation_renewal', '保全续封提醒'), ('appeal_deadline', '上诉期限提醒'), ('evidence_deadline', '举证期限提醒'), ('defense_deadline', '答辩期限提醒'), ('other', '其他提醒')], max_length=30, verbose_name='通知类型')),
                ('notification_title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('notification_content', models.TextField(verbose_name='通知内容')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('read_unconfirmed', '已读未确认'), ('escalated', '已升级')], default='pending', max_length=20, verbose_name='确认状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('sent_via_system', models.BooleanField(default=True, verbose_name='系统通知')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='短信通知')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='升级时间')),
                ('escalation_level', models.IntegerField(default=0, help_text='0=未升级，1=二次提醒，2=通知上级，3=电话通知', verbose_name='升级级别')),
                ('urgency_level', models.CharField(choices=[('normal', '一般'), ('important', '重要'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='紧急程度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '诉讼通知确认',
                'verbose_name_plural': '诉讼通知确认',
                'db_table': 'litigation_notification_confirmation',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('lawyer', '律师'), ('judge', '法官'), ('party', '当事人')], max_length=20, verbose_name='人员类型')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('law_firm', models.CharField(blank=True, max_length=200, verbose_name='律师事务所')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='执业证号')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='专业领域')),
                ('court_name', models.CharField(blank=True, max_length=200, verbose_name='法院名称')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('party_type', models.CharField(blank=True, help_text='自然人/法人/其他组织', max_length=20, verbose_name='当事人类型')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=255, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('role', models.CharField(blank=True, help_text='代理角色、审理角色、当事人角色等', max_length=100, verbose_name='角色')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评价')),
                ('evaluation', models.TextField(blank=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '诉讼人员',
                'verbose_name_plural': '诉讼人员',
                'db_table': 'litigation_person',
                'ordering': ['person_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LitigationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('filing', '立案'), ('trial', '庭审'), ('judgment', '判决'), ('execution', '执行')], max_length=20, verbose_name='流程类型')),
                ('process_date', models.DateField(verbose_name='流程日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='流程状态')),
                ('filing_number', models.CharField(blank=True, max_length=100, verbose_name='立案号')),
                ('court_name', models.CharField(blank=True, max_length=200, verbose_name='法院名称')),
                ('court_address', models.TextField(blank=True, verbose_name='法院地址')),
                ('court_contact', models.CharField(blank=True, max_length=100, verbose_name='法院联系方式')),
                ('judge_name', models.CharField(blank=True, max_length=100, verbose_name='法官姓名')),
                ('trial_location', models.CharField(blank=True, max_length=200, verbose_name='庭审地点')),
                ('trial_participants', models.TextField(blank=True, verbose_name='庭审人员')),
                ('trial_result', models.TextField(blank=True, verbose_name='庭审结果')),
                ('trial_notes', models.TextField(blank=True, verbose_name='庭审记录')),
                ('judgment_number', models.CharField(blank=True, max_length=100, verbose_name='判决书编号')),
                ('judgment_content', models.TextField(blank=True, verbose_name='判决内容')),
                ('judgment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='判决金额')),
                ('execution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='执行金额')),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='利息金额')),
                ('execution_deadline', models.DateField(blank=True, null=True, verbose_name='执行期限')),
                ('execution_status', models.CharField(blank=True, max_length=50, verbose_name='执行状态')),
                ('execution_result', models.TextField(blank=True, verbose_name='执行结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '诉讼流程',
                'verbose_name_plural': '诉讼流程',
                'db_table': 'litigation_process',
                'ordering': ['-process_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('timeline_type', models.CharField(choices=[('filing', '立案时间'), ('trial', '庭审时间'), ('judgment', '判决时间'), ('execution', '执行时间'), ('preservation_renewal', '保全续封时间'), ('appeal_deadline', '上诉期限'), ('evidence_deadline', '举证期限'), ('defense_deadline', '答辩期限'), ('other', '其他时间')], max_length=30, verbose_name='节点类型')),
                ('timeline_date', models.DateTimeField(verbose_name='节点时间')),
                ('description', models.TextField(blank=True, verbose_name='节点说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('delayed', '已延期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='节点状态')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='启用提醒')),
                ('reminder_days_before', models.JSONField(default=list, help_text='如：[7, 3, 1] 表示提前7天、3天、1天提醒', verbose_name='提前提醒天数')),
                ('reminder_sent', models.JSONField(default=list, help_text='记录已发送的提醒日期', verbose_name='已发送提醒')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '诉讼时间节点',
                'verbose_name_plural': '诉讼时间节点',
                'db_table': 'litigation_timeline',
                'ordering': ['timeline_date'],
            },
        ),
        migrations.CreateModel(
            name='PreservationSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_type', models.CharField(choices=[('property', '财产保全'), ('evidence', '证据保全'), ('behavior', '行为保全'), ('other', '其他保全')], max_length=20, verbose_name='保全类型')),
                ('seal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='保全金额')),
                ('seal_number', models.CharField(blank=True, max_length=100, verbose_name='保全案号')),
                ('court_name', models.CharField(max_length=200, verbose_name='法院名称')),
                ('start_date', models.DateField(verbose_name='保全开始日期')),
                ('end_date', models.DateField(verbose_name='保全到期日期')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='续封日期')),
                ('renewal_deadline', models.DateField(blank=True, help_text='续封申请截止日期', null=True, verbose_name='续封截止日期')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已到期'), ('renewed', '已续封'), ('released', '已解除')], default='active', max_length=20, verbose_name='保全状态')),
                ('renewal_applied', models.BooleanField(default=False, verbose_name='已申请续封')),
                ('renewal_materials', models.TextField(blank=True, verbose_name='续封所需材料')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '保全续封',
                'verbose_name_plural': '保全续封',
                'db_table': 'preservation_seal',
                'ordering': ['-end_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='litigationcase',
            new_name='litigation__case_nu_53b3ac_idx',
            old_name='litigation__case_nu_idx',
        ),
        migrations.RenameIndex(
            model_name='litigationcase',
            new_name='litigation__status_ad1fc8_idx',
            old_name='litigation__status_idx',
        ),
        migrations.RenameIndex(
            model_name='litigationcase',
            new_name='litigation__case_ty_d72f42_idx',
            old_name='litigation__case_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='litigationcase',
            new_name='litigation__priorit_29c708_idx',
            old_name='litigation__priorit_idx',
        ),
        migrations.RenameIndex(
            model_name='litigationcase',
            new_name='litigation__registr_6b7668_idx',
            old_name='litigation__registr_idx',
        ),
        migrations.AddField(
            model_name='preservationseal',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_seals', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='preservationseal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_preservation_seals', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='litigationtimeline',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='litigationtimeline',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_litigation_timelines', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='litigationtimeline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_litigation_timelines', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='litigationprocess',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='litigationprocess',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_litigation_processes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='litigationperson',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='litigationnotificationconfirmation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_confirmations', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='litigationnotificationconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_litigation_notifications', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='litigationnotificationconfirmation',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_litigation_notifications', to=settings.AUTH_USER_MODEL, verbose_name='升级通知对象'),
        ),
        migrations.AddField(
            model_name='litigationnotificationconfirmation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litigation_notification_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AddField(
            model_name='litigationnotificationconfirmation',
            name='seal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_confirmations', to='litigation_management.preservationseal', verbose_name='关联保全续封'),
        ),
        migrations.AddField(
            model_name='litigationnotificationconfirmation',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_confirmations', to='litigation_management.litigationtimeline', verbose_name='关联时间节点'),
        ),
        migrations.AddField(
            model_name='litigationexpense',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='litigationexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_litigation_expenses', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='litigationexpense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_expenses', to='project_center.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='litigationdocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='litigation_management.litigationcase', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='litigationdocument',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='litigation_management.litigationprocess', verbose_name='关联流程'),
        ),
        migrations.AddField(
            model_name='litigationdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_litigation_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddIndex(
            model_name='litigationtimeline',
            index=models.Index(fields=['timeline_date'], name='litigation__timelin_5d01ea_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationtimeline',
            index=models.Index(fields=['timeline_type'], name='litigation__timelin_b82c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationtimeline',
            index=models.Index(fields=['status'], name='litigation__status_3f4c27_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationnotificationconfirmation',
            index=models.Index(fields=['recipient', 'status'], name='litigation__recipie_70324a_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationnotificationconfirmation',
            index=models.Index(fields=['case', 'status'], name='litigation__case_id_ab5156_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationnotificationconfirmation',
            index=models.Index(fields=['sent_at'], name='litigation__sent_at_47be69_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationnotificationconfirmation',
            index=models.Index(fields=['notification_type', 'status'], name='litigation__notific_40ff43_idx'),
        ),
    ]
