# Generated by Django 4.2.7 on 2025-11-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0001_initial'),
        ('litigation_management', '0002_add_notification_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcase',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_cases', to='production_management.businesscontract', verbose_name='关联合同'),
        ),
        migrations.AlterField(
            model_name='litigationcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_cases', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='litigationexpense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_expenses', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='litigationexpense',
            name='reimbursement_status',
            field=models.CharField(blank=True, choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], max_length=20, verbose_name='报销状态'),
        ),
    ]
