# Generated by Django 4.2.7 on 2025-12-07 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# backend.apps.customer_management.migrations.0004_copy_contracts
# backend.apps.customer_management.migrations.0013_add_qixinbao_fields_remove_short_name

def forward_copy_contracts(apps, schema_editor):
    """从0004_copy_contracts迁移复制"""
    Project = apps.get_model('production_management', 'Project')
    PaymentPlan = apps.get_model('production_management', 'PaymentPlan')
    BusinessContract = apps.get_model('customer_management', 'BusinessContract')
    BusinessPaymentPlan = apps.get_model('customer_management', 'BusinessPaymentPlan')

    contracts = {}
    for project in Project.objects.all():
        contract, _ = BusinessContract.objects.get_or_create(
            project_id=project.id,
            defaults={
                'contract_number': getattr(project, 'contract_number', ''),
                'amount': getattr(project, 'contract_amount', None),
                'contract_date': getattr(project, 'contract_date', None),
                'attachment': getattr(project, 'contract_file', ''),
                'notes': '',
            }
        )
        changed = False
        if not contract.contract_number and getattr(project, 'contract_number', ''):
            contract.contract_number = project.contract_number
            changed = True
        if contract.amount in (None, 0) and getattr(project, 'contract_amount', None):
            contract.amount = project.contract_amount
            changed = True
        if not contract.contract_date and getattr(project, 'contract_date', None):
            contract.contract_date = project.contract_date
            changed = True
        if not contract.attachment and getattr(project, 'contract_file', None):
            contract.attachment = project.contract_file
            changed = True
        if changed:
            contract.save(update_fields=['contract_number', 'amount', 'contract_date', 'attachment'])
        contracts[project.id] = contract

    plan_objs = []
    for plan in PaymentPlan.objects.all():
        contract = contracts.get(plan.project_id)
        if not contract:
            contract = BusinessContract.objects.create(project_id=plan.project_id)
            contracts[plan.project_id] = contract
        plan_objs.append(BusinessPaymentPlan(
            contract=contract,
            phase_name=plan.phase_name,
            phase_description=plan.phase_description,
            planned_amount=plan.planned_amount,
            planned_date=plan.planned_date,
            actual_amount=plan.actual_amount,
            actual_date=plan.actual_date,
            status=plan.status,
            trigger_condition=plan.trigger_condition,
            condition_detail=plan.condition_detail,
            notes=plan.notes,
        ))
    if plan_objs:
        BusinessPaymentPlan.objects.bulk_create(plan_objs, batch_size=500)


def backward_copy_contracts(apps, schema_editor):
    """从0004_copy_contracts迁移复制"""
    BusinessContract = apps.get_model('customer_management', 'BusinessContract')
    BusinessPaymentPlan = apps.get_model('customer_management', 'BusinessPaymentPlan')
    BusinessPaymentPlan.objects.all().delete()
    BusinessContract.objects.all().delete()


def remove_short_name_if_exists(apps, schema_editor):
    """从0013迁移复制：安全删除short_name字段（如果存在）"""
    db_table = 'customer_client'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = 'short_name'
        """, [db_table])
        if cursor.fetchone():
            cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN short_name')


def reverse_remove_short_name(apps, schema_editor):
    """从0013迁移复制：恢复short_name字段"""
    pass


class Migration(migrations.Migration):

    replaces = [('customer_management', '0001_initial'), ('customer_management', '0002_initial'), ('customer_management', '0003_businesscontract_businesspaymentplan'), ('customer_management', '0004_copy_contracts'), ('customer_management', '0005_contractapproval_contractchange_contractfile_and_more'), ('customer_management', '0006_alter_businesscontract_contract_number'), ('customer_management', '0007_contractstatuslog'), ('customer_management', '0008_businessopportunity_client_client_type_and_more'), ('customer_management', '0012_add_quotation_mode_fields'), ('customer_management', '0013_add_qixinbao_fields_remove_short_name'), ('customer_management', '0011_remove_client_address_remove_client_email_and_more'), ('customer_management', '0010_client_consumption_limit_count_and_more'), ('customer_management', '0009_add_legal_risk_fields'), ('customer_management', '0014_merge_20251126_1419'), ('customer_management', '0015_remove_client_blacklist_details_remove_client_code_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='客户简称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('client_level', models.CharField(choices=[('vip', 'VIP客户'), ('important', '重要客户'), ('general', '一般客户'), ('potential', '潜在客户')], default='general', max_length=20, verbose_name='客户等级')),
                ('credit_level', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('normal', '一般'), ('poor', '较差'), ('bad', '很差')], default='normal', max_length=20, verbose_name='信用等级')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='网站')),
                ('total_contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计合同金额')),
                ('total_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计回款金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('health_score', models.IntegerField(default=0, verbose_name='健康度评分')),
                ('description', models.TextField(blank=True, verbose_name='客户描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer_client',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(max_length=20, verbose_name='项目状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management.client', verbose_name='客户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '客户项目',
                'verbose_name_plural': '客户项目',
                'db_table': 'customer_client_project',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要联系人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer_management.client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户联系人',
                'verbose_name_plural': '客户联系人',
                'db_table': 'customer_contact',
            },
        ),
        migrations.CreateModel(
            name='BusinessContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='合同日期')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='business_contracts/%Y/%m/', verbose_name='合同附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_contract', to='production_management.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '商务合同',
                'verbose_name_plural': '商务合同',
                'db_table': 'business_contract',
            },
        ),
        migrations.CreateModel(
            name='BusinessPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100, verbose_name='回款阶段')),
                ('phase_description', models.TextField(blank=True, verbose_name='阶段描述')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划金额')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际金额')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('pending', '待回款'), ('partial', '部分回款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_condition', models.CharField(blank=True, max_length=100, verbose_name='触发条件')),
                ('condition_detail', models.CharField(blank=True, max_length=200, verbose_name='付款条件详情')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='customer_management.businesscontract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '商务回款计划',
                'verbose_name_plural': '商务回款计划',
                'db_table': 'business_payment_plan',
                'ordering': ['planned_date'],
            },
        ),
        migrations.RunPython(
            code=forward_copy_contracts,
            reverse_code=backward_copy_contracts,
        ),
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1, help_text='1=商务经理, 2=部门经理, 3=总经理', verbose_name='审核层级')),
                ('result', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('pending', '待审核')], default='pending', max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合同审核记录',
                'verbose_name_plural': '合同审核记录',
                'db_table': 'business_contract_approval',
                'ordering': ['approval_level', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('amount', '金额变更'), ('period', '期限变更'), ('terms', '条款变更'), ('party', '双方变更'), ('other', '其他变更')], max_length=20, verbose_name='变更类型')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('before_content', models.TextField(blank=True, verbose_name='变更前内容')),
                ('after_content', models.TextField(verbose_name='变更后内容')),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, help_text='金额变更时填写', max_digits=12, null=True, verbose_name='变更金额')),
                ('change_date', models.DateField(default=django.utils.timezone.now, verbose_name='变更日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合同变更记录',
                'verbose_name_plural': '合同变更记录',
                'db_table': 'business_contract_change',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('original', '合同原件'), ('scanned', '合同扫描件'), ('attachment', '合同附件'), ('supplement', '补充协议'), ('change', '变更协议'), ('termination', '终止协议'), ('other', '其他文件')], default='scanned', max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='文件')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '合同文件',
                'verbose_name_plural': '合同文件',
                'db_table': 'business_contract_file',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='businesscontract',
            options={'ordering': ['-created_time'], 'verbose_name': '商务合同', 'verbose_name_plural': '商务合同'},
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='attachment',
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='合同审批人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customer_management.client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（含税）'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_amount_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（不含税）'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_amount_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同税额'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_name',
            field=models.CharField(blank=True, help_text='如未填写，将使用合同编号', max_length=200, verbose_name='合同名称'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_period',
            field=models.IntegerField(blank=True, help_text='自动计算：结束日期-开始日期', null=True, verbose_name='合同期限（天）'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_type',
            field=models.CharField(choices=[('framework', '框架合同'), ('project', '项目合同'), ('supplement', '补充协议'), ('change', '变更协议'), ('termination', '终止协议'), ('other', '其他')], default='project', max_length=20, verbose_name='合同类型'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='description',
            field=models.TextField(blank=True, verbose_name='合同描述'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同生效日期'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同结束日期'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, help_text='用于补充协议、变更协议关联主合同', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contracts', to='customer_management.businesscontract', verbose_name='主合同'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_a_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='甲方联系人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_a_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='甲方名称'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_b_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='乙方联系人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_b_name',
            field=models.CharField(blank=True, default='四川维海科技有限公司', max_length=200, verbose_name='乙方名称'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已回款金额'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已结算金额'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='合同签订人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同开始日期'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewing', '审核中'), ('signed', '已签订'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='合同状态'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='默认6%，可调整', max_digits=5, verbose_name='税率(%)'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='unpaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='自动计算：合同金额-已回款金额', max_digits=12, null=True, verbose_name='未回款金额'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同签订日期'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_number',
            field=models.CharField(help_text='唯一标识，建议格式：VIH-CON-YYYY-NNNN', max_length=100, unique=True, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['contract_number'], name='business_co_contrac_e8523a_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['status', 'contract_type'], name='business_co_status_a1c505_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['contract_date'], name='business_co_contrac_dcd013_idx'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_changes', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='customer_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_changes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='customer_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_number',
            field=models.CharField(blank=True, help_text='唯一标识，留空将自动生成（格式：VIH-CON-YYYY-NNNN）', max_length=100, null=True, unique=True, verbose_name='合同编号'),
        ),
        migrations.CreateModel(
            name='ContractStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewing', '审核中'), ('signed', '已签订'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewing', '审核中'), ('signed', '已签订'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], max_length=20, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_status_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='customer_management.businesscontract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同状态流转日志',
                'verbose_name_plural': '合同状态流转日志',
                'db_table': 'business_contract_status_log',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.CharField(blank=True, help_text='自动生成：OPP-YYYY-NNNN', max_length=50, null=True, unique=True, verbose_name='商机编号')),
                ('name', models.CharField(max_length=200, verbose_name='商机名称')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='项目名称')),
                ('project_address', models.CharField(blank=True, max_length=500, verbose_name='项目地址')),
                ('project_type', models.CharField(blank=True, help_text='住宅/综合体/商业/写字楼等', max_length=50, verbose_name='项目业态')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='建筑面积（平方米）')),
                ('drawing_stage', models.CharField(blank=True, max_length=50, verbose_name='图纸阶段')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='预计金额（万元）')),
                ('success_probability', models.IntegerField(default=10, help_text='10/30/50/70/90', verbose_name='成功概率（%）')),
                ('weighted_amount', models.DecimalField(decimal_places=2, default=0, help_text='预计金额 × 成功概率', max_digits=15, verbose_name='加权金额')),
                ('status', models.CharField(choices=[('potential', '潜在客户'), ('initial_contact', '初步接触'), ('requirement_confirmed', '需求确认'), ('quotation', '方案报价'), ('negotiation', '商务谈判'), ('won', '赢单'), ('lost', '输单'), ('cancelled', '已取消')], default='potential', max_length=30, verbose_name='商机状态')),
                ('urgency', models.CharField(choices=[('normal', '普通'), ('urgent', '紧急'), ('very_urgent', '特急')], default='normal', max_length=20, verbose_name='紧急程度')),
                ('expected_sign_date', models.DateField(blank=True, null=True, verbose_name='预计签约时间')),
                ('actual_sign_date', models.DateField(blank=True, null=True, verbose_name='实际签约日期')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实际签约金额（万元）')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('win_reason', models.TextField(blank=True, verbose_name='赢单原因')),
                ('loss_reason', models.TextField(blank=True, verbose_name='输单原因')),
                ('health_score', models.IntegerField(default=0, help_text='0-100分', verbose_name='健康度评分')),
                ('description', models.TextField(blank=True, verbose_name='商机描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('business_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='负责商务')),
            ],
            options={
                'verbose_name': '商机',
                'verbose_name_plural': '商机',
                'db_table': 'business_opportunity',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('developer', '开发商'), ('government', '政府单位'), ('design_institute', '设计院'), ('general_contractor', '总包单位'), ('other', '其他')], max_length=20, verbose_name='客户类型'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_scale',
            field=models.CharField(blank=True, choices=[('large', '大型'), ('medium', '中型'), ('small', '小型')], max_length=20, verbose_name='企业规模'),
        ),
        migrations.AddField(
            model_name='client',
            name='grade',
            field=models.CharField(blank=True, choices=[('strategic', '战略客户'), ('core', '核心客户'), ('potential', '潜力客户'), ('regular', '常规客户'), ('nurturing', '培育客户'), ('observing', '观察客户')], help_text='用于商机管理的客户分级', max_length=20, null=True, verbose_name='客户分级'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='client',
            name='score',
            field=models.IntegerField(default=0, help_text='0-100分，用于自动计算客户分级', verbose_name='客户评分'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('self_development', '自主开发'), ('customer_referral', '老客户推荐'), ('industry_exhibition', '行业展会'), ('online_promotion', '网络推广'), ('other', '其他')], max_length=20, verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='client',
            name='unified_credit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='统一信用代码'),
        ),
        migrations.CreateModel(
            name='QuotationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('rate', '费率'), ('unit_price', '单价'), ('fixed', '固定金额')], max_length=20, verbose_name='规则类型')),
                ('project_type', models.CharField(blank=True, max_length=50, verbose_name='项目业态')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='服务类型')),
                ('structure_type', models.CharField(blank=True, max_length=50, verbose_name='结构形式')),
                ('rule_params', models.JSONField(default=dict, help_text='存储费率、单价等参数', verbose_name='规则参数')),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最小面积')),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最大面积')),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='调整系数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='规则说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotation_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报价规则',
                'verbose_name_plural': '报价规则',
                'db_table': 'business_quotation_rule',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('potential', '潜在客户'), ('initial_contact', '初步接触'), ('requirement_confirmed', '需求确认'), ('quotation', '方案报价'), ('negotiation', '商务谈判'), ('won', '赢单'), ('lost', '输单'), ('cancelled', '已取消')], max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('potential', '潜在客户'), ('initial_contact', '初步接触'), ('requirement_confirmed', '需求确认'), ('quotation', '方案报价'), ('negotiation', '商务谈判'), ('won', '赢单'), ('lost', '输单'), ('cancelled', '已取消')], max_length=30, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_status_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='customer_management.businessopportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机状态流转日志',
                'verbose_name_plural': '商机状态流转日志',
                'db_table': 'business_opportunity_status_log',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateField(verbose_name='跟进日期')),
                ('follow_type', models.CharField(choices=[('phone', '电话沟通'), ('visit', '上门拜访'), ('online_meeting', '线上会议'), ('email', '邮件沟通'), ('other', '其他')], default='phone', max_length=20, verbose_name='跟进方式')),
                ('participants', models.CharField(blank=True, max_length=500, verbose_name='参与人员')),
                ('content', models.TextField(verbose_name='跟进内容')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('next_plan', models.TextField(blank=True, verbose_name='下一步计划')),
                ('next_follow_date', models.DateField(blank=True, null=True, verbose_name='预计下次跟进')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_followups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customer_management.businessopportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机跟进记录',
                'verbose_name_plural': '商机跟进记录',
                'db_table': 'business_opportunity_followup',
                'ordering': ['-follow_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1, help_text='1=商务部经理, 2=商务总监, 3=总经理', verbose_name='审核层级')),
                ('result', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('pending', '待审核')], default='pending', max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='customer_management.businessopportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机审批记录',
                'verbose_name_plural': '商机审批记录',
                'db_table': 'business_opportunity_approval',
                'ordering': ['approval_level', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='customer_management.client', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='OpportunityQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('draft', '初稿报价'), ('customer', '客户报价'), ('final', '最终报价')], default='draft', max_length=20, verbose_name='版本类型')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='建筑面积（平方米）')),
                ('project_type', models.CharField(blank=True, max_length=50, verbose_name='项目业态')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='服务类型')),
                ('structure_type', models.CharField(blank=True, max_length=50, verbose_name='结构形式')),
                ('base_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='基准报价（万元）')),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='调整系数')),
                ('final_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最终报价（万元）')),
                ('quotation_note', models.TextField(blank=True, verbose_name='报价说明')),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/', verbose_name='报价文件')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customer_management.businessopportunity', verbose_name='商机')),
                ('quotation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_management.quotationrule', verbose_name='使用的报价规则')),
            ],
            options={
                'verbose_name': '商机报价',
                'verbose_name_plural': '商机报价',
                'db_table': 'business_opportunity_quotation',
                'ordering': ['-version_number', '-created_time'],
                'unique_together': {('opportunity', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['opportunity_number'], name='business_op_opportu_247937_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['status'], name='business_op_status_97cb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['business_manager', 'status'], name='business_op_busines_690fca_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['expected_sign_date'], name='business_op_expecte_ffe177_idx'),
        ),
        migrations.AddField(
            model_name='opportunityquotation',
            name='quotation_mode',
            field=models.CharField(choices=[('rate', '纯费率模式'), ('base_fee_rate', '基本费+费率模式'), ('fixed', '包干价模式'), ('segmented', '分段累进模式'), ('min_savings_rate', '最低节省+费率模式'), ('performance_linked', '绩效挂钩模式'), ('hybrid', '混合计价模式')], default='rate', help_text='选择报价计算模式', max_length=30, verbose_name='报价模式'),
        ),
        migrations.AddField(
            model_name='opportunityquotation',
            name='mode_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON格式存储报价模式相关参数（费率、基本费、分段配置等）', verbose_name='模式参数'),
        ),
        migrations.AddField(
            model_name='opportunityquotation',
            name='cap_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='服务费上限，超过此金额按封顶费计算（可选）', max_digits=15, null=True, verbose_name='封顶费（万元）'),
        ),
        migrations.AddField(
            model_name='opportunityquotation',
            name='saved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='用于计算服务费的节省金额', max_digits=15, null=True, verbose_name='节省金额（万元）'),
        ),
        migrations.AddField(
            model_name='opportunityquotation',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='根据报价模式计算的服务费', max_digits=15, verbose_name='服务费（万元）'),
        ),
        migrations.AddField(
            model_name='opportunityquotation',
            name='calculation_steps',
            field=models.JSONField(blank=True, default=list, help_text='JSON格式存储计算过程，用于展示计算明细', verbose_name='计算步骤'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_representative',
            field=models.CharField(blank=True, help_text='从启信宝API获取', max_length=100, verbose_name='法定代表人'),
        ),
        migrations.AddField(
            model_name='client',
            name='established_date',
            field=models.DateField(blank=True, help_text='从启信宝API获取', null=True, verbose_name='成立日期'),
        ),
        migrations.AddField(
            model_name='client',
            name='registered_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='从启信宝API获取', max_digits=15, null=True, verbose_name='注册资本（万元）'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_phone',
            field=models.CharField(blank=True, help_text='从启信宝API获取', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_email',
            field=models.EmailField(blank=True, help_text='从启信宝API获取', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_address',
            field=models.CharField(blank=True, help_text='从启信宝API获取', max_length=500, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_industry',
            field=models.CharField(blank=True, help_text='从启信宝API获取', max_length=100, verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_group',
            field=models.CharField(blank=True, help_text='从启信宝API获取', max_length=200, verbose_name='所属集团'),
        ),
        migrations.RunPython(
            code=remove_short_name_if_exists,
            reverse_code=reverse_remove_short_name,
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='职务'),
        ),
        migrations.AddField(
            model_name='client',
            name='consumption_limit_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='限制高消费数量'),
        ),
        migrations.AddField(
            model_name='client',
            name='executed_person_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='被执行人数量'),
        ),
        migrations.AddField(
            model_name='client',
            name='final_case_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='终本案件数量'),
        ),
        migrations.AddField(
            model_name='client',
            name='litigation_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='司法案件数量'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_risk_level',
            field=models.CharField(choices=[('low', '低风险'), ('medium_low', '中低风险'), ('medium', '中风险'), ('medium_high', '中高风险'), ('high', '高风险'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='法律风险等级'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_group',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_scale',
        ),
        migrations.RemoveField(
            model_name='client',
            name='short_name',
        ),
        migrations.AddField(
            model_name='client',
            name='legal_risk_level',
            field=models.CharField(choices=[('low', '低风险'), ('medium_low', '中低风险'), ('medium', '中风险'), ('medium_high', '中高风险'), ('high', '高风险'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='法律风险等级'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='adjustment_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='旧版报价字段，保留兼容性', max_digits=5, verbose_name='调整系数'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='base_quotation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='旧版报价字段，保留兼容性', max_digits=15, verbose_name='基准报价（万元）'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='final_quotation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='最终报价金额（兼容旧版：base_quotation × adjustment_factor；新版：service_fee）', max_digits=15, verbose_name='最终报价（万元）'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='quotation_rule',
            field=models.ForeignKey(blank=True, help_text='旧版报价规则，保留兼容性', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_management.quotationrule', verbose_name='使用的报价规则'),
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateTimeField(verbose_name='计划日期')),
                ('plan_title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('plan_purpose', models.TextField(verbose_name='拜访目的')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='拜访地点')),
                ('participants', models.CharField(blank=True, max_length=500, verbose_name='参与人员')),
                ('status', models.CharField(choices=[('planned', '已计划'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='计划状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visit_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_plans', to='customer_management.businessopportunity', verbose_name='关联商机')),
            ],
            options={
                'verbose_name': '拜访计划',
                'verbose_name_plural': '拜访计划',
                'db_table': 'customer_visit_plan',
                'ordering': ['plan_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(verbose_name='签到时间')),
                ('checkin_location', models.CharField(max_length=200, verbose_name='签到地点')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_checkins', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkins', to=settings.AUTH_USER_MODEL, verbose_name='签到人')),
                ('visit_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='customer_management.visitplan', verbose_name='关联拜访计划')),
            ],
            options={
                'verbose_name': '拜访签到',
                'verbose_name_plural': '拜访签到',
                'db_table': 'customer_visit_checkin',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('visit', '客户拜访'), ('phone', '电话沟通'), ('meeting', '会议'), ('email', '邮件沟通'), ('other', '其他')], max_length=20, verbose_name='活动类型')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='活动地点')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customer_management.client', verbose_name='关联客户')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customer_management.businessopportunity', verbose_name='关联商机')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_activities', to=settings.AUTH_USER_MODEL, verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '销售活动',
                'verbose_name_plural': '销售活动',
                'db_table': 'sales_activity',
                'ordering': ['start_time', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('visit', '客户拜访'), ('phone', '电话沟通'), ('meeting', '会议'), ('email', '邮件沟通'), ('wechat', '微信沟通'), ('other', '其他')], max_length=20, verbose_name='关系类型')),
                ('title', models.CharField(max_length=200, verbose_name='关系标题')),
                ('content', models.TextField(verbose_name='关系内容')),
                ('relationship_date', models.DateTimeField(verbose_name='关系日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('participants', models.CharField(blank=True, max_length=500, verbose_name='参与人员')),
                ('next_action', models.TextField(blank=True, verbose_name='下一步行动')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='下次行动日期')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_relationships', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='customer_management.businessopportunity', verbose_name='关联商机')),
            ],
            options={
                'verbose_name': '客户关系',
                'verbose_name_plural': '客户关系',
                'db_table': 'customer_relationship',
                'ordering': ['-relationship_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, verbose_name='联系邮箱')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区县')),
                ('lead_source', models.CharField(choices=[('rcc_platform', 'RCC平台信息'), ('website', '官网咨询'), ('phone', '电话咨询'), ('exhibition', '展会'), ('referral', '转介绍'), ('other', '其他')], default='other', max_length=50, verbose_name='线索来源')),
                ('channel', models.CharField(blank=True, max_length=50, verbose_name='渠道')),
                ('follow_status', models.CharField(choices=[('unhandled', '未处理'), ('contact_valid', '联系方式有效'), ('contact_invalid', '联系方式无效'), ('converted', '已转化'), ('lost', '已流失')], default='unhandled', max_length=20, verbose_name='跟进状态')),
                ('latest_followup_note', models.TextField(blank=True, verbose_name='最新跟进记录')),
                ('actual_followup_time', models.DateTimeField(blank=True, null=True, verbose_name='实际跟进时间')),
                ('days_not_followed', models.IntegerField(default=0, verbose_name='未跟进天数')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('is_friend_added', models.BooleanField(default=False, verbose_name='是否已加好友')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customer_management.client', verbose_name='转化客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_leads', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '客户线索',
                'verbose_name_plural': '客户线索',
                'db_table': 'customer_lead',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['plan_date', 'status'], name='customer_vi_plan_da_33b14f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['client', 'plan_date'], name='customer_vi_client__4278df_idx'),
        ),
        migrations.AddIndex(
            model_name='visitcheckin',
            index=models.Index(fields=['client', 'checkin_time'], name='customer_vi_client__042b18_idx'),
        ),
        migrations.AddIndex(
            model_name='visitcheckin',
            index=models.Index(fields=['checkin_time'], name='customer_vi_checkin_113b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['sales_person', 'start_time'], name='sales_activ_sales_p_9c0087_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['activity_type', 'start_time'], name='sales_activ_activit_4d7c41_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['is_completed', 'start_time'], name='sales_activ_is_comp_d6ac03_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['client', 'relationship_date'], name='customer_re_client__b399b1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerlead',
            index=models.Index(fields=['follow_status', 'responsible_user'], name='customer_le_follow__fe34e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerlead',
            index=models.Index(fields=['lead_source', 'created_time'], name='customer_le_lead_so_4a754a_idx'),
        ),
    ]
