# Generated by Django 4.2.7 on 2025-11-06 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='客户简称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('client_level', models.CharField(choices=[('vip', 'VIP客户'), ('important', '重要客户'), ('general', '一般客户'), ('potential', '潜在客户')], default='general', max_length=20, verbose_name='客户等级')),
                ('credit_level', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('normal', '一般'), ('poor', '较差'), ('bad', '很差')], default='normal', max_length=20, verbose_name='信用等级')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='网站')),
                ('total_contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计合同金额')),
                ('total_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计回款金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('health_score', models.IntegerField(default=0, verbose_name='健康度评分')),
                ('description', models.TextField(blank=True, verbose_name='客户描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer_client',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要联系人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户联系人',
                'verbose_name_plural': '客户联系人',
                'db_table': 'customer_contact',
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(max_length=20, verbose_name='项目状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management.client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户项目',
                'verbose_name_plural': '客户项目',
                'db_table': 'customer_client_project',
            },
        ),
    ]
