# Generated by Django 4.2.7 on 2025-11-06 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('production_management', '0001_initial'),  # 注释掉，因为production_management迁移尚未创建
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_management.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer_management.client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
