# Generated by Django 4.2.7 on 2025-11-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('production_management', '0001_initial'),  # 注释掉，因为production_management迁移尚未创建
        ('customer_management', '0004_copy_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1, help_text='1=商务经理, 2=部门经理, 3=总经理', verbose_name='审核层级')),
                ('result', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('pending', '待审核')], default='pending', max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合同审核记录',
                'verbose_name_plural': '合同审核记录',
                'db_table': 'business_contract_approval',
                'ordering': ['approval_level', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('amount', '金额变更'), ('period', '期限变更'), ('terms', '条款变更'), ('party', '双方变更'), ('other', '其他变更')], max_length=20, verbose_name='变更类型')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('before_content', models.TextField(blank=True, verbose_name='变更前内容')),
                ('after_content', models.TextField(verbose_name='变更后内容')),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, help_text='金额变更时填写', max_digits=12, null=True, verbose_name='变更金额')),
                ('change_date', models.DateField(default=django.utils.timezone.now, verbose_name='变更日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合同变更记录',
                'verbose_name_plural': '合同变更记录',
                'db_table': 'business_contract_change',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('original', '合同原件'), ('scanned', '合同扫描件'), ('attachment', '合同附件'), ('supplement', '补充协议'), ('change', '变更协议'), ('termination', '终止协议'), ('other', '其他文件')], default='scanned', max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='文件')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '合同文件',
                'verbose_name_plural': '合同文件',
                'db_table': 'business_contract_file',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='businesscontract',
            options={'ordering': ['-created_time'], 'verbose_name': '商务合同', 'verbose_name_plural': '商务合同'},
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='attachment',
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='合同审批人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customer_management.client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（含税）'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_amount_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（不含税）'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_amount_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同税额'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_name',
            field=models.CharField(blank=True, help_text='如未填写，将使用合同编号', max_length=200, verbose_name='合同名称'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_period',
            field=models.IntegerField(blank=True, help_text='自动计算：结束日期-开始日期', null=True, verbose_name='合同期限（天）'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='contract_type',
            field=models.CharField(choices=[('framework', '框架合同'), ('project', '项目合同'), ('supplement', '补充协议'), ('change', '变更协议'), ('termination', '终止协议'), ('other', '其他')], default='project', max_length=20, verbose_name='合同类型'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='description',
            field=models.TextField(blank=True, verbose_name='合同描述'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同生效日期'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同结束日期'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, help_text='用于补充协议、变更协议关联主合同', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contracts', to='customer_management.businesscontract', verbose_name='主合同'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_a_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='甲方联系人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_a_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='甲方名称'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_b_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='乙方联系人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='party_b_name',
            field=models.CharField(blank=True, default='四川维海科技有限公司', max_length=200, verbose_name='乙方名称'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已回款金额'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已结算金额'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='合同签订人'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同开始日期'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewing', '审核中'), ('signed', '已签订'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='合同状态'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='默认6%，可调整', max_digits=5, verbose_name='税率(%)'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='unpaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='自动计算：合同金额-已回款金额', max_digits=12, null=True, verbose_name='未回款金额'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同签订日期'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_number',
            field=models.CharField(help_text='唯一标识，建议格式：VIH-CON-YYYY-NNNN', max_length=100, unique=True, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['contract_number'], name='business_co_contrac_e8523a_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['status', 'contract_type'], name='business_co_status_a1c505_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['contract_date'], name='business_co_contrac_dcd013_idx'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_changes', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='customer_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='contractchange',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_changes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='customer_management.businesscontract', verbose_name='合同'),
        ),
    ]
