# Generated by Django 4.2.7 on 2025-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_contractapproval_contractchange_contractfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_number',
            field=models.CharField(blank=True, help_text='唯一标识，留空将自动生成（格式：VIH-CON-YYYY-NNNN）', max_length=100, null=True, unique=True, verbose_name='合同编号'),
        ),
    ]
