# Generated by Django 4.2.7 on 2025-11-17 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0006_alter_businesscontract_contract_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewing', '审核中'), ('signed', '已签订'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewing', '审核中'), ('signed', '已签订'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], max_length=20, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_status_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='customer_management.businesscontract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同状态流转日志',
                'verbose_name_plural': '合同状态流转日志',
                'db_table': 'business_contract_status_log',
                'ordering': ['-created_time'],
            },
        ),
    ]
