# Generated by Django 4.2.7 on 2025-11-23 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0007_contractstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.CharField(blank=True, help_text='自动生成：OPP-YYYY-NNNN', max_length=50, null=True, unique=True, verbose_name='商机编号')),
                ('name', models.CharField(max_length=200, verbose_name='商机名称')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='项目名称')),
                ('project_address', models.CharField(blank=True, max_length=500, verbose_name='项目地址')),
                ('project_type', models.CharField(blank=True, help_text='住宅/综合体/商业/写字楼等', max_length=50, verbose_name='项目业态')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='建筑面积（平方米）')),
                ('drawing_stage', models.CharField(blank=True, max_length=50, verbose_name='图纸阶段')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='预计金额（万元）')),
                ('success_probability', models.IntegerField(default=10, help_text='10/30/50/70/90', verbose_name='成功概率（%）')),
                ('weighted_amount', models.DecimalField(decimal_places=2, default=0, help_text='预计金额 × 成功概率', max_digits=15, verbose_name='加权金额')),
                ('status', models.CharField(choices=[('potential', '潜在客户'), ('initial_contact', '初步接触'), ('requirement_confirmed', '需求确认'), ('quotation', '方案报价'), ('negotiation', '商务谈判'), ('won', '赢单'), ('lost', '输单'), ('cancelled', '已取消')], default='potential', max_length=30, verbose_name='商机状态')),
                ('urgency', models.CharField(choices=[('normal', '普通'), ('urgent', '紧急'), ('very_urgent', '特急')], default='normal', max_length=20, verbose_name='紧急程度')),
                ('expected_sign_date', models.DateField(blank=True, null=True, verbose_name='预计签约时间')),
                ('actual_sign_date', models.DateField(blank=True, null=True, verbose_name='实际签约日期')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实际签约金额（万元）')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('win_reason', models.TextField(blank=True, verbose_name='赢单原因')),
                ('loss_reason', models.TextField(blank=True, verbose_name='输单原因')),
                ('health_score', models.IntegerField(default=0, help_text='0-100分', verbose_name='健康度评分')),
                ('description', models.TextField(blank=True, verbose_name='商机描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('business_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='负责商务')),
            ],
            options={
                'verbose_name': '商机',
                'verbose_name_plural': '商机',
                'db_table': 'business_opportunity',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('developer', '开发商'), ('government', '政府单位'), ('design_institute', '设计院'), ('general_contractor', '总包单位'), ('other', '其他')], max_length=20, verbose_name='客户类型'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_scale',
            field=models.CharField(blank=True, choices=[('large', '大型'), ('medium', '中型'), ('small', '小型')], max_length=20, verbose_name='企业规模'),
        ),
        migrations.AddField(
            model_name='client',
            name='grade',
            field=models.CharField(blank=True, choices=[('strategic', '战略客户'), ('core', '核心客户'), ('potential', '潜力客户'), ('regular', '常规客户'), ('nurturing', '培育客户'), ('observing', '观察客户')], help_text='用于商机管理的客户分级', max_length=20, null=True, verbose_name='客户分级'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='client',
            name='score',
            field=models.IntegerField(default=0, help_text='0-100分，用于自动计算客户分级', verbose_name='客户评分'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('self_development', '自主开发'), ('customer_referral', '老客户推荐'), ('industry_exhibition', '行业展会'), ('online_promotion', '网络推广'), ('other', '其他')], max_length=20, verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='client',
            name='unified_credit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='统一信用代码'),
        ),
        migrations.CreateModel(
            name='QuotationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('rate', '费率'), ('unit_price', '单价'), ('fixed', '固定金额')], max_length=20, verbose_name='规则类型')),
                ('project_type', models.CharField(blank=True, max_length=50, verbose_name='项目业态')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='服务类型')),
                ('structure_type', models.CharField(blank=True, max_length=50, verbose_name='结构形式')),
                ('rule_params', models.JSONField(default=dict, help_text='存储费率、单价等参数', verbose_name='规则参数')),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最小面积')),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最大面积')),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='调整系数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='规则说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotation_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报价规则',
                'verbose_name_plural': '报价规则',
                'db_table': 'business_quotation_rule',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('potential', '潜在客户'), ('initial_contact', '初步接触'), ('requirement_confirmed', '需求确认'), ('quotation', '方案报价'), ('negotiation', '商务谈判'), ('won', '赢单'), ('lost', '输单'), ('cancelled', '已取消')], max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('potential', '潜在客户'), ('initial_contact', '初步接触'), ('requirement_confirmed', '需求确认'), ('quotation', '方案报价'), ('negotiation', '商务谈判'), ('won', '赢单'), ('lost', '输单'), ('cancelled', '已取消')], max_length=30, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_status_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='customer_management.businessopportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机状态流转日志',
                'verbose_name_plural': '商机状态流转日志',
                'db_table': 'business_opportunity_status_log',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateField(verbose_name='跟进日期')),
                ('follow_type', models.CharField(choices=[('phone', '电话沟通'), ('visit', '上门拜访'), ('online_meeting', '线上会议'), ('email', '邮件沟通'), ('other', '其他')], default='phone', max_length=20, verbose_name='跟进方式')),
                ('participants', models.CharField(blank=True, max_length=500, verbose_name='参与人员')),
                ('content', models.TextField(verbose_name='跟进内容')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('next_plan', models.TextField(blank=True, verbose_name='下一步计划')),
                ('next_follow_date', models.DateField(blank=True, null=True, verbose_name='预计下次跟进')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_followups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customer_management.businessopportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机跟进记录',
                'verbose_name_plural': '商机跟进记录',
                'db_table': 'business_opportunity_followup',
                'ordering': ['-follow_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1, help_text='1=商务部经理, 2=商务总监, 3=总经理', verbose_name='审核层级')),
                ('result', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('pending', '待审核')], default='pending', max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='customer_management.businessopportunity', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机审批记录',
                'verbose_name_plural': '商机审批记录',
                'db_table': 'business_opportunity_approval',
                'ordering': ['approval_level', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='customer_management.client', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='OpportunityQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('draft', '初稿报价'), ('customer', '客户报价'), ('final', '最终报价')], default='draft', max_length=20, verbose_name='版本类型')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='建筑面积（平方米）')),
                ('project_type', models.CharField(blank=True, max_length=50, verbose_name='项目业态')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='服务类型')),
                ('structure_type', models.CharField(blank=True, max_length=50, verbose_name='结构形式')),
                ('base_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='基准报价（万元）')),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='调整系数')),
                ('final_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最终报价（万元）')),
                ('quotation_note', models.TextField(blank=True, verbose_name='报价说明')),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/', verbose_name='报价文件')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customer_management.businessopportunity', verbose_name='商机')),
                ('quotation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_management.quotationrule', verbose_name='使用的报价规则')),
            ],
            options={
                'verbose_name': '商机报价',
                'verbose_name_plural': '商机报价',
                'db_table': 'business_opportunity_quotation',
                'ordering': ['-version_number', '-created_time'],
                'unique_together': {('opportunity', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['opportunity_number'], name='business_op_opportu_247937_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['status'], name='business_op_status_97cb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['business_manager', 'status'], name='business_op_busines_690fca_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunity',
            index=models.Index(fields=['expected_sign_date'], name='business_op_expecte_ffe177_idx'),
        ),
    ]
