# Generated by Django 4.2.7 on 2025-11-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0012_add_quotation_mode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blacklist_details',
            field=models.TextField(blank=True, verbose_name='失信详情'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_blacklist',
            field=models.BooleanField(default=False, verbose_name='是否在失信名单'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_litigation',
            field=models.BooleanField(default=False, verbose_name='是否存在诉讼'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_risk_level',
            field=models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='法律风险等级'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_risk_notes',
            field=models.TextField(blank=True, help_text='记录法律风险相关情况', verbose_name='法律风险说明'),
        ),
        migrations.AddField(
            model_name='client',
            name='litigation_details',
            field=models.TextField(blank=True, verbose_name='诉讼详情'),
        ),
    ]
