# Generated by Django 4.2.7 on 2025-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0012_add_quotation_mode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consumption_limit_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='限制高消费数量'),
        ),
        migrations.AddField(
            model_name='client',
            name='executed_person_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='被执行人数量'),
        ),
        migrations.AddField(
            model_name='client',
            name='final_case_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='终本案件数量'),
        ),
        migrations.AddField(
            model_name='client',
            name='litigation_count',
            field=models.IntegerField(default=0, help_text='从启信宝API获取', verbose_name='司法案件数量'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_risk_level',
            field=models.CharField(choices=[('low', '低风险'), ('medium_low', '中低风险'), ('medium', '中风险'), ('medium_high', '中高风险'), ('high', '高风险'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='法律风险等级'),
        ),
    ]
