# Generated by Django 4.2.7 on 2025-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0012_add_quotation_mode_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='职务'),
        ),
    ]
