# Generated by Django 4.2.7 on 2025-11-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0009_add_legal_risk_fields'),
        ('customer_management', '0010_client_consumption_limit_count_and_more'),
        ('customer_management', '0011_remove_client_address_remove_client_email_and_more'),
        ('customer_management', '0013_add_qixinbao_fields_remove_short_name'),
    ]

    operations = [
    ]
