# Generated by Django 4.2.7 on 2025-11-26 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0014_merge_20251126_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='blacklist_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_group',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_scale',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_blacklist',
        ),
        migrations.RemoveField(
            model_name='client',
            name='has_litigation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='legal_risk_notes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='litigation_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_risk_level',
            field=models.CharField(choices=[('low', '低风险'), ('medium_low', '中低风险'), ('medium', '中风险'), ('medium_high', '中高风险'), ('high', '高风险'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='法律风险等级'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='adjustment_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='旧版报价字段，保留兼容性', max_digits=5, verbose_name='调整系数'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='base_quotation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='旧版报价字段，保留兼容性', max_digits=15, verbose_name='基准报价（万元）'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='final_quotation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='最终报价金额（兼容旧版：base_quotation × adjustment_factor；新版：service_fee）', max_digits=15, verbose_name='最终报价（万元）'),
        ),
        migrations.AlterField(
            model_name='opportunityquotation',
            name='quotation_rule',
            field=models.ForeignKey(blank=True, help_text='旧版报价规则，保留兼容性', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_management.quotationrule', verbose_name='使用的报价规则'),
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateTimeField(verbose_name='计划日期')),
                ('plan_title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('plan_purpose', models.TextField(verbose_name='拜访目的')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='拜访地点')),
                ('participants', models.CharField(blank=True, max_length=500, verbose_name='参与人员')),
                ('status', models.CharField(choices=[('planned', '已计划'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='计划状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visit_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_plans', to='customer_management.businessopportunity', verbose_name='关联商机')),
            ],
            options={
                'verbose_name': '拜访计划',
                'verbose_name_plural': '拜访计划',
                'db_table': 'customer_visit_plan',
                'ordering': ['plan_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(verbose_name='签到时间')),
                ('checkin_location', models.CharField(max_length=200, verbose_name='签到地点')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_checkins', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkins', to=settings.AUTH_USER_MODEL, verbose_name='签到人')),
                ('visit_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='customer_management.visitplan', verbose_name='关联拜访计划')),
            ],
            options={
                'verbose_name': '拜访签到',
                'verbose_name_plural': '拜访签到',
                'db_table': 'customer_visit_checkin',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('visit', '客户拜访'), ('phone', '电话沟通'), ('meeting', '会议'), ('email', '邮件沟通'), ('other', '其他')], max_length=20, verbose_name='活动类型')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='活动地点')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customer_management.client', verbose_name='关联客户')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customer_management.businessopportunity', verbose_name='关联商机')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_activities', to=settings.AUTH_USER_MODEL, verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '销售活动',
                'verbose_name_plural': '销售活动',
                'db_table': 'sales_activity',
                'ordering': ['start_time', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('visit', '客户拜访'), ('phone', '电话沟通'), ('meeting', '会议'), ('email', '邮件沟通'), ('wechat', '微信沟通'), ('other', '其他')], max_length=20, verbose_name='关系类型')),
                ('title', models.CharField(max_length=200, verbose_name='关系标题')),
                ('content', models.TextField(verbose_name='关系内容')),
                ('relationship_date', models.DateTimeField(verbose_name='关系日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('participants', models.CharField(blank=True, max_length=500, verbose_name='参与人员')),
                ('next_action', models.TextField(blank=True, verbose_name='下一步行动')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='下次行动日期')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_relationships', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='customer_management.businessopportunity', verbose_name='关联商机')),
            ],
            options={
                'verbose_name': '客户关系',
                'verbose_name_plural': '客户关系',
                'db_table': 'customer_relationship',
                'ordering': ['-relationship_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, verbose_name='联系邮箱')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区县')),
                ('lead_source', models.CharField(choices=[('rcc_platform', 'RCC平台信息'), ('website', '官网咨询'), ('phone', '电话咨询'), ('exhibition', '展会'), ('referral', '转介绍'), ('other', '其他')], default='other', max_length=50, verbose_name='线索来源')),
                ('channel', models.CharField(blank=True, max_length=50, verbose_name='渠道')),
                ('follow_status', models.CharField(choices=[('unhandled', '未处理'), ('contact_valid', '联系方式有效'), ('contact_invalid', '联系方式无效'), ('converted', '已转化'), ('lost', '已流失')], default='unhandled', max_length=20, verbose_name='跟进状态')),
                ('latest_followup_note', models.TextField(blank=True, verbose_name='最新跟进记录')),
                ('actual_followup_time', models.DateTimeField(blank=True, null=True, verbose_name='实际跟进时间')),
                ('days_not_followed', models.IntegerField(default=0, verbose_name='未跟进天数')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('is_friend_added', models.BooleanField(default=False, verbose_name='是否已加好友')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customer_management.client', verbose_name='转化客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_leads', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '客户线索',
                'verbose_name_plural': '客户线索',
                'db_table': 'customer_lead',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['plan_date', 'status'], name='customer_vi_plan_da_33b14f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['client', 'plan_date'], name='customer_vi_client__4278df_idx'),
        ),
        migrations.AddIndex(
            model_name='visitcheckin',
            index=models.Index(fields=['client', 'checkin_time'], name='customer_vi_client__042b18_idx'),
        ),
        migrations.AddIndex(
            model_name='visitcheckin',
            index=models.Index(fields=['checkin_time'], name='customer_vi_checkin_113b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['sales_person', 'start_time'], name='sales_activ_sales_p_9c0087_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['activity_type', 'start_time'], name='sales_activ_activit_4d7c41_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['is_completed', 'start_time'], name='sales_activ_is_comp_d6ac03_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['client', 'relationship_date'], name='customer_re_client__b399b1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerlead',
            index=models.Index(fields=['follow_status', 'responsible_user'], name='customer_le_follow__fe34e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerlead',
            index=models.Index(fields=['lead_source', 'created_time'], name='customer_le_lead_so_4a754a_idx'),
        ),
    ]
