# Generated by Django 4.2.7 on 2025-11-30 10:11

from django.db import migrations


def update_project_foreign_key(apps, schema_editor):
    """更新ClientProject的外键约束，从project_center_project改为production_management_project"""
    db_alias = schema_editor.connection.alias
    
    # 删除旧的外键约束
    with schema_editor.connection.cursor() as cursor:
        # 检查production_management_project表是否存在
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'production_management_project'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            # 删除旧的外键约束
            cursor.execute("""
                ALTER TABLE customer_client_project 
                DROP CONSTRAINT IF EXISTS customer_client_proj_project_id_62ba17de_fk_project_c;
            """)
            
            # 添加新的外键约束
            cursor.execute("""
                ALTER TABLE customer_client_project 
                ADD CONSTRAINT customer_client_proj_project_id_62ba17de_fk_production_management_project_id 
                FOREIGN KEY (project_id) 
                REFERENCES production_management_project(id) 
                DEFERRABLE INITIALLY DEFERRED;
            """)


def reverse_update_project_foreign_key(apps, schema_editor):
    """回滚操作：恢复旧的外键约束"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # 检查project_center_project表是否存在
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'project_center_project'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            # 删除新的外键约束
            cursor.execute("""
                ALTER TABLE customer_client_project 
                DROP CONSTRAINT IF EXISTS customer_client_proj_project_id_62ba17de_fk_production_management_project_id;
            """)
            
            # 恢复旧的外键约束
            cursor.execute("""
                ALTER TABLE customer_client_project 
                ADD CONSTRAINT customer_client_proj_project_id_62ba17de_fk_project_c 
                FOREIGN KEY (project_id) 
                REFERENCES project_center_project(id) 
                DEFERRABLE INITIALLY DEFERRED;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial_squashed_0015_remove_client_blacklist_details_remove_client_code_and_more'),
        # 注意：这里不直接依赖production_management，而是通过RunPython来检查表是否存在
    ]

    operations = [
        migrations.RunPython(
            update_project_foreign_key,
            reverse_update_project_foreign_key,
        ),
    ]
