# Generated by Django 4.2.7 on 2025-12-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0016_update_project_reference'),
    ]

    operations = [
    ]
