# Generated by Django 4.2.7 on 2025-12-01 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permission_management', '0001_initial'),  # 添加permission_management依赖
        ('workflow_engine', '0002_alter_approvalinstance_content_type_and_more'),
        ('production_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0017_auto_20251201_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_number', models.CharField(blank=True, help_text='系统自动生成或手动输入', max_length=100, verbose_name='投标编号')),
                ('bidding_date', models.DateField(verbose_name='投标日期')),
                ('submission_deadline', models.DateField(verbose_name='提交截止日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('preparing', '准备中'), ('submitted', '已提交'), ('won', '中标'), ('lost', '未中标'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('tender_requirements', models.TextField(help_text='根据招标文件填写的要求', verbose_name='招标要求')),
                ('technical_proposal', models.JSONField(blank=True, default=dict, help_text='技术方案、技术能力、技术团队等信息', verbose_name='技术标信息')),
                ('commercial_proposal', models.JSONField(blank=True, default=dict, help_text='报价、付款方式、服务承诺等商务信息', verbose_name='商务标信息')),
                ('personnel_certificates', models.JSONField(blank=True, default=list, help_text='JSON格式存储选中的员工证书信息', verbose_name='人员证书')),
                ('company_certificates', models.JSONField(blank=True, default=list, help_text='JSON格式存储公司资质证书、营业执照等信息', verbose_name='公司证件')),
                ('bidding_documents', models.JSONField(blank=True, default=list, help_text='JSON格式存储上传的投标文件列表', verbose_name='投标文件')),
                ('notes', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投标报价记录',
                'verbose_name_plural': '投标报价记录',
                'db_table': 'business_bidding_quotation',
                'ordering': ['-bidding_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='BusinessNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiation_date', models.DateField(verbose_name='洽谈日期')),
                ('negotiation_type', models.CharField(choices=[('phone', '电话沟通'), ('meeting', '会议洽谈'), ('visit', '上门拜访'), ('email', '邮件沟通'), ('online', '线上会议'), ('other', '其他')], max_length=20, verbose_name='洽谈类型')),
                ('participants', models.CharField(blank=True, help_text='参与洽谈的人员，多个用逗号分隔', max_length=500, verbose_name='参与人员')),
                ('content', models.TextField(verbose_name='洽谈内容')),
                ('client_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('next_plan', models.TextField(blank=True, verbose_name='下一步计划')),
                ('discussed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='讨论金额（万元）')),
                ('payment_terms', models.TextField(blank=True, verbose_name='付款条件')),
                ('contract_terms', models.TextField(blank=True, verbose_name='合同条款')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商务洽谈记录',
                'verbose_name_plural': '商务洽谈记录',
                'db_table': 'business_negotiation',
                'ordering': ['-negotiation_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ContactCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperation_type', models.CharField(choices=[('project', '项目合作'), ('consulting', '咨询服务'), ('support', '技术支持'), ('training', '培训服务'), ('other', '其他')], max_length=20, verbose_name='合作类型')),
                ('cooperation_start_date', models.DateField(verbose_name='合作开始时间')),
                ('cooperation_end_date', models.DateField(blank=True, null=True, verbose_name='合作结束时间')),
                ('cooperation_status', models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('terminated', '已终止')], default='ongoing', max_length=20, verbose_name='合作状态')),
                ('cooperation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='合作金额（万元）')),
                ('cooperation_description', models.TextField(blank=True, verbose_name='合作描述')),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='0-100分', null=True, verbose_name='满意度评分')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员合作信息记录',
                'verbose_name_plural': '人员合作信息记录',
                'db_table': 'customer_contact_cooperation',
                'ordering': ['-cooperation_start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('high_school', '高中'), ('college', '专科'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], max_length=20, verbose_name='学历')),
                ('school_name', models.CharField(max_length=200, verbose_name='学校名称')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('enrollment_date', models.DateField(verbose_name='入学时间')),
                ('graduation_date', models.DateField(verbose_name='毕业时间')),
                ('is_full_time', models.BooleanField(default=True, verbose_name='是否全日制')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户人员教育背景',
                'verbose_name_plural': '客户人员教育背景',
                'db_table': 'customer_contact_education',
                'ordering': ['-graduation_date', '-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactJobChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('join', '入职'), ('leave', '离职'), ('transfer', '调岗'), ('promotion', '升职'), ('demotion', '降职')], max_length=20, verbose_name='变动类型')),
                ('from_company', models.CharField(blank=True, max_length=200, verbose_name='原公司')),
                ('to_company', models.CharField(max_length=200, verbose_name='新公司')),
                ('from_position', models.CharField(blank=True, max_length=100, verbose_name='原职位')),
                ('to_position', models.CharField(max_length=100, verbose_name='新职位')),
                ('from_department', models.CharField(blank=True, max_length=100, verbose_name='原部门')),
                ('to_department', models.CharField(blank=True, max_length=100, verbose_name='新部门')),
                ('change_date', models.DateField(verbose_name='变动时间')),
                ('change_reason', models.CharField(blank=True, max_length=500, verbose_name='变动原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员工作变动记录',
                'verbose_name_plural': '人员工作变动记录',
                'db_table': 'customer_contact_job_change',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_type', models.CharField(choices=[('phone', '电话跟踪'), ('email', '邮件跟踪'), ('wechat', '微信跟踪'), ('face_to_face', '面谈跟踪'), ('meeting', '会议跟踪'), ('other', '其他')], max_length=20, verbose_name='跟踪类型')),
                ('tracking_date', models.DateTimeField(verbose_name='跟踪时间')),
                ('tracking_content', models.TextField(verbose_name='跟踪内容')),
                ('tracking_result', models.CharField(choices=[('success', '成功'), ('followup', '待跟进'), ('failed', '失败'), ('other', '其他')], default='followup', max_length=20, verbose_name='跟踪结果')),
                ('next_tracking_date', models.DateField(blank=True, null=True, verbose_name='下次跟踪时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员跟踪信息记录',
                'verbose_name_plural': '人员跟踪信息记录',
                'db_table': 'customer_contact_tracking',
                'ordering': ['-tracking_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('start_date', models.DateField(verbose_name='入职时间')),
                ('end_date', models.DateField(blank=True, help_text='为空表示至今', null=True, verbose_name='离职时间')),
                ('office_address', models.CharField(blank=True, max_length=500, verbose_name='办公地址')),
                ('job_description', models.TextField(blank=True, verbose_name='工作内容')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户人员工作经历',
                'verbose_name_plural': '客户人员工作经历',
                'db_table': 'customer_contact_work_experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationshipUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(choices=[('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], max_length=30, verbose_name='原关系等级')),
                ('to_level', models.CharField(choices=[('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], max_length=30, verbose_name='目标关系等级')),
                ('upgrade_reason', models.TextField(verbose_name='升级原因')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', help_text='如果升级到"合作意向"、"合作认可"或"外部合伙人"需要审批', max_length=20, verbose_name='审批状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
            ],
            options={
                'verbose_name': '客户关系升级记录',
                'verbose_name_plural': '客户关系升级记录',
                'db_table': 'customer_relationship_upgrade',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(verbose_name='备案日期')),
                ('filing_type', models.CharField(choices=[('initial', '初始备案'), ('update', '更新备案'), ('supplement', '补充备案'), ('other', '其他')], max_length=20, verbose_name='备案类型')),
                ('filing_number', models.CharField(blank=True, help_text='系统自动生成或手动输入', max_length=100, verbose_name='备案编号')),
                ('filing_content', models.TextField(verbose_name='备案内容')),
                ('filing_purpose', models.TextField(blank=True, verbose_name='备案目的')),
                ('filing_notes', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商机备案记录',
                'verbose_name_plural': '商机备案记录',
                'db_table': 'business_opportunity_filing',
                'ordering': ['-filing_date', '-created_time'],
            },
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='parent_contract',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='businesspaymentplan',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='customerlead',
            name='converted_client',
        ),
        migrations.RemoveField(
            model_name='customerlead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerlead',
            name='responsible_user',
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'ordering': ['-is_primary', '-created_time'], 'verbose_name': '客户联系人', 'verbose_name_plural': '客户联系人'},
        ),
        migrations.AlterModelOptions(
            name='customerrelationship',
            options={'ordering': ['-followup_time', '-created_time'], 'verbose_name': '客户关系记录', 'verbose_name_plural': '客户关系记录'},
        ),
        migrations.RemoveIndex(
            model_name='customerrelationship',
            name='customer_re_client__b399b1_idx',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='next_action',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='next_action_date',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='related_opportunity',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='relationship_date',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='relationship_type',
        ),
        migrations.RemoveField(
            model_name='customerrelationship',
            name='title',
        ),
        migrations.AddField(
            model_name='client',
            name='public_sea_entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='进入公海时间'),
        ),
        migrations.AddField(
            model_name='client',
            name='public_sea_reason',
            field=models.CharField(blank=True, choices=[('unassigned', '未分配'), ('released', '已释放'), ('auto_entry', '自动进入')], max_length=20, verbose_name='进入公海原因'),
        ),
        migrations.AddField(
            model_name='client',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='为空表示在公海', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_clients', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='best_contact_time',
            field=models.CharField(blank=True, help_text='如：工作日9-11点', max_length=200, verbose_name='最佳联系时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='contact_frequency',
            field=models.CharField(blank=True, choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '每季度'), ('occasionally', '偶尔'), ('never', '从未')], max_length=20, verbose_name='联系频率'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='decision_influence',
            field=models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='决策影响力'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='first_contact_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次接触时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='focus_areas',
            field=models.TextField(blank=True, help_text='如：技术、管理、市场等', verbose_name='关注领域'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='home_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='居住地址'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='interests',
            field=models.TextField(blank=True, verbose_name='个人兴趣爱好'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='last_contact_time',
            field=models.DateTimeField(blank=True, help_text='自动更新', null=True, verbose_name='最后联系时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='office_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='办公地址'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='position_level',
            field=models.CharField(blank=True, choices=[('employee', '普通员工'), ('supervisor', '主管'), ('manager', '经理'), ('director', '总监'), ('vp', '副总'), ('ceo', '总经理')], max_length=20, verbose_name='职位级别'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='preferred_contact_methods',
            field=models.JSONField(blank=True, default=list, help_text='多选：phone、email、wechat、face_to_face、other', verbose_name='偏好沟通方式'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='relationship_level',
            field=models.CharField(choices=[('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], default='requirement_communication', max_length=30, verbose_name='关系等级'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='relationship_score',
            field=models.IntegerField(default=0, help_text='0-100分', verbose_name='关系评分'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='resume_file',
            field=models.FileField(blank=True, help_text='支持格式：PDF、Word、图片；文件大小限制：10MB', null=True, upload_to='contact_resumes/%Y/%m/', verbose_name='简历文件'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='resume_source',
            field=models.CharField(blank=True, choices=[('51job', '51job'), ('zhaopin', '智联招聘'), ('boss', 'BOSS直聘'), ('liepin', '猎聘'), ('other', '其他')], max_length=20, verbose_name='简历来源'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='resume_upload_time',
            field=models.DateTimeField(blank=True, help_text='自动设置', null=True, verbose_name='简历上传时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='role',
            field=models.CharField(blank=True, choices=[('contact_person', '对接人'), ('promoter', '推动人'), ('decision_maker', '决策人')], max_length=20, verbose_name='人员角色'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='多选标签，如：技术专家、决策者、影响者、支持者等', verbose_name='个人标签'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='work_years',
            field=models.IntegerField(blank=True, help_text='自动计算', null=True, verbose_name='工作年限'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='followup_method',
            field=models.CharField(choices=[('phone', '电话'), ('email', '邮件'), ('wechat', '微信'), ('visit', '上门'), ('meeting', '会议'), ('exhibition', '展会'), ('other', '其他')], default='phone', max_length=20, verbose_name='跟进方式'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='followup_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_relationships', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='followup_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='跟进时间'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='record_type',
            field=models.CharField(choices=[('followup', '跟进记录'), ('visit', '拜访记录')], default='followup', max_length=20, verbose_name='记录类型'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='related_contacts',
            field=models.ManyToManyField(blank=True, related_name='relationships', to='customer_management.clientcontact', verbose_name='关联的客户人员'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='relationship_level',
            field=models.CharField(choices=[('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], default='requirement_communication', max_length=30, verbose_name='关系等级'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='办公电话'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='wechat',
            field=models.CharField(blank=True, help_text='可存储多个，用逗号分隔', max_length=200, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customer_management.client', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='contractapproval',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='production_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='contractchange',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='production_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='contractfile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='production_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='contractstatuslog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='production_management.businesscontract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='contractstatuslog',
            name='from_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='原状态'),
        ),
        migrations.AlterField(
            model_name='contractstatuslog',
            name='to_status',
            field=models.CharField(max_length=20, verbose_name='目标状态'),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='content',
            field=models.TextField(verbose_name='跟进/拜访内容'),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_relationships', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterUniqueTogether(
            name='clientproject',
            unique_together={('client', 'project')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='customer_cl_name_fa39ad_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['unified_credit_code'], name='customer_cl_unified_ef90c3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['responsible_user', 'is_active'], name='customer_cl_respons_e74a91_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['public_sea_entry_time'], name='customer_cl_public__13c229_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'role'], name='customer_co_client__8428bc_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['relationship_level'], name='customer_co_relatio_29ec0d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['last_contact_time'], name='customer_co_last_co_d731c3_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['client', 'followup_time'], name='customer_re_client__b7d7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['record_type', 'followup_time'], name='customer_re_record__fa6ce2_idx'),
        ),
        migrations.DeleteModel(
            name='BusinessContract',
        ),
        migrations.DeleteModel(
            name='BusinessPaymentPlan',
        ),
        migrations.DeleteModel(
            name='CustomerLead',
        ),
        migrations.AddField(
            model_name='opportunityfiling',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_filings', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='opportunityfiling',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='customer_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AddField(
            model_name='customerrelationshipupgrade',
            name='approval_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_upgrades', to='workflow_engine.approvalinstance', verbose_name='审批实例'),
        ),
        migrations.AddField(
            model_name='customerrelationshipupgrade',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_upgrades', to='customer_management.client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='customerrelationshipupgrade',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_relationship_upgrades', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='customerrelationshipupgrade',
            name='related_contacts',
            field=models.ManyToManyField(blank=True, related_name='relationship_upgrades', to='customer_management.clientcontact', verbose_name='关联的客户人员'),
        ),
        migrations.AddField(
            model_name='contactworkexperience',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='customer_management.clientcontact', verbose_name='客户人员'),
        ),
        migrations.AddField(
            model_name='contacttracking',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='customer_management.clientcontact', verbose_name='客户人员'),
        ),
        migrations.AddField(
            model_name='contacttracking',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trackings', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contacttracking',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_trackings', to='customer_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AddField(
            model_name='contacttracking',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_trackings', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='contacttracking',
            name='tracking_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_trackings', to=settings.AUTH_USER_MODEL, verbose_name='跟踪人'),
        ),
        migrations.AddField(
            model_name='contactjobchange',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_changes', to='customer_management.clientcontact', verbose_name='客户人员'),
        ),
        migrations.AddField(
            model_name='contactjobchange',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_changes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contactjobchange',
            name='related_client',
            field=models.ForeignKey(blank=True, help_text='如果新公司是我们的客户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_changes', to='customer_management.client', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='contacteducation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='customer_management.clientcontact', verbose_name='客户人员'),
        ),
        migrations.AddField(
            model_name='contactcooperation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperations', to='customer_management.clientcontact', verbose_name='客户人员'),
        ),
        migrations.AddField(
            model_name='contactcooperation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cooperations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contactcooperation',
            name='our_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_cooperations', to=settings.AUTH_USER_MODEL, verbose_name='我方对接人'),
        ),
        migrations.AddField(
            model_name='contactcooperation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_cooperations', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='businessnegotiation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='businessnegotiation',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='customer_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AddField(
            model_name='biddingquotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bidding_quotations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='biddingquotation',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_quotations', to='customer_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AddField(
            model_name='biddingquotation',
            name='similar_projects',
            field=models.ManyToManyField(blank=True, help_text='选择类似的项目作为业绩证明', related_name='bidding_quotations', to='production_management.project', verbose_name='类似业绩'),
        ),
        migrations.AddIndex(
            model_name='customerrelationshipupgrade',
            index=models.Index(fields=['client', 'approval_status'], name='customer_re_client__49d942_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationshipupgrade',
            index=models.Index(fields=['to_level', 'approval_status'], name='customer_re_to_leve_85d7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactworkexperience',
            index=models.Index(fields=['company_name', 'start_date'], name='customer_co_company_29ac1f_idx'),
        ),
        migrations.AddIndex(
            model_name='contacttracking',
            index=models.Index(fields=['contact', 'tracking_date'], name='customer_co_contact_a1d403_idx'),
        ),
        migrations.AddIndex(
            model_name='contacttracking',
            index=models.Index(fields=['next_tracking_date'], name='customer_co_next_tr_f7ce11_idx'),
        ),
    ]
