# Generated by Django 4.2.7 on 2025-12-02 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0018_biddingquotation_businessnegotiation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRelationshipCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('followup', '跟进协作'), ('visit', '拜访协作'), ('activity', '活动协作'), ('service', '服务协作')], max_length=20, verbose_name='任务类型')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='任务进度')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='customer_management.client', verbose_name='客户')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='协作者')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_contacts', models.ManyToManyField(blank=True, related_name='collaborations', to='customer_management.clientcontact', verbose_name='关联的客户人员')),
                ('related_relationships', models.ManyToManyField(blank=True, related_name='collaborations', to='customer_management.customerrelationship', verbose_name='关联的跟进记录')),
                ('responsible_users', models.ManyToManyField(related_name='responsible_collaborations', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '客户关系协作任务',
                'verbose_name_plural': '客户关系协作任务',
                'db_table': 'customer_relationship_collaboration',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationshipCollaborationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('task_type', models.CharField(choices=[('followup', '跟进协作'), ('visit', '拜访协作'), ('activity', '活动协作'), ('service', '服务协作')], max_length=20, verbose_name='任务类型')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('description_template', models.TextField(verbose_name='描述模板')),
                ('default_priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='默认优先级')),
                ('is_shared', models.BooleanField(default=False, verbose_name='是否共享')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '协作任务模板',
                'verbose_name_plural': '协作任务模板',
                'db_table': 'customer_relationship_collaboration_template',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationshipCollaborationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建任务'), ('started', '开始任务'), ('progress_updated', '更新进度'), ('status_changed', '状态变更'), ('commented', '添加评论'), ('attachment_added', '添加附件'), ('completed', '完成任务'), ('cancelled', '取消任务')], max_length=30, verbose_name='执行动作')),
                ('content', models.TextField(blank=True, verbose_name='执行内容')),
                ('execution_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='customer_management.customerrelationshipcollaboration', verbose_name='协作任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '协作任务执行记录',
                'verbose_name_plural': '协作任务执行记录',
                'db_table': 'customer_relationship_collaboration_execution',
                'ordering': ['-execution_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationshipCollaborationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='customer_management.customerrelationshipcollaboration', verbose_name='协作任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '协作任务评论',
                'verbose_name_plural': '协作任务评论',
                'db_table': 'customer_relationship_collaboration_comment',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationshipCollaborationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='collaboration_attachments/%Y/%m/%d/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customer_management.customerrelationshipcollaboration', verbose_name='协作任务')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '协作任务附件',
                'verbose_name_plural': '协作任务附件',
                'db_table': 'customer_relationship_collaboration_attachment',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='DishonestyExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='立案时间')),
                ('case_number', models.CharField(blank=True, max_length=200, verbose_name='案号')),
                ('execution_target', models.CharField(blank=True, max_length=500, verbose_name='执行标的')),
                ('execution_court', models.CharField(blank=True, max_length=200, verbose_name='执行法院')),
                ('behavior_description', models.TextField(blank=True, verbose_name='失信被执行人的行为具体情形')),
                ('source', models.CharField(choices=[('qixinbao', '启信宝API'), ('manual', '手动录入')], default='qixinbao', max_length=50, verbose_name='数据来源')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishonesty_execution_records', to='customer_management.client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '失信被执行记录',
                'verbose_name_plural': '失信被执行记录',
                'db_table': 'customer_dishonesty_execution_record',
                'ordering': ['-filing_date', '-created_time'],
                'indexes': [models.Index(fields=['client', '-filing_date'], name='customer_di_client__434009_idx'), models.Index(fields=['case_number'], name='customer_di_case_nu_b4b2c0_idx')],
            },
        ),
    ]
