-- 0020迁移：将DishonestyExecutionRecord改为ExecutionRecord
-- 执行前请备份数据库！

BEGIN;

-- 1. 在Client表中添加total_execution_amount字段
ALTER TABLE "customer_client" 
ADD COLUMN IF NOT EXISTS "total_execution_amount" numeric(12, 2) DEFAULT 0 NOT NULL;

-- 2. 创建新的ExecutionRecord表
CREATE TABLE IF NOT EXISTS "customer_execution_record" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "case_number" varchar(200) NOT NULL DEFAULT '',
    "execution_status" varchar(50) NOT NULL DEFAULT 'unknown',
    "execution_court" varchar(200) NOT NULL DEFAULT '',
    "filing_date" date NULL,
    "execution_amount" numeric(12, 2) NOT NULL DEFAULT 0,
    "source" varchar(50) NOT NULL DEFAULT 'qixinbao',
    "created_time" timestamp with time zone NOT NULL,
    "updated_time" timestamp with time zone NOT NULL,
    "client_id" bigint NOT NULL
);

-- 3. 创建索引
CREATE INDEX IF NOT EXISTS "customer_ex_client__idx" 
ON "customer_execution_record" ("client_id", "filing_date" DESC);

CREATE INDEX IF NOT EXISTS "customer_ex_case_nu_idx" 
ON "customer_execution_record" ("case_number");

CREATE INDEX IF NOT EXISTS "customer_execution_record_client_id_a6e5fe01" 
ON "customer_execution_record" ("client_id");

-- 4. 添加外键约束
ALTER TABLE "customer_execution_record" 
ADD CONSTRAINT "customer_execution_r_client_id_a6e5fe01_fk_customer_" 
FOREIGN KEY ("client_id") REFERENCES "customer_client" ("id") 
DEFERRABLE INITIALLY DEFERRED;

-- 5. 迁移数据（从旧表到新表）
-- 注意：执行金额从execution_target中提取，如果包含"万"则乘以10000
INSERT INTO "customer_execution_record" 
    (client_id, case_number, execution_status, execution_court, 
     filing_date, execution_amount, source, created_time, updated_time)
SELECT 
    client_id,
    COALESCE(case_number, ''),
    'unknown' as execution_status,
    COALESCE(execution_court, ''),
    filing_date,
    CASE 
        WHEN execution_target ~ '万' THEN 
            COALESCE(
                (regexp_replace(execution_target, '[^0-9.]', '', 'g')::numeric * 10000),
                0
            )
        WHEN execution_target ~ '^[0-9.]+' THEN 
            COALESCE(
                regexp_replace(execution_target, '[^0-9.]', '', 'g')::numeric,
                0
            )
        ELSE 0
    END as execution_amount,
    COALESCE(source, 'qixinbao'),
    COALESCE(created_time, NOW()),
    COALESCE(updated_time, NOW())
FROM "customer_dishonesty_execution_record"
WHERE EXISTS (
    SELECT 1 FROM "customer_client" WHERE "customer_client"."id" = "customer_dishonesty_execution_record"."client_id"
);

-- 6. 更新客户的总执行金额
UPDATE "customer_client" c
SET "total_execution_amount" = COALESCE(
    (SELECT SUM(execution_amount) 
     FROM "customer_execution_record" e 
     WHERE e.client_id = c.id), 
    0
);

-- 7. 删除旧表（谨慎操作！）
-- 如果确认数据迁移成功，可以取消注释下面的行
-- DROP TABLE IF EXISTS "customer_dishonesty_execution_record" CASCADE;

COMMIT;

-- 验证迁移结果
SELECT 
    '旧表记录数' as description,
    COUNT(*) as count
FROM "customer_dishonesty_execution_record"
UNION ALL
SELECT 
    '新表记录数' as description,
    COUNT(*) as count
FROM "customer_execution_record"
UNION ALL
SELECT 
    '有执行记录的客户数' as description,
    COUNT(*) as count
FROM "customer_client"
WHERE "total_execution_amount" > 0;

