# Generated by Django 4.2.7 on 2025-12-02 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0020_change_dishonesty_to_execution_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='就职公司')),
                ('unified_credit_code', models.CharField(blank=True, max_length=18, verbose_name='社会统一信用代码')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '联系人职业信息',
                'verbose_name_plural': '联系人职业信息',
                'db_table': 'customer_contact_career',
                'ordering': ['-join_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='executionrecord',
            new_name='customer_ex_client__50d76a_idx',
            old_name='customer_ex_client__idx',
        ),
        migrations.RenameIndex(
            model_name='executionrecord',
            new_name='customer_ex_case_nu_d5f407_idx',
            old_name='customer_ex_case_nu_idx',
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='approval_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='customerrelationship',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='部门（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='home_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='家庭地址（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职时间（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='office_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='办公地址'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='职位（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='position_level',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='职位级别（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='电话（已废弃）'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='wechat',
            field=models.CharField(blank=True, default='', help_text='可存储多个，用逗号分隔', max_length=200, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='work_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='工作年限（已废弃）'),
        ),
        migrations.AlterField(
            model_name='customerrelationshipcollaboration',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='任务标题'),
        ),
        migrations.AlterField(
            model_name='customerrelationshipcollaborationexecution',
            name='action',
            field=models.CharField(choices=[('created', '创建任务'), ('started', '开始任务'), ('progress_updated', '更新进度'), ('status_changed', '状态变更'), ('commented', '添加评论'), ('attachment_added', '添加附件'), ('attachment_deleted', '删除附件'), ('completed', '完成任务'), ('cancelled', '取消任务')], max_length=30, verbose_name='执行动作'),
        ),
        migrations.AddField(
            model_name='contactcareer',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='customer_management.clientcontact', verbose_name='联系人'),
        ),
        migrations.AddIndex(
            model_name='contactcareer',
            index=models.Index(fields=['contact'], name='customer_co_contact_bc2810_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcareer',
            index=models.Index(fields=['join_date'], name='customer_co_join_da_3856f9_idx'),
        ),
    ]
