# Generated by Django 4.2.7 on 2025-12-03 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0023_update_opportunity_drawing_stage_to_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrelationship',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='定位地址'),
        ),
        migrations.AlterField(
            model_name='businessopportunity',
            name='opportunity_number',
            field=models.CharField(blank=True, help_text='自动生成：SJ-YYYYMMDD-0000', max_length=50, null=True, unique=True, verbose_name='商机编号'),
        ),
        migrations.CreateModel(
            name='CustomerRequirementCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_number', models.CharField(blank=True, help_text='自动生成：XQ-YYYYMMDD-0000', max_length=50, null=True, unique=True, verbose_name='沟通编号')),
                ('title', models.CharField(max_length=200, verbose_name='沟通主题')),
                ('communication_type', models.CharField(choices=[('phone', '电话沟通'), ('meeting', '会议沟通'), ('email', '邮件沟通'), ('site_visit', '现场拜访'), ('online', '线上沟通'), ('other', '其他')], default='meeting', max_length=20, verbose_name='沟通方式')),
                ('communication_date', models.DateTimeField(verbose_name='沟通时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='沟通地点')),
                ('client_participants', models.CharField(blank=True, help_text='多个人员用逗号分隔', max_length=500, verbose_name='客户参与人员')),
                ('requirement_description', models.TextField(verbose_name='需求描述')),
                ('requirement_details', models.TextField(blank=True, verbose_name='需求详情')),
                ('technical_requirements', models.TextField(blank=True, verbose_name='技术要求')),
                ('business_requirements', models.TextField(blank=True, verbose_name='商务要求')),
                ('budget_range', models.CharField(blank=True, max_length=200, verbose_name='预算范围')),
                ('timeline_requirement', models.CharField(blank=True, max_length=200, verbose_name='时间要求')),
                ('communication_result', models.TextField(blank=True, verbose_name='沟通结果')),
                ('next_action', models.TextField(blank=True, verbose_name='下一步行动')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='下次行动时间')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('attachments', models.TextField(blank=True, help_text='附件文件列表，用逗号分隔', verbose_name='附件说明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_communications', to='customer_management.client', verbose_name='关联客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirement_communications', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_communications', to='customer_management.businessopportunity', verbose_name='关联商机')),
                ('our_participants', models.ManyToManyField(blank=True, related_name='requirement_communications_participated', to=settings.AUTH_USER_MODEL, verbose_name='我方参与人员')),
            ],
            options={
                'verbose_name': '客户需求沟通登记',
                'verbose_name_plural': '客户需求沟通登记',
                'db_table': 'customer_requirement_communication',
                'ordering': ['-communication_date', '-created_time'],
                'indexes': [models.Index(fields=['opportunity', '-communication_date'], name='customer_re_opportu_752350_idx'), models.Index(fields=['client', '-communication_date'], name='customer_re_client__9048e9_idx'), models.Index(fields=['status', '-communication_date'], name='customer_re_status_a61b11_idx'), models.Index(fields=['communication_number'], name='customer_re_communi_b97e59_idx')],
            },
        ),
    ]
