# Generated by Django 4.2.7 on 2025-12-03 08:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0027_seed_communication_checklist_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_result', models.TextField(help_text='记录拜访过程中的关键信息和结果', verbose_name='拜访结果')),
                ('customer_feedback', models.TextField(blank=True, help_text='客户的主要反馈和意见', verbose_name='客户反馈')),
                ('key_points', models.TextField(blank=True, help_text='本次拜访的关键要点和收获', verbose_name='关键要点')),
                ('next_actions', models.TextField(blank=True, help_text='后续需要跟进的事项和行动计划', verbose_name='下一步行动')),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='拜访满意度评分（1-10分）', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='满意度评分')),
                ('effectiveness', models.CharField(blank=True, choices=[('excellent', '非常有效'), ('good', '有效'), ('average', '一般'), ('poor', '效果不佳')], max_length=20, verbose_name='拜访效果')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '拜访结果复盘',
                'verbose_name_plural': '拜访结果复盘',
                'db_table': 'customer_visit_review',
                'ordering': ['-created_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='communicationchecklistanswer',
            new_name='communicati_checkli_c54e9d_idx',
            old_name='comm_check_a_checklist_question_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationchecklistquestion',
            new_name='communicati_part_7b6339_idx',
            old_name='comm_check_q_part_order_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationchecklistquestion',
            new_name='communicati_is_acti_39b5cd_idx',
            old_name='comm_check_q_is_active_idx',
        ),
        migrations.AddField(
            model_name='visitplan',
            name='checklist_prepared',
            field=models.BooleanField(default=False, verbose_name='清单已准备'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='checklist_prepared_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='清单准备时间'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='communication_checklist',
            field=models.TextField(blank=True, help_text='拜访前需要准备的沟通要点和材料清单', verbose_name='沟通清单'),
        ),
        migrations.AddField(
            model_name='visitreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visit_reviews', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='visitreview',
            name='visit_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='customer_management.visitcheckin', verbose_name='关联签到'),
        ),
        migrations.AddField(
            model_name='visitreview',
            name='visit_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='customer_management.visitplan', verbose_name='关联拜访计划'),
        ),
    ]
