# Generated by Django 4.2.7 on 2025-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0029_add_visit_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='communication_checklist',
            field=models.TextField(blank=True, help_text='拜访前需要准备的沟通要点和材料清单', verbose_name='沟通清单'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='checklist_prepared',
            field=models.BooleanField(default=False, verbose_name='清单已准备'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='checklist_prepared_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='清单准备时间'),
        ),
    ]
