# Generated by Django 4.2.7 on 2025-12-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0030_add_communication_checklist_fields_to_visit_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercommunicationchecklist',
            name='client',
        ),
        migrations.RemoveField(
            model_name='customercommunicationchecklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customercommunicationchecklist',
            name='opportunity',
        ),
        migrations.DeleteModel(
            name='CommunicationChecklistAnswer',
        ),
        migrations.DeleteModel(
            name='CommunicationChecklistQuestion',
        ),
        migrations.DeleteModel(
            name='CustomerCommunicationChecklist',
        ),
    ]
