# Generated by Django 4.2.7 on 2025-12-07 02:23

import backend.apps.customer_management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0035_initialize_client_type_and_grade_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('service', '服务委托书'), ('procurement', '采购委托书'), ('consulting', '咨询委托书'), ('other', '其他')], default='service', max_length=50, verbose_name='模板类型')),
                ('category', models.CharField(blank=True, help_text='用于模板分类管理', max_length=100, verbose_name='模板分类')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('template_content', models.JSONField(default=dict, help_text='存储委托书各字段的模板值，支持变量占位符', verbose_name='模板内容')),
                ('variables', models.JSONField(default=list, help_text='模板中使用的变量列表，格式：[{"name": "变量名", "label": "显示名称", "description": "说明"}]', verbose_name='变量列表')),
                ('template_file', models.FileField(blank=True, help_text='支持上传Word、PDF等格式的模板文件，用于预览和下载', max_length=500, null=True, upload_to=backend.apps.customer_management.models.authorization_letter_template_file_path, verbose_name='模板文件')),
                ('template_file_name', models.CharField(blank=True, help_text='原始文件名', max_length=255, verbose_name='模板文件名')),
                ('template_file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_time', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务委托书模板',
                'verbose_name_plural': '业务委托书模板',
                'db_table': 'business_authorization_letter_template',
                'ordering': ['-created_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='authorizationletter',
            new_name='business_au_letter__169de4_idx',
            old_name='business_au_letter__idx',
        ),
        migrations.RenameIndex(
            model_name='authorizationletter',
            new_name='business_au_status_470c0f_idx',
            old_name='business_au_status_idx',
        ),
        migrations.RenameIndex(
            model_name='authorizationletter',
            new_name='business_au_client__7527c7_idx',
            old_name='business_au_client__idx',
        ),
        migrations.RenameIndex(
            model_name='authorizationletter',
            new_name='business_au_opportu_66bb64_idx',
            old_name='business_au_opportun_idx',
        ),
        migrations.RenameIndex(
            model_name='authorizationletter',
            new_name='business_au_letter__f16ddb_idx',
            old_name='business_au_letter__idx2',
        ),
        migrations.RenameIndex(
            model_name='clientgrade',
            new_name='customer_cl_code_33f4b9_idx',
            old_name='customer_cl_grade_code_idx',
        ),
        migrations.RenameIndex(
            model_name='clientgrade',
            new_name='customer_cl_is_acti_f0955b_idx',
            old_name='customer_cl_grade_active_idx',
        ),
        migrations.RenameIndex(
            model_name='clienttype',
            new_name='customer_cl_code_a7a43d_idx',
            old_name='customer_cl_type_code_idx',
        ),
        migrations.RenameIndex(
            model_name='clienttype',
            new_name='customer_cl_is_acti_6254a6_idx',
            old_name='customer_cl_type_active_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='customer_management.clienttype', verbose_name='客户类型'),
        ),
        migrations.AddField(
            model_name='authorizationlettertemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_authorization_letter_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='authorizationlettertemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_authorization_letter_templates', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddIndex(
            model_name='authorizationlettertemplate',
            index=models.Index(fields=['template_type', 'status'], name='business_au_templat_6db411_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationlettertemplate',
            index=models.Index(fields=['status'], name='business_au_status_4cd460_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationlettertemplate',
            index=models.Index(fields=['created_time'], name='business_au_created_fc9c6c_idx'),
        ),
    ]
