# Generated by Django 4.2.7 on 2025-12-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0047_add_contract_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessexpenseapplicationrelatedcontacts',
            name='businessexpenseapplication',
        ),
        migrations.RemoveField(
            model_name='businessexpenseapplicationrelatedcontacts',
            name='clientcontact',
        ),
        migrations.RenameIndex(
            model_name='businessexpenseapplication',
            new_name='customer_bu_client__d1bcbd_idx',
            old_name='customer_bu_client__idx',
        ),
        migrations.RenameIndex(
            model_name='businessexpenseapplication',
            new_name='customer_bu_expense_46442d_idx',
            old_name='customer_bu_expense__idx',
        ),
        migrations.RenameIndex(
            model_name='businessexpenseapplication',
            new_name='customer_bu_applica_2bd12b_idx',
            old_name='customer_bu_applica_idx',
        ),
        migrations.RenameIndex(
            model_name='contactcolleague',
            new_name='customer_co_career__1a2214_idx',
            old_name='customer_co_career_idx',
        ),
        migrations.RenameIndex(
            model_name='contactinfochange',
            new_name='customer_co_contact_90f098_idx',
            old_name='customer_co_contact_6a8f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='contactinfochange',
            new_name='customer_co_change__1bbcdf_idx',
            old_name='customer_co_change__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='contactinfochange',
            new_name='customer_co_created_889dea_idx',
            old_name='customer_co_created_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='contractnegotiation',
            new_name='business_co_contrac_23271e_idx',
            old_name='business_co_contrac_idx',
        ),
        migrations.RenameIndex(
            model_name='contractnegotiation',
            new_name='business_co_client__62d5a1_idx',
            old_name='business_co_client_idx',
        ),
        migrations.RenameIndex(
            model_name='contractnegotiation',
            new_name='business_co_negotia_a17ce2_idx',
            old_name='business_co_negotia_idx',
        ),
        migrations.RenameIndex(
            model_name='contractnegotiation',
            new_name='business_co_status_f3bdbd_idx',
            old_name='business_co_status_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='customer_sc_name_c26e4d_idx',
            old_name='customer_sc_name_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='customer_sc_region_c6d0dc_idx',
            old_name='customer_sc_region_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='customer_sc_is_211_7d5b4e_idx',
            old_name='customer_sc_tags_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='customer_sc_is_acti_0d873b_idx',
            old_name='customer_sc_active_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- 安全添加字段（如果不存在）
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'business_authorization_letter' 
                                AND column_name = 'business_manager_id'
                            ) THEN
                                ALTER TABLE business_authorization_letter 
                                ADD COLUMN business_manager_id INTEGER NULL;
                            END IF;
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'business_authorization_letter' 
                                AND column_name = 'client_id'
                            ) THEN
                                ALTER TABLE business_authorization_letter 
                                ADD COLUMN client_id INTEGER NULL;
                            END IF;
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'business_authorization_letter' 
                                AND column_name = 'client_contact_id'
                            ) THEN
                                ALTER TABLE business_authorization_letter 
                                ADD COLUMN client_contact_id INTEGER NULL;
                            END IF;
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'business_authorization_letter' 
                                AND column_name = 'project_number'
                            ) THEN
                                ALTER TABLE business_authorization_letter 
                                ADD COLUMN project_number VARCHAR(50) NULL;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        ALTER TABLE business_authorization_letter DROP COLUMN IF EXISTS business_manager_id;
                        ALTER TABLE business_authorization_letter DROP COLUMN IF EXISTS client_id;
                        ALTER TABLE business_authorization_letter DROP COLUMN IF EXISTS client_contact_id;
                        ALTER TABLE business_authorization_letter DROP COLUMN IF EXISTS project_number;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='authorizationletter',
                    name='business_manager',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_authorization_letters', to=settings.AUTH_USER_MODEL, verbose_name='商务经理'),
                ),
                migrations.AddField(
                    model_name='authorizationletter',
                    name='client',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_letters', to='customer_management.client', verbose_name='关联客户'),
                ),
                migrations.AddField(
                    model_name='authorizationletter',
                    name='client_contact',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_letters', to='customer_management.clientcontact', verbose_name='单位代表（联系人）'),
                ),
                migrations.AddField(
                    model_name='authorizationletter',
                    name='project_number',
                    field=models.CharField(blank=True, help_text='自动生成：HT-YYYY-NNNN，不可修改', max_length=50, null=True, unique=True, verbose_name='项目编号'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='authorizationletter',
            name='design_stages',
            field=models.JSONField(blank=True, default=list, help_text='已废弃，请使用图纸阶段', verbose_name='设计阶段（已废弃）'),
        ),
        migrations.AlterField(
            model_name='authorizationletter',
            name='detailed_review_scopes',
            field=models.JSONField(blank=True, default=list, verbose_name='精细化审图范围（已废弃）'),
        ),
        migrations.AlterField(
            model_name='authorizationletter',
            name='process_optimization_scopes',
            field=models.JSONField(blank=True, default=list, verbose_name='过程优化范围（已废弃）'),
        ),
        migrations.AlterField(
            model_name='authorizationletter',
            name='result_optimization_scopes',
            field=models.JSONField(blank=True, default=list, verbose_name='结果优化范围（已废弃）'),
        ),
        migrations.AlterField(
            model_name='businessexpenseapplication',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contacteducation',
            name='school',
            field=models.ForeignKey(blank=True, help_text='从后台管理的学校列表中选择', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='customer_management.school', verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='contacteducation',
            name='school_name',
            field=models.CharField(blank=True, help_text='如果学校不在列表中，可手动输入', max_length=200, verbose_name='毕业学校名称（备用）'),
        ),
        migrations.AlterField(
            model_name='contractnegotiation',
            name='participants',
            field=models.ManyToManyField(help_text='我方参与洽谈的人员', related_name='participated_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='参与人员'),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='relationship_level',
            field=models.CharField(choices=[('first_contact', '首次沟通'), ('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], default='requirement_communication', max_length=30, verbose_name='关系等级'),
        ),
        migrations.AlterField(
            model_name='customerrelationshipupgrade',
            name='from_level',
            field=models.CharField(choices=[('first_contact', '首次沟通'), ('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], max_length=30, verbose_name='原关系等级'),
        ),
        migrations.AlterField(
            model_name='customerrelationshipupgrade',
            name='to_level',
            field=models.CharField(choices=[('first_contact', '首次沟通'), ('requirement_communication', '需求沟通'), ('cooperation_intention', '合作意向'), ('cooperation_recognition', '合作认可'), ('external_partner', '外部合伙人')], max_length=30, verbose_name='目标关系等级'),
        ),
        migrations.DeleteModel(
            name='BusinessExpenseApplicationRelatedContacts',
        ),
    ]
