# Generated by Django 4.2.7 on 2025-12-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0048_remove_businessexpenseapplicationrelatedcontacts_businessexpenseapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractchange',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='contractchange',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractchange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contractfile',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='contractstatuslog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='contractstatuslog',
            name='contract',
        ),
        migrations.DeleteModel(
            name='ContractApproval',
        ),
        migrations.DeleteModel(
            name='ContractChange',
        ),
        migrations.DeleteModel(
            name='ContractFile',
        ),
        migrations.DeleteModel(
            name='ContractStatusLog',
        ),
    ]
