# Generated by Django 4.2.7 on 2026-01-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0051_remove_filter_collapse_feature'),
    ]

    operations = [
    ]
