# Generated by Django 4.2.7 on 2026-01-17 14:41

from django.db import migrations


class Migration(migrations.Migration):
    """
    删除"逾期拜访提醒"功能
    
    说明：
    - "逾期拜访提醒"功能是基于ClientContact模型计算出来的，没有独立的数据库表
    - 已删除的内容：
      1. contact_tracking_reminders视图函数
      2. 菜单项配置
      3. URL路由配置
      4. 模板文件
      5. 客户管理首页中的相关代码
    
    此迁移文件用于记录删除操作，实际上不需要删除任何数据库表。
    """

    dependencies = [
        ('customer_management', '0052_add_customer_lead_filing_warehouse'),
    ]

    operations = [
        # 无需删除数据库表，因为"逾期拜访提醒"功能没有独立的数据库模型
        # 该功能是基于ClientContact模型计算出来的提醒信息
    ]
