# Generated by Django 4.2.7 on 2026-01-18 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0053_remove_contact_tracking_reminders'),
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='visit_plans',
                to='system_management.department',
                verbose_name='所属部门'
            ),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='responsible_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='responsible_visit_plans',
                to=settings.AUTH_USER_MODEL,
                verbose_name='负责人'
            ),
        ),
    ]
