# Generated by Django 4.2.7 on 2026-01-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0055_add_lead_number_to_customer_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWarehouseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, help_text='系统自动生成', max_length=100, verbose_name='申请编号')),
                ('application_type', models.CharField(choices=[('new_customer', '新客户入库'), ('customer_update', '客户信息更新'), ('customer_recovery', '客户恢复'), ('other', '其他')], default='new_customer', max_length=30, verbose_name='申请类型')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('application_reason', models.TextField(verbose_name='申请原因')),
                ('application_content', models.TextField(verbose_name='申请内容')),
                ('application_notes', models.TextField(blank=True, verbose_name='备注说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='申请状态')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_warehouse_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_applications', to='customer_management.client', verbose_name='关联客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_warehouse_applications', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_warehouse_applications', to='customer_management.businessopportunity', verbose_name='关联商机')),
            ],
            options={
                'verbose_name': '客户入库申请',
                'verbose_name_plural': '客户入库申请',
                'db_table': 'customer_warehouse_application',
                'ordering': ['-application_date', '-created_time'],
                'indexes': [models.Index(fields=['client', '-application_date'], name='customer_wa_client__6882eb_idx'), models.Index(fields=['application_number'], name='customer_wa_applica_2d3f48_idx'), models.Index(fields=['status', '-application_date'], name='customer_wa_status_0a3bb5_idx'), models.Index(fields=['application_type', '-application_date'], name='customer_wa_applica_1aaa31_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='客户编号')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, verbose_name='联系邮箱')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区县')),
                ('lead_source', models.CharField(choices=[('rcc_platform', 'RCC平台信息'), ('website', '官网咨询'), ('phone', '电话咨询'), ('exhibition', '展会'), ('referral', '转介绍'), ('other', '其他')], default='other', max_length=50, verbose_name='线索来源')),
                ('channel', models.CharField(blank=True, max_length=50, verbose_name='渠道')),
                ('follow_status', models.CharField(choices=[('unhandled', '未处理'), ('contact_valid', '联系方式有效'), ('contact_invalid', '联系方式无效'), ('converted', '已转化'), ('lost', '已流失')], default='unhandled', max_length=20, verbose_name='跟进状态')),
                ('latest_followup_note', models.TextField(blank=True, verbose_name='最新跟进记录')),
                ('actual_followup_time', models.DateTimeField(blank=True, null=True, verbose_name='实际跟进时间')),
                ('days_not_followed', models.IntegerField(default=0, verbose_name='未跟进天数')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('is_friend_added', models.BooleanField(default=False, verbose_name='是否已加好友')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customer_management.client', verbose_name='转化客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_leads', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '客户线索',
                'verbose_name_plural': '客户线索',
                'db_table': 'customer_lead',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['follow_status', 'responsible_user'], name='customer_le_follow__fe34e2_idx'), models.Index(fields=['lead_source', 'created_time'], name='customer_le_lead_so_4a754a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(verbose_name='备案日期')),
                ('filing_type', models.CharField(choices=[('initial', '初始备案'), ('update', '更新备案'), ('supplement', '补充备案'), ('annual', '年度备案'), ('other', '其他')], default='initial', max_length=20, verbose_name='备案类型')),
                ('filing_number', models.CharField(blank=True, help_text='系统自动生成或手动输入', max_length=100, verbose_name='备案编号')),
                ('filing_content', models.TextField(verbose_name='备案内容')),
                ('filing_purpose', models.TextField(blank=True, verbose_name='备案目的')),
                ('filing_notes', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='customer_management.client', verbose_name='关联客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_filings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_filings', to='customer_management.businessopportunity', verbose_name='关联商机')),
            ],
            options={
                'verbose_name': '客户备案记录',
                'verbose_name_plural': '客户备案记录',
                'db_table': 'customer_filing',
                'ordering': ['-filing_date', '-created_time'],
                'indexes': [models.Index(fields=['client', '-filing_date'], name='customer_fi_client__f5b531_idx'), models.Index(fields=['filing_number'], name='customer_fi_filing__10ec60_idx'), models.Index(fields=['filing_type', '-filing_date'], name='customer_fi_filing__ba8cfd_idx')],
            },
        ),
    ]
