# Generated by Django 4.2.7 on 2025-12-07 02:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_management', '0004_create_design_stage_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_management', '0008_delete_permissionitem'),
        ('plan_management', '0001_create_related_projects_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            -- 如果表已存在，跳过创建
                            IF EXISTS (
                                SELECT 1 FROM information_schema.tables 
                                WHERE table_schema = 'public' 
                                AND table_name = 'plan_plan'
                            ) THEN
                                RAISE NOTICE 'Table plan_plan already exists, skipping creation';
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(help_text='格式：PLAN-{YYYYMMDD}-{序列号}', max_length=50, unique=True, verbose_name='计划编号')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('plan_type', models.CharField(choices=[('personal', '个人计划'), ('department', '部门计划'), ('company', '公司计划'), ('project', '项目计划')], max_length=20, verbose_name='计划类型')),
                ('plan_period', models.CharField(choices=[('daily', '日计划'), ('weekly', '周计划'), ('monthly', '月计划'), ('quarterly', '季度计划'), ('yearly', '年计划')], max_length=20, verbose_name='计划周期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approving', '审批中'), ('approved', '已审批'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='计划状态')),
                ('alignment_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100分，自动计算', max_digits=5, verbose_name='目标对齐度')),
                ('contribution_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100分，评估计划对战略目标的贡献度', max_digits=5, verbose_name='贡献度评估')),
                ('content', models.TextField(help_text='支持富文本', max_length=5000, verbose_name='计划内容')),
                ('plan_objective', models.TextField(max_length=1000, verbose_name='计划目标')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('end_time', models.DateTimeField(verbose_name='计划结束时间')),
                ('duration_days', models.IntegerField(help_text='自动计算', verbose_name='计划周期（天）')),
                ('collaboration_plan', models.TextField(blank=True, help_text='如果选择了协作人员，必须填写协作计划', verbose_name='协作计划')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='计划优先级')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='单位：元', max_digits=15, null=True, verbose_name='计划预算')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('progress', models.DecimalField(decimal_places=2, default=0, help_text='百分比，0-100', max_digits=5, verbose_name='执行进度')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent_plan', models.ForeignKey(blank=True, help_text='用于计划分解', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='plan_management.plan', verbose_name='父计划')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_plans', to=settings.AUTH_USER_MODEL, verbose_name='协作人员')),
            ],
            options={
                'verbose_name': '计划',
                'verbose_name_plural': '计划',
                'db_table': 'plan_plan',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.CharField(help_text='格式：GOAL-{YYYYMMDD}-{序列号}', max_length=50, unique=True, verbose_name='目标编号')),
                ('name', models.CharField(max_length=200, verbose_name='目标名称')),
                ('goal_type', models.CharField(choices=[('financial', '财务目标'), ('market', '市场目标'), ('operation', '运营目标'), ('innovation', '创新目标'), ('talent', '人才目标'), ('other', '其他')], max_length=20, verbose_name='目标类型')),
                ('goal_period', models.CharField(choices=[('annual', '年度目标'), ('three_year', '三年目标'), ('five_year', '五年目标')], max_length=20, verbose_name='目标周期')),
                ('status', models.CharField(choices=[('draft', '制定中'), ('published', '已发布'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='目标状态')),
                ('indicator_name', models.CharField(max_length=100, verbose_name='目标指标名称')),
                ('indicator_type', models.CharField(choices=[('numeric', '数值型'), ('percentage', '百分比型'), ('boolean', '布尔型'), ('text', '文本型')], max_length=20, verbose_name='指标类型')),
                ('indicator_unit', models.CharField(blank=True, help_text='如：万元、%、个、次等', max_length=20, verbose_name='指标单位')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='目标值')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='当前值')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='百分比，自动计算', max_digits=5, verbose_name='完成率')),
                ('description', models.TextField(max_length=2000, verbose_name='目标描述')),
                ('background', models.TextField(blank=True, verbose_name='目标背景')),
                ('significance', models.TextField(blank=True, verbose_name='目标意义')),
                ('weight', models.DecimalField(decimal_places=2, help_text='范围0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='目标权重')),
                ('weight_description', models.TextField(blank=True, verbose_name='权重说明')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('duration_days', models.IntegerField(help_text='自动计算', verbose_name='目标周期（天）')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_goals', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent_goal', models.ForeignKey(blank=True, help_text='用于目标分解', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_goals', to='plan_management.strategicgoal', verbose_name='上级目标')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_goals', to=settings.AUTH_USER_MODEL, verbose_name='参与人员')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='related_goals', to='production_management.project', verbose_name='关联项目')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='system_management.department', verbose_name='负责部门')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_goals', to=settings.AUTH_USER_MODEL, verbose_name='目标负责人')),
            ],
            options={
                'verbose_name': '战略目标',
                'verbose_name_plural': '战略目标',
                'db_table': 'plan_strategic_goal',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PlanStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('change_reason', models.CharField(blank=True, max_length=500, verbose_name='变更原因')),
                ('changed_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='plan_management.plan', verbose_name='计划')),
            ],
            options={
                'verbose_name': '计划状态日志',
                'verbose_name_plural': '计划状态日志',
                'db_table': 'plan_plan_status_log',
                'ordering': ['-changed_time'],
            },
        ),
        migrations.CreateModel(
            name='PlanProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='进度百分比')),
                ('progress_description', models.TextField(verbose_name='进度说明')),
                ('execution_result', models.TextField(blank=True, verbose_name='执行结果')),
                ('execution_issues', models.TextField(blank=True, verbose_name='执行问题')),
                ('recorded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='plan_management.plan', verbose_name='计划')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_plan_progress', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '计划进度记录',
                'verbose_name_plural': '计划进度记录',
                'db_table': 'plan_plan_progress_record',
                'ordering': ['-recorded_time'],
            },
        ),
        migrations.CreateModel(
            name='PlanIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='问题状态')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('discovered_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发现时间')),
                ('resolved_time', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_issues', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plan_issues', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='plan_management.plan', verbose_name='计划')),
            ],
            options={
                'verbose_name': '计划问题',
                'verbose_name_plural': '计划问题',
                'db_table': 'plan_plan_issue',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_node', models.CharField(max_length=100, verbose_name='审批节点')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approval_opinion', models.TextField(verbose_name='审批意见')),
                ('approval_notes', models.TextField(blank=True, verbose_name='审批说明')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='plan_management.plan', verbose_name='计划')),
            ],
            options={
                'verbose_name': '计划审批记录',
                'verbose_name_plural': '计划审批记录',
                'db_table': 'plan_plan_approval',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='related_goal',
            field=models.ForeignKey(help_text='必填，选择关联的战略目标', on_delete=django.db.models.deletion.PROTECT, related_name='related_plans', to='plan_management.strategicgoal', verbose_name='关联战略目标'),
        ),
        migrations.AddField(
            model_name='plan',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_plans', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='plan',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='system_management.department', verbose_name='负责部门'),
        ),
        migrations.AddField(
            model_name='plan',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_plans', to=settings.AUTH_USER_MODEL, verbose_name='计划负责人'),
        ),
        migrations.CreateModel(
            name='GoalStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('change_reason', models.CharField(blank=True, max_length=500, verbose_name='变更原因')),
                ('changed_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='plan_management.strategicgoal', verbose_name='目标')),
            ],
            options={
                'verbose_name': '目标状态日志',
                'verbose_name_plural': '目标状态日志',
                'db_table': 'plan_goal_status_log',
                'ordering': ['-changed_time'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='当前值')),
                ('completion_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='完成率')),
                ('progress_description', models.TextField(verbose_name='进度说明')),
                ('recorded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='plan_management.strategicgoal', verbose_name='目标')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_goal_progress', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '目标进度记录',
                'verbose_name_plural': '目标进度记录',
                'db_table': 'plan_goal_progress_record',
                'ordering': ['-recorded_time'],
            },
        ),
        migrations.CreateModel(
            name='GoalAlignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_score', models.DecimalField(decimal_places=2, help_text='0-100分', max_digits=5, verbose_name='对齐度评分')),
                ('alignment_analysis', models.TextField(blank=True, verbose_name='对齐度分析')),
                ('suggestions', models.TextField(blank=True, verbose_name='提升建议')),
                ('recorded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('child_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_alignment_records', to='plan_management.strategicgoal', verbose_name='下级目标')),
                ('parent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_alignment_records', to='plan_management.strategicgoal', verbose_name='上级目标')),
            ],
            options={
                'verbose_name': '目标对齐度记录',
                'verbose_name_plural': '目标对齐度记录',
                'db_table': 'plan_goal_alignment_record',
            },
        ),
        migrations.CreateModel(
            name='GoalAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_reason', models.TextField(verbose_name='调整原因')),
                ('adjustment_content', models.TextField(verbose_name='调整内容')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('new_target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='新目标值')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='新结束日期')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_notes', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goal_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_goal_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='plan_management.strategicgoal', verbose_name='目标')),
            ],
            options={
                'verbose_name': '目标调整申请',
                'verbose_name_plural': '目标调整申请',
                'db_table': 'plan_goal_adjustment',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['goal_number'], name='plan_strate_goal_nu_b640cd_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['status'], name='plan_strate_status_eea008_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['goal_type'], name='plan_strate_goal_ty_a75d73_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['goal_period'], name='plan_strate_goal_pe_349c82_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['responsible_person'], name='plan_strate_respons_dbdf37_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['start_date', 'end_date'], name='plan_strate_start_d_e49fec_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicgoal',
            index=models.Index(fields=['parent_goal'], name='plan_strate_parent__08bd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='planstatuslog',
            index=models.Index(fields=['plan', '-changed_time'], name='plan_plan_s_plan_id_9e5969_idx'),
        ),
        migrations.AddIndex(
            model_name='planprogressrecord',
            index=models.Index(fields=['plan', '-recorded_time'], name='plan_plan_p_plan_id_572278_idx'),
        ),
        migrations.AddIndex(
            model_name='planissue',
            index=models.Index(fields=['plan', '-created_time'], name='plan_plan_i_plan_id_3c6ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='planissue',
            index=models.Index(fields=['status'], name='plan_plan_i_status_3c2bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='planissue',
            index=models.Index(fields=['severity'], name='plan_plan_i_severit_ccf1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='planapproval',
            index=models.Index(fields=['plan', '-created_time'], name='plan_plan_a_plan_id_0ed4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='planapproval',
            index=models.Index(fields=['status'], name='plan_plan_a_status_a3e130_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_number'], name='plan_plan_plan_nu_852fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status'], name='plan_plan_status_47cc73_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_type'], name='plan_plan_plan_ty_ad032d_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_period'], name='plan_plan_plan_pe_55c491_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['responsible_person'], name='plan_plan_respons_53d822_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['related_goal'], name='plan_plan_related_c849dc_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['start_time', 'end_time'], name='plan_plan_start_t_3aa5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['parent_plan'], name='plan_plan_parent__c223e4_idx'),
        ),
        migrations.AddIndex(
            model_name='goalstatuslog',
            index=models.Index(fields=['goal', '-changed_time'], name='plan_goal_s_goal_id_7bbb11_idx'),
        ),
        migrations.AddIndex(
            model_name='goalprogressrecord',
            index=models.Index(fields=['goal', '-recorded_time'], name='plan_goal_p_goal_id_10f169_idx'),
        ),
        migrations.AddIndex(
            model_name='goalalignmentrecord',
            index=models.Index(fields=['parent_goal', 'child_goal'], name='plan_goal_a_parent__1d6bf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goalalignmentrecord',
            unique_together={('parent_goal', 'child_goal')},
        ),
        migrations.AddIndex(
            model_name='goaladjustment',
            index=models.Index(fields=['goal', '-created_time'], name='plan_goal_a_goal_id_ca5d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='goaladjustment',
            index=models.Index(fields=['status'], name='plan_goal_a_status_003fb1_idx'),
        ),
            ],
        ),
    ]
