# Generated by Django 4.2.7 on 2026-01-23 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalnotification',
            name='event',
            field=models.CharField(choices=[('submit', '提交审批'), ('approve', '审批通过'), ('reject', '审批驳回'), ('cancel', '取消审批'), ('draft_timeout', '草稿超时'), ('approval_timeout', '审批超时'), ('company_goal_published', '公司目标发布'), ('personal_goal_published', '个人目标发布'), ('goal_accepted', '目标被接收'), ('company_plan_published', '公司计划发布'), ('personal_plan_published', '个人计划发布'), ('plan_accepted', '计划被接收'), ('weekly_plan_reminder', '周计划提醒'), ('weekly_plan_overdue', '周计划逾期'), ('goal_creation', '目标创建待办'), ('goal_progress_update', '目标进度更新待办'), ('plan_creation', '计划创建待办'), ('daily_plan_reminder', '日计划提醒'), ('plan_progress_update', '计划进度更新待办'), ('progress_update_notify_supervisor', '进度更新通知上级'), ('todo_overdue', '待办事项逾期'), ('work_summary_generated', '工作总结生成'), ('work_summary_supervisor', '工作总结上级通知'), ('daily_notification', '每日通知')], max_length=50, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='WorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('weekly', '周报'), ('monthly', '月报')], max_length=20, verbose_name='总结类型')),
                ('period_start', models.DateField(verbose_name='周期开始日期')),
                ('period_end', models.DateField(verbose_name='周期结束日期')),
                ('goal_progress_summary', models.JSONField(default=dict, verbose_name='目标进度汇总')),
                ('plan_completion_summary', models.JSONField(default=dict, verbose_name='计划完成汇总')),
                ('achievements', models.JSONField(default=list, verbose_name='成就亮点')),
                ('risk_items', models.JSONField(default=list, verbose_name='风险项')),
                ('sent_to_supervisor', models.BooleanField(default=False, verbose_name='是否已发送给上级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_summaries', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '工作总结',
                'verbose_name_plural': '工作总结',
                'db_table': 'plan_work_summary',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'summary_type'], name='plan_work_user_type_idx'), models.Index(fields=['period_start', 'period_end'], name='plan_work_period_idx')],
            },
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('goal_creation', '目标创建'), ('goal_decomposition', '目标分解'), ('goal_progress_update', '目标进度更新'), ('plan_creation', '计划创建'), ('plan_decomposition_weekly', '周计划分解'), ('plan_decomposition_daily', '日计划分解'), ('plan_progress_update', '计划进度更新')], max_length=50, verbose_name='待办类型')),
                ('title', models.CharField(max_length=200, verbose_name='待办标题')),
                ('description', models.TextField(blank=True, verbose_name='待办描述')),
                ('related_object_type', models.CharField(blank=True, choices=[('goal', '目标'), ('plan', '计划'), ('todo', '待办'), ('summary', '总结'), ('notification', '通知')], max_length=20, null=True, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联对象ID')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('auto_generated', models.BooleanField(default=True, verbose_name='是否系统自动生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'db_table': 'plan_todo_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='plan_todo_user_status_idx'), models.Index(fields=['deadline'], name='plan_todo_deadline_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='plan_todo_object_idx'), models.Index(fields=['task_type', 'status'], name='plan_todo_type_status_idx')],
            },
        ),
    ]
