# Generated by Django 4.2.7 on 2026-01-05 15:14

from django.db import migrations, models


def migrate_plan_statuses_forward(apps, schema_editor):
    """将审批相关状态转换为其他状态"""
    Plan = apps.get_model('plan_management', 'Plan')
    
    # 将 pending_approval (待审批) 转换为 draft (草稿)
    Plan.objects.filter(status='pending_approval').update(status='draft')
    
    # 将 approving (审批中) 和 approved (已审批) 转换为 in_progress (执行中)
    Plan.objects.filter(status__in=['approving', 'approved']).update(status='in_progress')


def migrate_plan_statuses_backward(apps, schema_editor):
    """反向迁移：将状态转换回审批状态（如果需要回滚）"""
    Plan = apps.get_model('plan_management', 'Plan')
    
    # 注意：反向迁移无法准确恢复原始状态，这里只是示例
    # 实际回滚时可能需要手动处理
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0002_initial'),
    ]

    operations = [
        # 第一步：迁移数据，将审批状态转换为其他状态
        migrations.RunPython(
            migrate_plan_statuses_forward,
            migrate_plan_statuses_backward,
        ),
        # 第二步：修改 Plan 状态字段，移除审批相关状态
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='计划状态'),
        ),
        # 第三步：删除 PlanApproval 模型（这会自动删除数据库表）
        migrations.DeleteModel(
            name='PlanApproval',
        ),
    ]
