# Generated by Django 4.2.7 on 2026-01-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0002_add_todo_task_and_work_summary_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalnotification',
            name='object_type',
            field=models.CharField(choices=[('plan', '计划'), ('goal', '目标'), ('todo', '待办'), ('summary', '总结'), ('notification', '通知')], max_length=20, verbose_name='对象类型'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='related_object_type',
            field=models.CharField(blank=True, choices=[('goal', '目标'), ('plan', '计划'), ('todo', '待办')], max_length=20, null=True, verbose_name='关联对象类型'),
        ),
    ]
