# Generated by Django 4.2.7 on 2026-01-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0003_alter_plan_status_delete_planapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='goal_type',
            field=models.CharField(choices=[('personal', '个人计划'), ('department', '部门计划'), ('company', '公司计划'), ('project', '项目计划')], max_length=20, verbose_name='目标类型'),
        ),
    ]
