# Generated by Django 4.2.7 on 2026-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0003_update_object_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='acceptance_criteria',
            field=models.CharField(help_text='明确说明如何判定计划完成', max_length=2000, verbose_name='验收标准'),
        ),
    ]
