# Generated by Django 4.2.7 on 2026-01-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0004_alter_plan_acceptance_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='acceptance_criteria',
        ),
    ]
