# Generated by Django 4.2.7 on 2026-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0004_update_goal_type_choices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='strategicgoal',
            name='plan_strate_start_d_e49fec_idx',
        ),
        migrations.RemoveIndex(
            model_name='strategicgoal',
            name='plan_strate_parent__08bd9a_idx',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='background',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='parent_goal',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='related_projects',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='significance',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='weight_description',
        ),
    ]
