# Generated by Django 4.2.7 on 2026-01-25 06:49

import backend.apps.plan_management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('plan_management', '0005_remove_acceptance_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('file', models.FileField(max_length=500, upload_to=backend.apps.plan_management.models.attachment_upload_path, verbose_name='附件文件')),
                ('name', models.CharField(help_text='显示名称', max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='上传时间')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联对象类型')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'plan_attachment',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='plan_attach_content_81f4bf_idx'), models.Index(fields=['-uploaded_at'], name='plan_attach_uploade_8d4519_idx')],
            },
        ),
    ]
