# Generated by Django 4.2.7 on 2026-01-07 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_management', '0005_remove_unused_goal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_reason', models.TextField(verbose_name='调整原因')),
                ('adjustment_content', models.TextField(verbose_name='调整内容')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('new_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='新计划名称')),
                ('new_start_time', models.DateTimeField(blank=True, null=True, verbose_name='新开始时间')),
                ('new_end_time', models.DateTimeField(blank=True, null=True, verbose_name='新结束时间')),
                ('new_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='新预算')),
                ('new_content', models.TextField(blank=True, max_length=5000, verbose_name='新计划内容')),
                ('new_plan_objective', models.TextField(blank=True, max_length=1000, verbose_name='新计划目标')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_notes', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plan_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plan_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('new_responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_plans', to=settings.AUTH_USER_MODEL, verbose_name='新负责人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='plan_management.plan', verbose_name='计划')),
            ],
            options={
                'verbose_name': '计划调整申请',
                'verbose_name_plural': '计划调整申请',
                'db_table': 'plan_plan_adjustment',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['plan', '-created_time'], name='plan_plan_a_plan_id_d529da_idx'), models.Index(fields=['status'], name='plan_plan_a_status_e42430_idx'), models.Index(fields=['created_by'], name='plan_plan_a_created_92fb3f_idx')],
            },
        ),
    ]
