# Generated by Django 6.0 on 2026-01-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0006_add_attachment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalnotification',
            name='event',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('submit', '提交审批'),
                    ('approve', '审批通过'),
                    ('reject', '审批驳回'),
                    ('cancel', '取消审批'),
                    ('draft_timeout', '草稿超时'),
                    ('approval_timeout', '审批超时'),
                    ('company_goal_published', '公司目标发布'),
                    ('personal_goal_published', '个人目标发布'),
                    ('goal_accepted', '目标被接收'),
                    ('company_plan_published', '公司计划发布'),
                    ('personal_plan_published', '个人计划发布'),
                    ('plan_accepted', '计划被接收'),
                    ('weekly_plan_reminder', '周计划提醒'),
                    ('weekly_plan_overdue', '周计划逾期'),
                    ('goal_creation', '目标创建待办'),
                    ('goal_progress_update', '目标进度更新待办'),
                    ('plan_creation', '计划创建待办'),
                    ('daily_plan_reminder', '日计划提醒'),
                    ('plan_progress_update', '计划进度更新待办'),
                    ('progress_update_notify_supervisor', '进度更新通知上级'),
                    ('todo_overdue', '待办事项逾期'),
                    ('work_summary_generated', '工作总结生成'),
                    ('work_summary_supervisor', '工作总结上级通知'),
                    ('daily_notification', '每日通知'),
                ],
                verbose_name='事件类型'
            ),
        ),
    ]
