# Generated by Django 4.2.7 on 2026-01-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0006_add_plan_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='collaboration_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='related_project',
        ),
        migrations.RemoveField(
            model_name='planadjustment',
            name='new_budget',
        ),
        migrations.AlterField(
            model_name='plan',
            name='related_goal',
            field=models.ForeignKey(help_text='必填，选择关联的年度目标', on_delete=django.db.models.deletion.PROTECT, related_name='related_plans', to='plan_management.strategicgoal', verbose_name='关联年度目标'),
        ),
    ]
