# Generated by Django 4.2.7 on 2026-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0007_remove_plan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_period',
            field=models.CharField(choices=[('daily', '日计划'), ('weekly', '周计划'), ('monthly', '月计划'), ('quarterly', '季度计划'), ('yearly', '年计划'), ('topic', '专题计划')], max_length=20, verbose_name='计划周期'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_approval', '审批中'), ('in_progress', '执行中'), ('overdue', '已逾期'), ('completed', '已完成'), ('cancelled', '已取消'), ('paused', '已暂停'), ('delayed', '已延期')], default='draft', max_length=20, verbose_name='计划状态'),
        ),
    ]
