# Generated by Django 4.2.7 on 2026-01-26 17:00

from django.db import migrations, models


def fill_acceptance_criteria(apps, schema_editor):
    """为现有计划记录填充验收标准默认值"""
    Plan = apps.get_model('plan_management', 'Plan')
    # 为所有现有记录设置默认值
    Plan.objects.filter(acceptance_criteria__isnull=True).update(
        acceptance_criteria='待补充验收标准'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0007_fix_notification_event_length'),
    ]

    operations = [
        # 第一步：添加字段，允许为空
        migrations.AddField(
            model_name='plan',
            name='acceptance_criteria',
            field=models.TextField(blank=True, null=True, help_text='计划完成的验收标准', max_length=1000, verbose_name='验收标准'),
        ),
        # 第二步：为现有记录填充默认值
        migrations.RunPython(fill_acceptance_criteria, migrations.RunPython.noop),
        # 第三步：将字段改为必填
        migrations.AlterField(
            model_name='plan',
            name='acceptance_criteria',
            field=models.TextField(blank=False, help_text='计划完成的验收标准', max_length=1000, verbose_name='验收标准'),
        ),
    ]
