# Generated by Django 4.2.7 on 2026-01-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
        ('plan_management', '0008_add_topic_plan_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='system_management.ourcompany', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='plan',
            name='org_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='system_management.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategic_goals', to='system_management.ourcompany', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='org_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategic_goals', to='system_management.department', verbose_name='部门'),
        ),
    ]
