# Generated by Django 4.2.7 on 2026-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0008_add_acceptance_criteria'),
    ]

    operations = [
        # 确保计划层级字段为必填（虽然已有默认值，但明确设置blank=False）
        migrations.AlterField(
            model_name='plan',
            name='level',
            field=models.CharField(choices=[('company', '公司计划'), ('personal', '个人计划')], default='company', help_text='company=公司计划, personal=个人计划', max_length=20, verbose_name='计划层级'),
        ),
        # 确保计划周期字段为必填
        migrations.AlterField(
            model_name='plan',
            name='plan_period',
            field=models.CharField(choices=[('daily', '日计划'), ('weekly', '周计划'), ('monthly', '月计划'), ('quarterly', '季度计划'), ('yearly', '年计划')], max_length=20, verbose_name='计划周期'),
        ),
    ]
