# Generated by Django 4.2.7 on 2026-01-28 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_management', '0009_make_level_plan_period_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaladjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('time', '时间调整'), ('content', '内容调整'), ('responsible', '负责人调整'), ('target_value', '目标值调整')], default='content', max_length=20, verbose_name='调整类型'),
        ),
        migrations.AddField(
            model_name='goaladjustment',
            name='new_responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_goals', to=settings.AUTH_USER_MODEL, verbose_name='新负责人'),
        ),
        migrations.AddField(
            model_name='goaladjustment',
            name='new_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='新开始日期'),
        ),
        migrations.AlterField(
            model_name='goaladjustment',
            name='adjustment_content',
            field=models.TextField(blank=True, verbose_name='调整内容'),
        ),
    ]
