# Generated by Django 4.2.7 on 2026-01-28 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def check_and_add_fields(apps, schema_editor):
    """检查字段是否存在，如果不存在则添加"""
    db_alias = schema_editor.connection.alias
    
    # 检查表结构
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'plan_plan_adjustment'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # 检查多对多关系表
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name = 'plan_plan_adjustment_new_participants'
        """)
        m2m_exists = cursor.fetchone() is not None
    
    # 只添加不存在的字段
    if 'adjustment_type' not in existing_columns:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ADD COLUMN adjustment_type varchar(20) DEFAULT 'content' NOT NULL
            """)
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ALTER COLUMN adjustment_type DROP DEFAULT
            """)
    
    if 'new_start_time' not in existing_columns:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ADD COLUMN new_start_time timestamp with time zone NULL
            """)
    
    if 'new_responsible_person_id' not in existing_columns:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ADD COLUMN new_responsible_person_id bigint NULL
            """)
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ADD CONSTRAINT plan_plan_adjustment_new_responsible_person_id_fk 
                FOREIGN KEY (new_responsible_person_id) 
                REFERENCES system_user(id) 
                ON DELETE SET NULL
            """)
    
    if 'new_plan_objective' not in existing_columns:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ADD COLUMN new_plan_objective text DEFAULT '' NOT NULL
            """)
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ALTER COLUMN new_plan_objective DROP DEFAULT
            """)
    
    if 'new_acceptance_criteria' not in existing_columns:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ADD COLUMN new_acceptance_criteria text DEFAULT '' NOT NULL
            """)
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ALTER COLUMN new_acceptance_criteria DROP DEFAULT
            """)
    
    # 创建多对多关系表
    if not m2m_exists:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE plan_plan_adjustment_new_participants (
                    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    planadjustment_id bigint NOT NULL,
                    user_id bigint NOT NULL
                )
            """)
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment_new_participants 
                ADD CONSTRAINT plan_plan_adjustment_new_participants_planadjustment_id_fk 
                FOREIGN KEY (planadjustment_id) 
                REFERENCES plan_plan_adjustment(id) 
                ON DELETE CASCADE
            """)
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment_new_participants 
                ADD CONSTRAINT plan_plan_adjustment_new_participants_user_id_fk 
                FOREIGN KEY (user_id) 
                REFERENCES system_user(id) 
                ON DELETE CASCADE
            """)
            cursor.execute("""
                CREATE UNIQUE INDEX plan_plan_adjustment_new_participants_unique 
                ON plan_plan_adjustment_new_participants (planadjustment_id, user_id)
            """)
    
    # 修改 adjustment_content 字段允许为空
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE plan_plan_adjustment 
            ALTER COLUMN adjustment_content DROP NOT NULL
        """)
    
    # 修改 new_end_time 字段允许为空（如果还没有）
    if 'new_end_time' in existing_columns:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE plan_plan_adjustment 
                ALTER COLUMN new_end_time DROP NOT NULL
            """)


def reverse_migration(apps, schema_editor):
    """回滚迁移"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_management', '0010_goaladjustment_adjustment_type_and_more'),
    ]

    operations = [
        migrations.RunPython(check_and_add_fields, reverse_migration),
        migrations.AlterField(
            model_name='planadjustment',
            name='adjustment_content',
            field=models.TextField(blank=True, verbose_name='调整内容'),
        ),
        migrations.AlterField(
            model_name='planadjustment',
            name='new_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='新结束时间'),
        ),
    ]
