# Generated by Django 4.2.7 on 2026-01-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0010_add_pending_approval_to_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_time'], 'permissions': [('approve_plan', 'Can approve plan')], 'verbose_name': '计划', 'verbose_name_plural': '计划'},
        ),
        migrations.AlterModelOptions(
            name='strategicgoal',
            options={'ordering': ['-created_time'], 'permissions': [('approve_strategicgoal', 'Can approve strategic goal')], 'verbose_name': '战略目标', 'verbose_name_plural': '战略目标'},
        ),
    ]
