# Generated by Django 4.2.7 on 2026-01-08 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_management', '0011_alter_plan_options_alter_strategicgoal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('object_type', models.CharField(choices=[('plan', '计划'), ('goal', '目标')], max_length=20, verbose_name='对象类型')),
                ('object_id', models.CharField(max_length=50, verbose_name='对象ID')),
                ('event', models.CharField(choices=[('submit', '提交审批'), ('approve', '审批通过'), ('reject', '审批驳回'), ('cancel', '取消审批')], max_length=20, verbose_name='事件类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '审批通知',
                'verbose_name_plural': '审批通知',
                'db_table': 'plan_approval_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='plan_approv_user_id_fdf6fe_idx'), models.Index(fields=['-created_at'], name='plan_approv_created_ef6d5d_idx'), models.Index(fields=['object_type', 'object_id'], name='plan_approv_object__3b2b49_idx')],
            },
        ),
    ]
