# Generated by Django 4.2.7 on 2026-01-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0045_backfill_contract_org'),
        ('plan_management', '0012_approvalnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicgoal',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='related_goals', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='related_goal',
            field=models.ForeignKey(blank=True, help_text='可选，选择关联的年度目标', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_plans', to='plan_management.strategicgoal', verbose_name='关联年度目标'),
        ),
    ]
