# Generated by Django 4.2.7 on 2026-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0013_strategicgoal_related_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalnotification',
            name='event',
            field=models.CharField(choices=[('submit', '提交审批'), ('approve', '审批通过'), ('reject', '审批驳回'), ('cancel', '取消审批'), ('draft_timeout', '草稿超时'), ('approval_timeout', '审批超时')], max_length=20, verbose_name='事件类型'),
        ),
    ]
