# Generated by Django 4.2.7 on 2026-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0013_state_sync_planadjustment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='completion_evidence',
            field=models.TextField(blank=True, help_text='可填写链接/编号/截图说明等，用于巡检核验', verbose_name='完成证据'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='completion_note',
            field=models.TextField(blank=True, help_text='人工完成时建议填写说明', verbose_name='完成说明'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='completion_via',
            field=models.CharField(blank=True, default='', help_text='auto=系统自动闭环，manual=人工提交', max_length=20, verbose_name='完成方式'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='verification_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='verification_reason',
            field=models.TextField(blank=True, verbose_name='核验说明/原因'),
        ),
        migrations.AddField(
            model_name='todotask',
            name='verification_status',
            field=models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('suspected', '疑似虚假完成')], default='pending', max_length=20, verbose_name='核验状态'),
        ),
    ]
