# Generated by Django 4.2.7 on 2026-01-13 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_management', '0015_create_plan_decision'),
    ]

    operations = [
        # 添加 Plan.acceptance_criteria 字段
        migrations.AddField(
            model_name='plan',
            name='acceptance_criteria',
            field=models.TextField(
                blank=True,
                help_text='明确说明如何判定计划完成，提交审批前必填',
                max_length=2000,
                verbose_name='验收标准'
            ),
        ),
        # 创建 PlanInactivityLog 模型
        migrations.CreateModel(
            name='PlanInactivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
                ('period_start', models.DateTimeField(verbose_name='检测区间开始')),
                ('period_end', models.DateTimeField(verbose_name='检测区间结束')),
                ('reason', models.CharField(choices=[('overdue_and_silent', '逾期且无操作'), ('overdue_no_progress', '逾期且无进度更新'), ('overdue_no_feedback', '逾期且无反馈')], max_length=50, verbose_name='触发原因')),
                ('reason_detail', models.TextField(blank=True, verbose_name='原因详情')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='记录检测时的计划状态、责任人等信息', verbose_name='状态快照')),
                ('is_confirmed', models.BooleanField(default=True, editable=False, help_text='是否为系统自动确认的不作为记录')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_logs', to='plan_management.plan', verbose_name='计划')),
            ],
            options={
                'verbose_name': '计划不作为记录',
                'verbose_name_plural': '计划不作为记录',
                'db_table': 'plan_plan_inactivity_log',
                'ordering': ['-detected_at'],
            },
        ),
        # 添加 PlanInactivityLog 的索引
        migrations.AddIndex(
            model_name='planinactivitylog',
            index=models.Index(fields=['plan', '-detected_at'], name='plan_plan_i_plan_id_12345_idx'),
        ),
        migrations.AddIndex(
            model_name='planinactivitylog',
            index=models.Index(fields=['reason', '-detected_at'], name='plan_plan_i_reason_12345_idx'),
        ),
        # 添加唯一约束：防止同一计划在同一时间段因同一原因重复生成记录
        migrations.AddConstraint(
            model_name='planinactivitylog',
            constraint=models.UniqueConstraint(fields=['plan', 'period_start', 'period_end', 'reason'], name='unique_plan_inactivity_period'),
        ),
        # 修改 PlanAdjustment：添加 original_end_time 字段
        migrations.AddField(
            model_name='planadjustment',
            name='original_end_time',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='记录调整前的截止时间',
                verbose_name='原截止时间'
            ),
        ),
    ]
