# Generated by Django 4.2.7 on 2026-01-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0019_disable_default_permissions'),
    ]

    operations = [
    ]
