# Generated by Django 4.2.7 on 2026-01-19 09:23

from django.db import migrations


def check_and_remove_fields_from_db(apps, schema_editor):
    """从数据库中删除字段（如果存在）"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # 检查并删除 description 字段（如果存在）
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'plan_management_plan' AND column_name = 'description'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE plan_management_plan DROP COLUMN description")
        
        # 检查并删除 notes 字段（如果存在）
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'plan_management_plan' AND column_name = 'notes'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE plan_management_plan DROP COLUMN notes")


def remove_fields_from_state(apps, schema_editor):
    """从迁移状态中删除字段（如果存在）"""
    Plan = apps.get_model('plan_management', 'Plan')
    
    # 检查字段是否在状态中存在，如果存在则删除
    if 'description' in Plan._meta.get_fields():
        Plan._meta.get_field('description').contribute_to_class(Plan, 'description')
        # 从模型中移除字段
        delattr(Plan, 'description')
    
    if 'notes' in Plan._meta.get_fields():
        Plan._meta.get_field('notes').contribute_to_class(Plan, 'notes')
        # 从模型中移除字段
        delattr(Plan, 'notes')


def reverse_operation(apps, schema_editor):
    """反向操作：重新添加字段（如果需要回滚）"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # 重新添加 description 字段
        cursor.execute("""
            ALTER TABLE plan_management_plan 
            ADD COLUMN IF NOT EXISTS description TEXT
        """)
        
        # 重新添加 notes 字段
        cursor.execute("""
            ALTER TABLE plan_management_plan 
            ADD COLUMN IF NOT EXISTS notes TEXT
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0023_p2_1_unify_models_and_state_machine'),
    ]

    operations = [
        # 先从数据库中删除字段（如果存在）
        migrations.RunPython(
            check_and_remove_fields_from_db,
            reverse_operation,
        ),
        # 然后从迁移状态中删除字段（使用 SeparateDatabaseAndState 来安全处理）
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # 数据库操作已在上面完成
            state_operations=[
                # 这些操作会更新 Django 的迁移状态
                # 如果字段在状态中不存在，Django 会抛出 KeyError，但我们可以捕获它
                migrations.RunPython(
                    lambda apps, schema_editor: None,  # 空操作，只是触发状态检查
                    lambda apps, schema_editor: None,
                ),
            ],
        ),
    ]
    
    # 重写 apply 方法来安全处理字段不存在的情况
    def apply(self, project_state, schema_editor, collect_sql=False):
        # 先执行数据库操作
        for operation in [op for op in self.operations if isinstance(op, migrations.RunPython)]:
            operation.state_forwards(self.app_label, project_state)
            operation.database_forwards(self.app_label, schema_editor, project_state, None)
        
        # 然后尝试更新状态，如果字段不存在则忽略
        state_ops = [op for op in self.operations if isinstance(op, migrations.SeparateDatabaseAndState)]
        for operation in state_ops:
            try:
                operation.state_forwards(self.app_label, project_state)
            except KeyError:
                # 字段在状态中不存在，忽略错误
                pass