# Generated by Django 4.2.7 on 2026-01-19

from django.db import migrations


def check_and_remove_priority_from_db(apps, schema_editor):
    """从数据库中删除priority字段（如果存在）"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # 检查并删除 priority 字段（如果存在）
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'plan_management_plan' AND column_name = 'priority'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE plan_management_plan DROP COLUMN priority")


def reverse_operation(apps, schema_editor):
    """反向操作：重新添加priority字段（如果需要回滚）"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # 重新添加 priority 字段
        cursor.execute("""
            ALTER TABLE plan_management_plan 
            ADD COLUMN IF NOT EXISTS priority VARCHAR(10) DEFAULT 'medium'
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0024_remove_plan_description_and_notes'),
    ]

    operations = [
        # 使用 SeparateDatabaseAndState 分离数据库操作和状态操作
        migrations.SeparateDatabaseAndState(
            # 数据库操作：删除字段（如果存在）
            database_operations=[
                migrations.RunPython(
                    check_and_remove_priority_from_db,
                    reverse_operation,
                ),
            ],
            # 状态操作：从迁移状态中删除字段
            state_operations=[
                migrations.RemoveField(
                    model_name='plan',
                    name='priority',
                ),
            ],
        ),
    ]
    
    def apply(self, project_state, schema_editor, collect_sql=False):
        """自定义apply方法，处理字段已经不存在的情况"""
        try:
            return super().apply(project_state, schema_editor, collect_sql)
        except KeyError as e:
            # 如果字段已经在状态中不存在，跳过状态操作，只执行数据库操作
            if 'priority' in str(e):
                # 只执行数据库操作
                for operation in self.operations:
                    if hasattr(operation, 'database_operations'):
                        for db_op in operation.database_operations:
                            db_op.apply(project_state, schema_editor, collect_sql)
                return project_state
            raise
