# Generated by Django 4.2.7 on 2026-01-19

from django.db import migrations


class SafeRemoveField(migrations.operations.fields.RemoveField):
    """安全删除字段：如果字段不存在则跳过"""
    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except KeyError:
            # 字段在状态中不存在，忽略错误
            pass


def remove_priority_from_db(apps, schema_editor):
    """从数据库中删除priority字段（如果存在）"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # 检查并删除 priority 字段（如果存在）
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'plan_management_plan' AND column_name = 'priority'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE plan_management_plan DROP COLUMN priority")


def reverse_operation(apps, schema_editor):
    """反向操作：重新添加priority字段（如果需要回滚）"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # 重新添加 priority 字段
        cursor.execute("""
            ALTER TABLE plan_management_plan 
            ADD COLUMN IF NOT EXISTS priority VARCHAR(10) DEFAULT 'medium'
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0024_remove_plan_description_and_notes'),
    ]

    operations = [
        # 先从数据库中删除字段（如果存在）
        migrations.RunPython(
            remove_priority_from_db,
            reverse_operation,
        ),
        # 然后从迁移状态中删除字段（使用安全删除）
        SafeRemoveField(
            model_name='plan',
            name='priority',
        ),
    ]
