# Generated by Django 4.2.7 on 2025-11-24 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_number', models.CharField(help_text='自动生成', max_length=100, unique=True, verbose_name='实例编号')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='审批状态')),
                ('apply_time', models.DateTimeField(blank=True, null=True, verbose_name='申请时间')),
                ('apply_comment', models.TextField(blank=True, verbose_name='申请说明')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('final_comment', models.TextField(blank=True, verbose_name='最终意见')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联对象类型')),
            ],
            options={
                'verbose_name': '审批实例',
                'verbose_name_plural': '审批实例',
                'db_table': 'workflow_approval_instance',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('start', '开始节点'), ('approval', '审批节点'), ('condition', '条件节点'), ('parallel', '并行节点'), ('end', '结束节点')], default='approval', max_length=20, verbose_name='节点类型')),
                ('sequence', models.IntegerField(default=1, help_text='数字越小越靠前', verbose_name='节点顺序')),
                ('approver_type', models.CharField(blank=True, choices=[('user', '指定用户'), ('role', '指定角色'), ('department', '指定部门'), ('department_manager', '部门经理'), ('creator', '创建人'), ('creator_manager', '创建人上级'), ('custom', '自定义规则')], max_length=30, verbose_name='审批人类型')),
                ('approval_mode', models.CharField(choices=[('single', '单人审批'), ('any', '任意一人通过'), ('all', '全部通过'), ('majority', '多数通过')], default='single', max_length=20, verbose_name='审批模式')),
                ('condition_expression', models.TextField(blank=True, help_text='JSON格式的条件表达式', verbose_name='条件表达式')),
                ('is_required', models.BooleanField(default=True, help_text='是否必须审批通过', verbose_name='是否必审')),
                ('can_reject', models.BooleanField(default=True, verbose_name='可驳回')),
                ('can_transfer', models.BooleanField(default=False, verbose_name='可转交')),
                ('timeout_hours', models.IntegerField(blank=True, help_text='覆盖流程默认超时时间', null=True, verbose_name='超时时间（小时）')),
                ('description', models.TextField(blank=True, verbose_name='节点描述')),
                ('approver_departments', models.ManyToManyField(blank=True, related_name='approval_nodes', to='system_management.department', verbose_name='指定部门')),
                ('approver_roles', models.ManyToManyField(blank=True, related_name='approval_nodes', to='system_management.role', verbose_name='指定角色')),
                ('approver_users', models.ManyToManyField(blank=True, related_name='approval_nodes', to=settings.AUTH_USER_MODEL, verbose_name='指定审批人')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'workflow_approval_node',
                'ordering': ['workflow', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：合同审批流程、商机审批流程', max_length=200, verbose_name='流程名称')),
                ('code', models.CharField(help_text='唯一标识，例如：contract_approval', max_length=100, unique=True, verbose_name='流程代码')),
                ('description', models.TextField(blank=True, verbose_name='流程描述')),
                ('category', models.CharField(blank=True, help_text='例如：合同管理、商机管理', max_length=100, verbose_name='流程分类')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('inactive', '停用')], default='draft', max_length=20, verbose_name='状态')),
                ('allow_withdraw', models.BooleanField(default=True, help_text='审批过程中是否允许撤回', verbose_name='允许撤回')),
                ('allow_reject', models.BooleanField(default=True, help_text='是否允许审批人驳回', verbose_name='允许驳回')),
                ('allow_transfer', models.BooleanField(default=False, help_text='是否允许审批人转交给他人', verbose_name='允许转交')),
                ('timeout_hours', models.IntegerField(blank=True, help_text='节点审批超时时间，为空则不限制', null=True, verbose_name='超时时间（小时）')),
                ('timeout_action', models.CharField(choices=[('auto_approve', '自动通过'), ('auto_reject', '自动驳回'), ('notify', '仅通知'), ('escalate', '升级审批')], default='notify', max_length=20, verbose_name='超时处理方式')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批流程模板',
                'verbose_name_plural': '审批流程模板',
                'db_table': 'workflow_template',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', '待审批'), ('approved', '通过'), ('rejected', '驳回'), ('transferred', '转交'), ('withdrawn', '撤回')], default='pending', max_length=20, verbose_name='审批结果')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审批时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workflow_engine.approvalinstance', verbose_name='审批实例')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='workflow_engine.approvalnode', verbose_name='审批节点')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_approvals', to=settings.AUTH_USER_MODEL, verbose_name='转交给')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'db_table': 'workflow_approval_record',
                'ordering': ['-approval_time'],
            },
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow_engine.workflowtemplate', verbose_name='所属流程'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_instances', to='workflow_engine.approvalnode', verbose_name='当前节点'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow_engine.workflowtemplate', verbose_name='流程模板'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalnode',
            unique_together={('workflow', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_ap_content_9b3edc_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status'], name='workflow_ap_status_dc8177_idx'),
        ),
    ]
