# Generated by Django 4.2.7 on 2025-11-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalinstance',
            name='content_type',
            field=models.ForeignKey(help_text='选择要关联的业务对象类型。例如：合同(businesscontract)、商机(businessopportunity)、项目(project)等。通常不需要手动填写，审批流程会在业务代码中自动创建并关联。', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联对象类型'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='object_id',
            field=models.PositiveIntegerField(help_text='填写该业务对象的具体ID。例如：合同ID为123，则填写123。通常不需要手动填写，审批流程会在业务代码中自动创建并关联。', verbose_name='关联对象ID'),
        ),
    ]
