# Generated by Django 4.2.7 on 2026-01-28 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0006_fix_applicable_models_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='applicable_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='指定此流程适用的业务模型，例如：businesscontract（合同）、businessopportunity（商机）、project（项目）等', size=None, verbose_name='适用模型'),
        ),
    ]
