#!/usr/bin/env python
"""
直接执行SQL创建计划管理模块的数据库表
绕过Django迁移系统的依赖问题
"""
import os
import sys

# 添加项目根目录到Python路径
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

# 设置环境变量，避免导入Django时加载URL配置
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.config.settings')

# 只导入必要的Django组件，避免URL配置错误
import django
from django.conf import settings
from django.core.management import execute_from_command_line

# 设置Django但不运行检查
django.setup()

from django.db import connection

def create_plan_strategic_goal_table():
    """创建 plan_strategic_goal 表"""
    cursor = connection.cursor()
    
    print("开始创建 plan_strategic_goal 表...")
    
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS "plan_strategic_goal" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "goal_number" varchar(50) NOT NULL UNIQUE,
        "name" varchar(200) NOT NULL,
        "goal_type" varchar(20) NOT NULL,
        "goal_period" varchar(20) NOT NULL,
        "status" varchar(20) NOT NULL DEFAULT 'draft',
        "indicator_name" varchar(100) NOT NULL,
        "indicator_type" varchar(20) NOT NULL,
        "indicator_unit" varchar(20) NOT NULL DEFAULT '',
        "target_value" numeric(20, 2) NOT NULL,
        "current_value" numeric(20, 2) NOT NULL DEFAULT 0,
        "completion_rate" numeric(5, 2) NOT NULL DEFAULT 0,
        "description" varchar(2000) NOT NULL,
        "background" text NOT NULL DEFAULT '',
        "significance" text NOT NULL DEFAULT '',
        "weight" numeric(5, 2) NOT NULL,
        "weight_description" text NOT NULL DEFAULT '',
        "start_date" date NOT NULL,
        "end_date" date NOT NULL,
        "duration_days" integer NOT NULL,
        "notes" text NOT NULL DEFAULT '',
        "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "responsible_person_id" bigint NOT NULL,
        "responsible_department_id" bigint NULL,
        "parent_goal_id" bigint NULL,
        "created_by_id" bigint NOT NULL
    );
    """
    
    try:
        cursor.execute(create_table_sql)
        print("✓ plan_strategic_goal 表创建成功")
    except Exception as e:
        print(f"⚠ plan_strategic_goal 表可能已存在: {e}")
    
    # 创建索引
    indexes = [
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_goal_number_idx" ON "plan_strategic_goal" ("goal_number");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_status_idx" ON "plan_strategic_goal" ("status");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_goal_type_idx" ON "plan_strategic_goal" ("goal_type");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_goal_period_idx" ON "plan_strategic_goal" ("goal_period");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_responsible_person_id_idx" ON "plan_strategic_goal" ("responsible_person_id");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_start_date_end_date_idx" ON "plan_strategic_goal" ("start_date", "end_date");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_parent_goal_id_idx" ON "plan_strategic_goal" ("parent_goal_id");',
    ]
    
    for index_sql in indexes:
        try:
            cursor.execute(index_sql)
        except Exception as e:
            print(f"⚠ 创建索引失败: {e}")
    
    print("✓ 索引创建完成")


def create_plan_plan_table():
    """创建 plan_plan 表"""
    cursor = connection.cursor()
    
    print("开始创建 plan_plan 表...")
    
    # 创建 plan_plan 表
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS "plan_plan" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "plan_number" varchar(50) NOT NULL UNIQUE,
        "name" varchar(200) NOT NULL,
        "plan_type" varchar(20) NOT NULL,
        "plan_period" varchar(20) NOT NULL,
        "status" varchar(20) NOT NULL DEFAULT 'draft',
        "alignment_score" numeric(5, 2) NOT NULL DEFAULT 0,
        "contribution_score" numeric(5, 2) NOT NULL DEFAULT 0,
        "content" text NOT NULL,
        "plan_objective" text NOT NULL,
        "description" text NOT NULL DEFAULT '',
        "start_time" timestamp with time zone NOT NULL,
        "end_time" timestamp with time zone NOT NULL,
        "duration_days" integer NOT NULL,
        "priority" varchar(10) NOT NULL DEFAULT 'medium',
        "budget" numeric(15, 2) NULL,
        "notes" text NOT NULL DEFAULT '',
        "progress" numeric(5, 2) NOT NULL DEFAULT 0,
        "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "related_goal_id" bigint NULL,
        "responsible_person_id" bigint NOT NULL,
        "responsible_department_id" bigint NULL,
        "related_project_id" bigint NULL,
        "parent_plan_id" bigint NULL,
        "created_by_id" bigint NOT NULL
    );
    """
    
    try:
        cursor.execute(create_table_sql)
        print("✓ plan_plan 表创建成功")
    except Exception as e:
        print(f"⚠ plan_plan 表可能已存在: {e}")
    
    # 创建索引
    indexes = [
        'CREATE INDEX IF NOT EXISTS "plan_plan_plan_number_idx" ON "plan_plan" ("plan_number");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_status_idx" ON "plan_plan" ("status");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_plan_type_idx" ON "plan_plan" ("plan_type");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_plan_period_idx" ON "plan_plan" ("plan_period");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_responsible_person_id_idx" ON "plan_plan" ("responsible_person_id");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_related_goal_id_idx" ON "plan_plan" ("related_goal_id");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_start_time_end_time_idx" ON "plan_plan" ("start_time", "end_time");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_parent_plan_id_idx" ON "plan_plan" ("parent_plan_id");',
    ]
    
    for index_sql in indexes:
        try:
            cursor.execute(index_sql)
        except Exception as e:
            print(f"⚠ 创建索引失败: {e}")
    
    print("✓ 索引创建完成")


def create_m2m_tables():
    """创建多对多关系表"""
    cursor = connection.cursor()
    
    print("开始创建多对多关系表...")
    
    # plan_plan_participants (Plan.participants)
    create_m2m_sql = """
    CREATE TABLE IF NOT EXISTS "plan_plan_participants" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "plan_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        UNIQUE("plan_id", "user_id")
    );
    """
    
    try:
        cursor.execute(create_m2m_sql)
        print("✓ plan_plan_participants 表创建成功")
    except Exception as e:
        print(f"⚠ plan_plan_participants 表可能已存在: {e}")
    
    # 创建索引
    m2m_indexes = [
        'CREATE INDEX IF NOT EXISTS "plan_plan_participants_plan_id_idx" ON "plan_plan_participants" ("plan_id");',
        'CREATE INDEX IF NOT EXISTS "plan_plan_participants_user_id_idx" ON "plan_plan_participants" ("user_id");',
    ]
    
    for index_sql in m2m_indexes:
        try:
            cursor.execute(index_sql)
        except Exception as e:
            print(f"⚠ 创建索引失败: {e}")
    
    # plan_strategic_goal_participants (StrategicGoal.participants)
    create_goal_m2m_sql = """
    CREATE TABLE IF NOT EXISTS "plan_strategic_goal_participants" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "strategicgoal_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        UNIQUE("strategicgoal_id", "user_id")
    );
    """
    
    try:
        cursor.execute(create_goal_m2m_sql)
        print("✓ plan_strategic_goal_participants 表创建成功")
    except Exception as e:
        print(f"⚠ plan_strategic_goal_participants 表可能已存在: {e}")
    
    # 创建索引
    goal_m2m_indexes = [
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_participants_goal_id_idx" ON "plan_strategic_goal_participants" ("strategicgoal_id");',
        'CREATE INDEX IF NOT EXISTS "plan_strategic_goal_participants_user_id_idx" ON "plan_strategic_goal_participants" ("user_id");',
    ]
    
    for index_sql in goal_m2m_indexes:
        try:
            cursor.execute(index_sql)
        except Exception as e:
            print(f"⚠ 创建索引失败: {e}")
    
    print("✓ 多对多关系表创建完成")
    
    # 注意：外键约束暂时不创建，因为相关表可能不存在
    # 如果相关表存在，可以稍后添加外键约束

if __name__ == '__main__':
    try:
        create_plan_strategic_goal_table()
        create_plan_plan_table()
        create_m2m_tables()
        print("\n✅ 所有表创建完成！")
    except Exception as e:
        print(f"\n❌ 创建表时发生错误: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

