#!/usr/bin/env python
"""
直接执行SQL创建客户管理模块的新表
绕过Django迁移系统的依赖问题
"""
import os
import sys

# 添加项目根目录到Python路径
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

import django

# 设置Django环境
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.config.settings')
django.setup()

from django.db import connection

def execute_sql():
    """执行SQL创建表"""
    cursor = connection.cursor()
    
    # SQL语句列表
    sql_statements = [
        # 创建 customer_visit_plan 表
        """
        CREATE TABLE IF NOT EXISTS "customer_visit_plan" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "plan_date" timestamp with time zone NOT NULL,
            "plan_title" varchar(200) NOT NULL,
            "plan_purpose" text NOT NULL,
            "location" varchar(200) NOT NULL DEFAULT '',
            "participants" varchar(500) NOT NULL DEFAULT '',
            "status" varchar(20) NOT NULL DEFAULT 'planned',
            "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "client_id" bigint NOT NULL,
            "created_by_id" bigint NOT NULL,
            "related_opportunity_id" bigint NULL
        );
        """,
        
        # 创建 customer_visit_checkin 表
        """
        CREATE TABLE IF NOT EXISTS "customer_visit_checkin" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "checkin_time" timestamp with time zone NOT NULL,
            "checkin_location" varchar(200) NOT NULL,
            "latitude" numeric(10, 7) NULL,
            "longitude" numeric(10, 7) NULL,
            "notes" text NOT NULL DEFAULT '',
            "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "client_id" bigint NOT NULL,
            "created_by_id" bigint NOT NULL,
            "visit_plan_id" bigint NULL
        );
        """,
        
        # 创建 sales_activity 表
        """
        CREATE TABLE IF NOT EXISTS "sales_activity" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "activity_type" varchar(20) NOT NULL,
            "title" varchar(200) NOT NULL,
            "start_time" timestamp with time zone NOT NULL,
            "end_time" timestamp with time zone NOT NULL,
            "location" varchar(200) NOT NULL DEFAULT '',
            "description" text NOT NULL DEFAULT '',
            "is_completed" boolean NOT NULL DEFAULT false,
            "completed_time" timestamp with time zone NULL,
            "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "related_client_id" bigint NULL,
            "related_opportunity_id" bigint NULL,
            "sales_person_id" bigint NOT NULL
        );
        """,
        
        # 创建 customer_relationship 表
        """
        CREATE TABLE IF NOT EXISTS "customer_relationship" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "relationship_type" varchar(20) NOT NULL,
            "title" varchar(200) NOT NULL,
            "content" text NOT NULL,
            "relationship_date" timestamp with time zone NOT NULL,
            "location" varchar(200) NOT NULL DEFAULT '',
            "participants" varchar(500) NOT NULL DEFAULT '',
            "next_action" text NOT NULL DEFAULT '',
            "next_action_date" date NULL,
            "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "client_id" bigint NOT NULL,
            "created_by_id" bigint NOT NULL,
            "related_opportunity_id" bigint NULL
        );
        """,
        
        # 创建 customer_lead_followup 表
        """
        CREATE TABLE IF NOT EXISTS "customer_lead_followup" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "follow_date" timestamp with time zone NOT NULL,
            "follow_type" varchar(20) NOT NULL DEFAULT 'phone',
            "content" text NOT NULL,
            "customer_feedback" text NOT NULL DEFAULT '',
            "next_plan" text NOT NULL DEFAULT '',
            "next_follow_date" timestamp with time zone NULL,
            "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "lead_id" bigint NOT NULL,
            "created_by_id" bigint NOT NULL
        );
        """,
        
        # 创建 customer_lead 表
        """
        CREATE TABLE IF NOT EXISTS "customer_lead" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "contact_name" varchar(100) NOT NULL,
            "contact_phone" varchar(20) NOT NULL DEFAULT '',
            "contact_email" varchar(100) NOT NULL DEFAULT '',
            "company_name" varchar(200) NOT NULL,
            "province" varchar(50) NOT NULL DEFAULT '',
            "city" varchar(50) NOT NULL DEFAULT '',
            "district" varchar(50) NOT NULL DEFAULT '',
            "lead_source" varchar(50) NOT NULL DEFAULT 'other',
            "channel" varchar(50) NOT NULL DEFAULT '',
            "follow_status" varchar(20) NOT NULL DEFAULT 'unhandled',
            "latest_followup_note" text NOT NULL DEFAULT '',
            "actual_followup_time" timestamp with time zone NULL,
            "days_not_followed" integer NOT NULL DEFAULT 0,
            "department" varchar(100) NOT NULL DEFAULT '',
            "is_friend_added" boolean NOT NULL DEFAULT false,
            "is_active" boolean NOT NULL DEFAULT true,
            "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "converted_client_id" bigint NULL,
            "created_by_id" bigint NOT NULL,
            "responsible_user_id" bigint NULL
        );
        """,
    ]
    
    # 创建索引和外键的SQL
    index_and_fk_sql = [
        # customer_visit_plan 索引和外键
        'CREATE INDEX IF NOT EXISTS "customer_vi_plan_da_33b14f_idx" ON "customer_visit_plan" ("plan_date", "status");',
        'CREATE INDEX IF NOT EXISTS "customer_vi_client__4278df_idx" ON "customer_visit_plan" ("client_id", "plan_date");',
        'CREATE INDEX IF NOT EXISTS "customer_visit_plan_client_id_39e6b979" ON "customer_visit_plan" ("client_id");',
        'CREATE INDEX IF NOT EXISTS "customer_visit_plan_created_by_id_fda0b0c9" ON "customer_visit_plan" ("created_by_id");',
        'CREATE INDEX IF NOT EXISTS "customer_visit_plan_related_opportunity_id_f077a8e7" ON "customer_visit_plan" ("related_opportunity_id");',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_visit_plan_client_id_39e6b979_fk\') THEN ALTER TABLE "customer_visit_plan" ADD CONSTRAINT "customer_visit_plan_client_id_39e6b979_fk" FOREIGN KEY ("client_id") REFERENCES "customer_client" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_visit_plan_created_by_id_fda0b0c9_fk\') THEN ALTER TABLE "customer_visit_plan" ADD CONSTRAINT "customer_visit_plan_created_by_id_fda0b0c9_fk" FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_visit_plan_related_opportunity__f077a8e7_fk\') THEN ALTER TABLE "customer_visit_plan" ADD CONSTRAINT "customer_visit_plan_related_opportunity__f077a8e7_fk" FOREIGN KEY ("related_opportunity_id") REFERENCES "business_opportunity" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        
        # customer_visit_checkin 索引和外键
        'CREATE INDEX IF NOT EXISTS "customer_vi_client__042b18_idx" ON "customer_visit_checkin" ("client_id", "checkin_time");',
        'CREATE INDEX IF NOT EXISTS "customer_vi_checkin_113b7d_idx" ON "customer_visit_checkin" ("checkin_time");',
        'CREATE INDEX IF NOT EXISTS "customer_visit_checkin_client_id_8a319a31" ON "customer_visit_checkin" ("client_id");',
        'CREATE INDEX IF NOT EXISTS "customer_visit_checkin_created_by_id_8a859e7e" ON "customer_visit_checkin" ("created_by_id");',
        'CREATE INDEX IF NOT EXISTS "customer_visit_checkin_visit_plan_id_a128f95f" ON "customer_visit_checkin" ("visit_plan_id");',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_visit_checkin_client_id_8a319a31_fk\') THEN ALTER TABLE "customer_visit_checkin" ADD CONSTRAINT "customer_visit_checkin_client_id_8a319a31_fk" FOREIGN KEY ("client_id") REFERENCES "customer_client" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_visit_checkin_created_by_id_8a859e7e_fk\') THEN ALTER TABLE "customer_visit_checkin" ADD CONSTRAINT "customer_visit_checkin_created_by_id_8a859e7e_fk" FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_visit_check_visit_plan_id_a128f95f_fk\') THEN ALTER TABLE "customer_visit_checkin" ADD CONSTRAINT "customer_visit_check_visit_plan_id_a128f95f_fk" FOREIGN KEY ("visit_plan_id") REFERENCES "customer_visit_plan" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        
        # sales_activity 索引和外键
        'CREATE INDEX IF NOT EXISTS "sales_activ_sales_p_9c0087_idx" ON "sales_activity" ("sales_person_id", "start_time");',
        'CREATE INDEX IF NOT EXISTS "sales_activ_activit_4d7c41_idx" ON "sales_activity" ("activity_type", "start_time");',
        'CREATE INDEX IF NOT EXISTS "sales_activ_is_comp_d6ac03_idx" ON "sales_activity" ("is_completed", "start_time");',
        'CREATE INDEX IF NOT EXISTS "sales_activity_related_client_id_57d3b7c6" ON "sales_activity" ("related_client_id");',
        'CREATE INDEX IF NOT EXISTS "sales_activity_related_opportunity_id_ad96d40a" ON "sales_activity" ("related_opportunity_id");',
        'CREATE INDEX IF NOT EXISTS "sales_activity_sales_person_id_fa06b4ca" ON "sales_activity" ("sales_person_id");',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'sales_activity_related_client_id_57d3b7c6_fk\') THEN ALTER TABLE "sales_activity" ADD CONSTRAINT "sales_activity_related_client_id_57d3b7c6_fk" FOREIGN KEY ("related_client_id") REFERENCES "customer_client" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'sales_activity_related_opportunity__ad96d40a_fk\') THEN ALTER TABLE "sales_activity" ADD CONSTRAINT "sales_activity_related_opportunity__ad96d40a_fk" FOREIGN KEY ("related_opportunity_id") REFERENCES "business_opportunity" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'sales_activity_sales_person_id_fa06b4ca_fk\') THEN ALTER TABLE "sales_activity" ADD CONSTRAINT "sales_activity_sales_person_id_fa06b4ca_fk" FOREIGN KEY ("sales_person_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        
        # customer_relationship 索引和外键
        'CREATE INDEX IF NOT EXISTS "customer_re_client__b399b1_idx" ON "customer_relationship" ("client_id", "relationship_date");',
        'CREATE INDEX IF NOT EXISTS "customer_relationship_client_id_e8425663" ON "customer_relationship" ("client_id");',
        'CREATE INDEX IF NOT EXISTS "customer_relationship_created_by_id_8cb0b54b" ON "customer_relationship" ("created_by_id");',
        'CREATE INDEX IF NOT EXISTS "customer_relationship_related_opportunity_id_674a21d6" ON "customer_relationship" ("related_opportunity_id");',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_relationship_client_id_e8425663_fk\') THEN ALTER TABLE "customer_relationship" ADD CONSTRAINT "customer_relationship_client_id_e8425663_fk" FOREIGN KEY ("client_id") REFERENCES "customer_client" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_relationship_created_by_id_8cb0b54b_fk\') THEN ALTER TABLE "customer_relationship" ADD CONSTRAINT "customer_relationship_created_by_id_8cb0b54b_fk" FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_relationshi_related_opportunity__674a21d6_fk\') THEN ALTER TABLE "customer_relationship" ADD CONSTRAINT "customer_relationshi_related_opportunity__674a21d6_fk" FOREIGN KEY ("related_opportunity_id") REFERENCES "business_opportunity" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        
        # customer_lead 索引和外键
        'CREATE INDEX IF NOT EXISTS "customer_le_follow__fe34e2_idx" ON "customer_lead" ("follow_status", "responsible_user_id");',
        'CREATE INDEX IF NOT EXISTS "customer_le_lead_so_4a754a_idx" ON "customer_lead" ("lead_source", "created_time");',
        'CREATE INDEX IF NOT EXISTS "customer_lead_converted_client_id_1061422c" ON "customer_lead" ("converted_client_id");',
        'CREATE INDEX IF NOT EXISTS "customer_lead_created_by_id_94b40c50" ON "customer_lead" ("created_by_id");',
        'CREATE INDEX IF NOT EXISTS "customer_lead_responsible_user_id_fb0f5890" ON "customer_lead" ("responsible_user_id");',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_lead_converted_client_id_1061422c_fk\') THEN ALTER TABLE "customer_lead" ADD CONSTRAINT "customer_lead_converted_client_id_1061422c_fk" FOREIGN KEY ("converted_client_id") REFERENCES "customer_client" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_lead_created_by_id_94b40c50_fk\') THEN ALTER TABLE "customer_lead" ADD CONSTRAINT "customer_lead_created_by_id_94b40c50_fk" FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_lead_responsible_user_id_fb0f5890_fk\') THEN ALTER TABLE "customer_lead" ADD CONSTRAINT "customer_lead_responsible_user_id_fb0f5890_fk" FOREIGN KEY ("responsible_user_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        
        # customer_lead_followup 索引和外键
        'CREATE INDEX IF NOT EXISTS "customer_lead_followup_lead_id_idx" ON "customer_lead_followup" ("lead_id", "follow_date");',
        'CREATE INDEX IF NOT EXISTS "customer_lead_followup_lead_id_fk_idx" ON "customer_lead_followup" ("lead_id");',
        'CREATE INDEX IF NOT EXISTS "customer_lead_followup_created_by_id_fk_idx" ON "customer_lead_followup" ("created_by_id");',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_lead_followup_lead_id_fk\') THEN ALTER TABLE "customer_lead_followup" ADD CONSTRAINT "customer_lead_followup_lead_id_fk" FOREIGN KEY ("lead_id") REFERENCES "customer_lead" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
        'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = \'customer_lead_followup_created_by_id_fk\') THEN ALTER TABLE "customer_lead_followup" ADD CONSTRAINT "customer_lead_followup_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") DEFERRABLE INITIALLY DEFERRED; END IF; END $$;',
    ]
    
    success_count = 0
    error_count = 0
    
    print("开始创建表...")
    for sql in sql_statements:
        try:
            cursor.execute(sql)
            success_count += 1
            print(f"✓ 表创建成功 ({success_count}/{len(sql_statements)})")
        except Exception as e:
            error_count += 1
            print(f"✗ 表创建失败: {str(e)}")
            # 如果表已存在，继续执行
            if 'already exists' in str(e).lower() or 'duplicate' in str(e).lower():
                print("  (表已存在，跳过)")
                success_count += 1
                error_count -= 1
    
    print("\n开始创建索引和外键...")
    for sql in index_and_fk_sql:
        try:
            cursor.execute(sql)
            success_count += 1
        except Exception as e:
            error_count += 1
            print(f"✗ 索引/外键创建失败: {str(e)}")
            # 如果索引或约束已存在，继续执行
            if 'already exists' in str(e).lower() or 'duplicate' in str(e).lower():
                error_count -= 1
    
    connection.commit()
    
    print(f"\n完成！成功: {success_count}, 失败: {error_count}")
    
    # 验证表是否创建成功
    print("\n验证表是否存在...")
    tables_to_check = [
        'customer_lead',
        'customer_lead_followup',
        'customer_relationship',
        'customer_visit_plan',
        'customer_visit_checkin',
        'sales_activity'
    ]
    
    for table_name in tables_to_check:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [table_name])
        exists = cursor.fetchone()[0]
        status = "✓" if exists else "✗"
        print(f"{status} {table_name}")

if __name__ == '__main__':
    execute_sql()

