#!/usr/bin/env python
"""
直接执行SQL创建业务委托书表
绕过Django迁移系统的依赖问题
"""
import os
import sys

# 添加项目根目录到Python路径
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

import django

# 设置Django环境
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.config.settings')
django.setup()

from django.db import connection

def execute_sql():
    """执行SQL创建表"""
    cursor = connection.cursor()
    
    try:
        # 创建 business_authorization_letter 表
        print("正在创建 business_authorization_letter 表...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "business_authorization_letter" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "letter_number" varchar(50) NULL UNIQUE,
                "project_name" varchar(200) NOT NULL,
                "provisional_price" numeric(15, 2) NULL,
                "letter_date" date NOT NULL,
                "status" varchar(20) NOT NULL DEFAULT 'draft',
                "client_name" varchar(200) NOT NULL,
                "client_representative" varchar(100) NOT NULL DEFAULT '',
                "client_phone" varchar(50) NOT NULL DEFAULT '',
                "client_email" varchar(254) NOT NULL DEFAULT '',
                "client_address" varchar(500) NOT NULL DEFAULT '',
                "trustee_name" varchar(200) NOT NULL DEFAULT '四川维海科技有限公司',
                "trustee_representative" varchar(100) NOT NULL DEFAULT '',
                "trustee_phone" varchar(50) NOT NULL DEFAULT '',
                "trustee_email" varchar(254) NOT NULL DEFAULT '',
                "trustee_address" varchar(500) NOT NULL DEFAULT '',
                "design_stages" jsonb NOT NULL DEFAULT '[]',
                "result_optimization_scopes" jsonb NOT NULL DEFAULT '[]',
                "process_optimization_scopes" jsonb NOT NULL DEFAULT '[]',
                "detailed_review_scopes" jsonb NOT NULL DEFAULT '[]',
                "result_optimization_rate" numeric(5, 2) NULL,
                "process_optimization_rate" numeric(5, 2) NULL,
                "detailed_review_unit_price_min" numeric(10, 2) NULL,
                "detailed_review_unit_price_max" numeric(10, 2) NULL,
                "fee_determination_principle" text NOT NULL DEFAULT '',
                "settlement_review_process" text NOT NULL DEFAULT '',
                "payment_schedule" jsonb NOT NULL DEFAULT '{}',
                "supplementary_agreement" text NOT NULL DEFAULT '',
                "start_date" date NULL,
                "end_date" date NULL,
                "duration_days" integer NULL,
                "notes" text NOT NULL DEFAULT '',
                "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "created_by_id" bigint NOT NULL,
                "opportunity_id" bigint NULL,
                "project_id" bigint NULL,
                CONSTRAINT "business_authorization_letter_created_by_id_fk" 
                    FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") ON DELETE RESTRICT,
                CONSTRAINT "business_authorization_letter_opportunity_id_fk" 
                    FOREIGN KEY ("opportunity_id") REFERENCES "business_opportunity" ("id") ON DELETE SET NULL,
                CONSTRAINT "business_authorization_letter_project_id_fk" 
                    FOREIGN KEY ("project_id") REFERENCES "production_management_project" ("id") ON DELETE SET NULL
            );
        """)
        print("✓ 创建 business_authorization_letter 表成功")
        
        # 创建索引
        print("正在创建索引...")
        indexes = [
            ('business_au_letter__idx', 'letter_number'),
            ('business_au_status_idx', 'status'),
            ('business_au_client__idx', 'client_name'),
            ('business_au_opportun_idx', 'opportunity_id'),
            ('business_au_letter__idx2', 'letter_date'),
        ]
        
        for index_name, column in indexes:
            try:
                cursor.execute(f"""
                    CREATE INDEX IF NOT EXISTS "{index_name}" 
                    ON "business_authorization_letter" ("{column}");
                """)
                print(f"✓ 创建索引 {index_name} 成功")
            except Exception as e:
                print(f"⚠ 索引 {index_name} 可能已存在: {e}")
        
        # 创建 business_authorization_letter_template 表
        print("\n正在创建 business_authorization_letter_template 表...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "business_authorization_letter_template" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "template_name" varchar(200) NOT NULL,
                "template_type" varchar(50) NOT NULL DEFAULT 'service',
                "category" varchar(100) NOT NULL DEFAULT '',
                "status" varchar(20) NOT NULL DEFAULT 'draft',
                "description" text NOT NULL DEFAULT '',
                "template_content" jsonb NOT NULL DEFAULT '{}',
                "variables" jsonb NOT NULL DEFAULT '[]',
                "usage_count" integer NOT NULL DEFAULT 0,
                "last_used_time" timestamp with time zone NULL,
                "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "created_by_id" bigint NOT NULL,
                "updated_by_id" bigint NULL,
                CONSTRAINT "business_authorization_letter_template_created_by_id_fk" 
                    FOREIGN KEY ("created_by_id") REFERENCES "system_user" ("id") ON DELETE RESTRICT,
                CONSTRAINT "business_authorization_letter_template_updated_by_id_fk" 
                    FOREIGN KEY ("updated_by_id") REFERENCES "system_user" ("id") ON DELETE SET NULL
            );
        """)
        print("✓ 创建 business_authorization_letter_template 表成功")
        
        # 创建模板表索引
        print("正在创建模板表索引...")
        template_indexes = [
            ('business_au_template_type_status_idx', 'template_type', 'status'),
            ('business_au_template_status_idx', 'status'),
            ('business_au_template_created_time_idx', 'created_time'),
        ]
        
        for index_name, *columns in template_indexes:
            try:
                columns_str = ', '.join(f'"{col}"' for col in columns)
                cursor.execute(f"""
                    CREATE INDEX IF NOT EXISTS "{index_name}" 
                    ON "business_authorization_letter_template" ({columns_str});
                """)
                print(f"✓ 创建索引 {index_name} 成功")
            except Exception as e:
                print(f"⚠ 索引 {index_name} 可能已存在: {e}")
        
        # 提交事务
        connection.commit()
        print("\n✓ 所有操作完成！")
        
    except Exception as e:
        connection.rollback()
        print(f"\n✗ 创建表失败: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    return True

if __name__ == '__main__':
    print("=" * 60)
    print("创建业务委托书表脚本")
    print("=" * 60)
    success = execute_sql()
    if success:
        print("\n✓ 脚本执行成功！")
        sys.exit(0)
    else:
        print("\n✗ 脚本执行失败！")
        sys.exit(1)

