# Generated by Django 4.2.7 on 2025-12-07 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0004_create_design_stage_model'),
        ('production_quality', '0006_alter_opinion_project_alter_productionreport_project_and_more'),
        ('settlement_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsettlement',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='contractsettlement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_contract_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='contractsettlement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_settlements_management', to='production_management.businesscontract', verbose_name='关联合同'),
        ),
        migrations.AlterField(
            model_name='contractsettlement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='contractsettlement',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_contract_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='outputvaluerecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_output_values_management', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='outputvaluerecord',
            name='responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_value_records_management', to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments_management', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments_management', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settlements_management', to='production_management.businesscontract', verbose_name='关联合同'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='reconciliation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='对账人'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_settlements_management', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='servicefeerate',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='如果为空，则为全局费率表', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_rates_management', to='production_management.businesscontract', verbose_name='关联合同'),
        ),
        migrations.AlterField(
            model_name='servicefeerate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_fee_rates_management', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='settlementitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlement_items_management', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='settlementitem',
            name='opinion',
            field=models.ForeignKey(blank=True, help_text='从生产管理模块的意见生成', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items_management', to='production_quality.opinion', verbose_name='关联意见'),
        ),
        migrations.AlterField(
            model_name='settlementitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_settlement_items_management', to=settings.AUTH_USER_MODEL, verbose_name='审核造价工程师'),
        ),
    ]
