# Generated by Django 4.2.7 on 2026-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_management', '0003_convert_opinion_to_opinion_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='settlementitem',
            name='settlement__opinion_ef0b16_idx',
        ),
        migrations.AlterUniqueTogether(
            name='settlementitem',
            unique_together={('settlement', 'opinion_id')},
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['opinion_id'], name='settlement__opinion_ef0b16_idx'),
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='opinion',
        ),
    ]
