# Generated by Django 4.2.7 on 2025-11-08 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, verbose_name='模块代码')),
                ('action', models.CharField(max_length=100, verbose_name='操作代码')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=150, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业务权限点',
                'verbose_name_plural': '业务权限点',
                'db_table': 'system_permission_item',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='client_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='客户类型备注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('internal', '内部员工'), ('external', '外部协作'), ('client_owner', '委托单位'), ('design_partner', '设计单位')], default='internal', max_length=20, verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='role',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='system_management.permissionitem', verbose_name='业务权限'),
        ),
    ]
