# Generated by Django 4.2.7 on 2025-11-08 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0002_permissionitem_user_client_type_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='system_management.role', verbose_name='系统角色'),
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('username', models.CharField(max_length=150, verbose_name='登录账号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('client_type', models.CharField(choices=[('internal', '内部员工'), ('external', '外部协作'), ('client_owner', '委托单位'), ('design_partner', '设计单位')], max_length=20, verbose_name='客户端类型')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='所属单位/公司')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='目标岗位')),
                ('extra_info', models.TextField(blank=True, verbose_name='备注信息')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('encoded_password', models.CharField(max_length=128, verbose_name='加密密码')),
                ('submitted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('processed_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('feedback', models.TextField(blank=True, verbose_name='审核意见')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_management.department', verbose_name='目标部门')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '注册申请',
                'verbose_name_plural': '注册申请',
                'db_table': 'system_registration_request',
                'ordering': ['-submitted_time'],
            },
        ),
    ]
