# Generated by Django 4.2.7 on 2025-11-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0003_user_roles_registrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='资料已完善'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='client_type',
            field=models.CharField(choices=[('service_provider', '服务单位'), ('client_owner', '委托单位'), ('design_partner', '设计单位')], max_length=20, verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('internal', '服务单位'), ('client_owner', '委托单位'), ('design_partner', '设计单位')], default='internal', max_length=20, verbose_name='用户类型'),
        ),
    ]
