# Generated by Django 4.2.7 on 2025-11-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0005_user_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('internal', '咨询单位'), ('client_owner', '委托单位'), ('design_partner', '设计单位'), ('control_partner', '过控单位')], default='internal', max_length=20, verbose_name='用户类型'),
        ),
    ]
