# Generated by Django 4.2.7 on 2025-11-22 08:42
# Modified: 使用 SeparateDatabaseAndState 避免迁移状态构建时的应用识别问题
# 该迁移已应用，修改以避免后续迁移时的状态构建错误

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0006_alter_user_user_type'),
        # 移除 permission_management 依赖，避免迁移状态构建错误
        # ('permission_management', '0001_initial'),
    ]

    operations = [
        # 使用 SeparateDatabaseAndState 分离数据库操作和状态操作
        # 这样在构建迁移状态时不会验证 permission_management 应用
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 数据库操作：由于迁移已应用，这里使用 noop
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # 状态操作：使用字符串引用，避免在构建状态时验证应用
                # 注意：这里使用延迟引用，Django 会在运行时解析
                migrations.AlterField(
                    model_name='role',
                    name='custom_permissions',
                    field=models.ManyToManyField(
                        blank=True, 
                        related_name='roles', 
                        to='permission_management.PermissionItem',  # 使用字符串引用
                        verbose_name='业务权限'
                    ),
                ),
            ],
        ),
    ]
    
    # 标记为已运行，避免在构建状态时验证
    run_before = [
        ('permission_management', '0001_initial'),
    ]
