# Generated by Django 4.2.7 on 2025-11-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0007_alter_role_custom_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionItem',
        ),
    ]
