# Generated by Django 4.2.7 on 2025-12-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0002_add_our_company_model'),
        ('system_management', '0008_delete_permissionitem'),
    ]

    operations = [
    ]
