# Generated by Django 4.2.7 on 2026-01-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0011_add_system_feedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemfeedback',
            new_name='system_feed_status_5259c5_idx',
            old_name='system_fee_status_8a3f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='systemfeedback',
            new_name='system_feed_submitt_7050ec_idx',
            old_name='system_fee_submitt_9c4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='systemfeedback',
            new_name='system_feed_feedbac_f41bcc_idx',
            old_name='system_fee_feedbac_7b8d9e_idx',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
    ]
