# Generated by Django 4.2.7 on 2025-11-21 03:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_management', '0006_alter_user_user_type'),
        ('project_center', '0018_add_project_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='科目编码')),
                ('name', models.CharField(max_length=100, verbose_name='科目名称')),
                ('subject_type', models.CharField(choices=[('asset', '资产'), ('liability', '负债'), ('equity', '所有者权益'), ('revenue', '收入'), ('expense', '费用'), ('cost', '成本')], max_length=20, verbose_name='科目类型')),
                ('direction', models.CharField(choices=[('debit', '借方'), ('credit', '贷方')], max_length=10, verbose_name='余额方向')),
                ('level', models.IntegerField(default=1, verbose_name='科目级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_subjects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='financial_management.accountsubject', verbose_name='上级科目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
                'db_table': 'financial_account_subject',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='凭证字号')),
                ('voucher_date', models.DateField(verbose_name='凭证日期')),
                ('attachment_count', models.IntegerField(default=0, verbose_name='附件数')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='借方合计')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='贷方合计')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审核'), ('posted', '已过账'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='状态')),
                ('reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('posted_time', models.DateTimeField(blank=True, null=True, verbose_name='过账时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='过账人')),
                ('preparer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='制单人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '记账凭证',
                'verbose_name_plural': '记账凭证',
                'db_table': 'financial_voucher',
                'ordering': ['-voucher_date', '-voucher_number'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(verbose_name='会计年度')),
                ('period_month', models.IntegerField(verbose_name='会计期间')),
                ('period_date', models.DateField(verbose_name='日期')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='期初余额')),
                ('period_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='本期借方')),
                ('period_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='本期贷方')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='期末余额')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('account_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='financial_management.accountsubject', verbose_name='会计科目')),
            ],
            options={
                'verbose_name': '总账',
                'verbose_name_plural': '总账',
                'db_table': 'financial_ledger',
                'ordering': ['account_subject', 'period_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='发票号码')),
                ('invoice_code', models.CharField(max_length=50, verbose_name='发票代码')),
                ('invoice_type', models.CharField(choices=[('incoming', '进项发票'), ('outgoing', '销项发票')], max_length=20, verbose_name='发票类型')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='发票金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='税额')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='价税合计')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='客户名称')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='供应商名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('issued', '已开具'), ('verified', '已认证'), ('cancelled', '已作废')], default='draft', max_length=20, verbose_name='状态')),
                ('verified_time', models.DateTimeField(blank=True, null=True, verbose_name='认证时间')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='发票附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL, verbose_name='认证人')),
            ],
            options={
                'verbose_name': '发票管理',
                'verbose_name_plural': '发票管理',
                'db_table': 'financial_invoice',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='FundFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_number', models.CharField(max_length=50, unique=True, verbose_name='流水号')),
                ('flow_date', models.DateField(verbose_name='发生日期')),
                ('flow_type', models.CharField(choices=[('income', '收入'), ('expense', '支出'), ('transfer', '转账')], max_length=20, verbose_name='流水类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('account_name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('counterparty', models.CharField(blank=True, max_length=200, verbose_name='对方单位')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fund_flows', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_flows', to='project_center.project', verbose_name='关联项目')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_flows', to='financial_management.voucher', verbose_name='关联凭证')),
            ],
            options={
                'verbose_name': '资金流水',
                'verbose_name_plural': '资金流水',
                'db_table': 'financial_fund_flow',
                'ordering': ['-flow_date', '-flow_number'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_number', models.CharField(max_length=50, unique=True, verbose_name='预算编号')),
                ('name', models.CharField(max_length=200, verbose_name='预算名称')),
                ('budget_year', models.IntegerField(verbose_name='预算年度')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='预算金额')),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已用金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='剩余金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('executing', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('account_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='financial_management.accountsubject', verbose_name='预算科目')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='system_management.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '预算管理',
                'verbose_name_plural': '预算管理',
                'db_table': 'financial_budget',
                'ordering': ['-budget_year', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='行号')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='借方金额')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='贷方金额')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('account_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_entries', to='financial_management.accountsubject', verbose_name='会计科目')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='financial_management.voucher', verbose_name='凭证')),
            ],
            options={
                'verbose_name': '凭证分录',
                'verbose_name_plural': '凭证分录',
                'db_table': 'financial_voucher_entry',
                'ordering': ['voucher', 'line_number'],
                'unique_together': {('voucher', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_number'], name='financial_v_voucher_81b864_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_date'], name='financial_v_voucher_390049_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='financial_v_status_410716_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['account_subject', 'period_date'], name='financial_l_account_6ed04f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['period_year', 'period_month'], name='financial_l_period__99e9c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('account_subject', 'period_year', 'period_month', 'period_date')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='financial_i_invoice_4a5a41_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='financial_i_invoice_6988aa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='financial_i_invoice_4b8983_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='financial_i_status_c36524_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_number', 'invoice_code')},
        ),
        migrations.AddIndex(
            model_name='fundflow',
            index=models.Index(fields=['flow_number'], name='financial_f_flow_nu_f3c0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='fundflow',
            index=models.Index(fields=['flow_date'], name='financial_f_flow_da_54f879_idx'),
        ),
        migrations.AddIndex(
            model_name='fundflow',
            index=models.Index(fields=['flow_type'], name='financial_f_flow_ty_c84e19_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_number'], name='financial_b_budget__658c79_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_year'], name='financial_b_budget__81a57b_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status'], name='financial_b_status_869491_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsubject',
            index=models.Index(fields=['code'], name='financial_a_code_17a0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsubject',
            index=models.Index(fields=['subject_type'], name='financial_a_subject_0469f6_idx'),
        ),
    ]
