# Generated by Django 4.2.7 on 2025-12-07 02:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0036_authorizationlettertemplate_and_more'),
        ('production_management', '0004_create_design_stage_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundflow',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_flows', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.CreateModel(
            name='ReceivableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='应收单号')),
                ('receivable_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应收金额')),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已收金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='未收金额')),
                ('receivable_date', models.DateField(verbose_name='应收日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('payment_terms', models.IntegerField(default=0, verbose_name='账期（天）')),
                ('status', models.CharField(choices=[('pending', '待收款'), ('partial', '部分收款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivables', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='customer_management.client', verbose_name='客户')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='production_management.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '应收账款',
                'verbose_name_plural': '应收账款',
                'db_table': 'financial_receivable',
                'ordering': ['-receivable_date', '-account_number'],
                'indexes': [models.Index(fields=['account_number'], name='financial_r_account_23c9f5_idx'), models.Index(fields=['receivable_date'], name='financial_r_receiva_8a6fd7_idx'), models.Index(fields=['status'], name='financial_r_status_dd24e6_idx'), models.Index(fields=['due_date'], name='financial_r_due_dat_8211ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='应付单号')),
                ('supplier', models.CharField(max_length=200, verbose_name='供应商')),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应付金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已付金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='未付金额')),
                ('payable_date', models.DateField(verbose_name='应付日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('payment_terms', models.IntegerField(default=0, verbose_name='账期（天）')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('partial', '部分付款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payables', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='production_management.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '应付账款',
                'verbose_name_plural': '应付账款',
                'db_table': 'financial_payable',
                'ordering': ['-payable_date', '-account_number'],
                'indexes': [models.Index(fields=['account_number'], name='financial_p_account_96bdc4_idx'), models.Index(fields=['payable_date'], name='financial_p_payable_69e2e3_idx'), models.Index(fields=['status'], name='financial_p_status_f2ab0c_idx'), models.Index(fields=['due_date'], name='financial_p_due_dat_da0616_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='报表编号')),
                ('report_type', models.CharField(choices=[('balance_sheet', '资产负债表'), ('income_statement', '利润表'), ('cash_flow', '现金流量表')], max_length=20, verbose_name='报表类型')),
                ('period_year', models.IntegerField(verbose_name='会计年度')),
                ('period_month', models.IntegerField(blank=True, null=True, verbose_name='会计期间')),
                ('report_date', models.DateField(verbose_name='报表日期')),
                ('report_data', models.JSONField(default=dict, verbose_name='报表数据')),
                ('generated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': '财务报表',
                'verbose_name_plural': '财务报表',
                'db_table': 'financial_report',
                'ordering': ['-report_date', '-generated_time'],
                'indexes': [models.Index(fields=['report_number'], name='financial_r_report__4691dd_idx'), models.Index(fields=['report_type'], name='financial_r_report__bc6257_idx'), models.Index(fields=['period_year', 'period_month'], name='financial_r_period__c7af95_idx')],
            },
        ),
    ]
