# Generated by Django 4.2.7 on 2025-11-14 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0012_project_flow_deadline_project_flow_payload_and_more'),
        ('customer_success', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='合同日期')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='business_contracts/%Y/%m/', verbose_name='合同附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_contract', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '商务合同',
                'verbose_name_plural': '商务合同',
                'db_table': 'business_contract',
            },
        ),
        migrations.CreateModel(
            name='BusinessPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100, verbose_name='回款阶段')),
                ('phase_description', models.TextField(blank=True, verbose_name='阶段描述')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划金额')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际金额')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('pending', '待回款'), ('partial', '部分回款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_condition', models.CharField(blank=True, max_length=100, verbose_name='触发条件')),
                ('condition_detail', models.CharField(blank=True, max_length=200, verbose_name='付款条件详情')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='customer_success.businesscontract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '商务回款计划',
                'verbose_name_plural': '商务回款计划',
                'db_table': 'business_payment_plan',
                'ordering': ['planned_date'],
            },
        ),
    ]
