# Generated by Django 4.2.7 on 2025-11-20 13:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_management', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True, verbose_name='员工编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('id_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='职称')),
                ('entry_date', models.DateField(verbose_name='入职日期')),
                ('status', models.CharField(choices=[('active', '在职'), ('on_leave', '请假'), ('suspended', '停职'), ('resigned', '离职')], default='active', max_length=20, verbose_name='状态')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='住址')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee_avatars/', verbose_name='头像')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_resumes/', verbose_name='简历')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='system_management.department', verbose_name='部门')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='系统账号')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
                'db_table': 'personnel_employee',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_number', models.CharField(max_length=100, unique=True, verbose_name='培训编号')),
                ('title', models.CharField(max_length=200, verbose_name='培训标题')),
                ('description', models.TextField(blank=True, verbose_name='培训描述')),
                ('trainer', models.CharField(blank=True, max_length=100, verbose_name='培训讲师')),
                ('training_date', models.DateField(blank=True, null=True, verbose_name='培训日期')),
                ('training_location', models.CharField(blank=True, max_length=200, verbose_name='培训地点')),
                ('duration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='培训时长（小时）')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('ongoing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
                'db_table': 'personnel_training',
                'ordering': ['-training_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.DateField(verbose_name='薪资月份')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='绩效奖金')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='加班费')),
                ('allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='津贴补贴')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应发金额')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='社保扣款')),
                ('housing_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='公积金扣款')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='个人所得税')),
                ('other_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='其他扣款')),
                ('total_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='扣款合计')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实发金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salaries', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='personnel_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '薪资记录',
                'verbose_name_plural': '薪资记录',
                'db_table': 'personnel_salary',
                'ordering': ['-salary_month'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_number', models.CharField(max_length=100, unique=True, verbose_name='考核编号')),
                ('period_type', models.CharField(choices=[('monthly', '月度'), ('quarterly', '季度'), ('semi_annual', '半年度'), ('annual', '年度')], max_length=20, verbose_name='考核周期')),
                ('period_year', models.IntegerField(verbose_name='考核年度')),
                ('period_quarter', models.IntegerField(blank=True, null=True, verbose_name='考核季度')),
                ('period_month', models.IntegerField(blank=True, null=True, verbose_name='考核月份')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总分')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='考核等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('self_assessment', '自评中'), ('manager_review', '上级评价中'), ('hr_review', 'HR审核中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('self_assessment', models.TextField(blank=True, verbose_name='自评')),
                ('manager_comment', models.TextField(blank=True, verbose_name='上级评价')),
                ('hr_comment', models.TextField(blank=True, verbose_name='HR评价')),
                ('reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='评价时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performances', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='personnel_management.employee', verbose_name='员工')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performances', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '绩效考核',
                'verbose_name_plural': '绩效考核',
                'db_table': 'personnel_performance',
                'ordering': ['-period_year', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_number', models.CharField(max_length=100, unique=True, verbose_name='请假单号')),
                ('leave_type', models.CharField(choices=[('annual', '年假'), ('sick', '病假'), ('personal', '事假'), ('marriage', '婚假'), ('maternity', '产假'), ('paternity', '陪产假'), ('bereavement', '丧假'), ('other', '其他')], max_length=20, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假事由')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='personnel_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'personnel_leave',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='合同编号')),
                ('contract_type', models.CharField(choices=[('fixed_term', '固定期限'), ('open_term', '无固定期限'), ('project_based', '以完成一定工作任务为期限')], max_length=20, verbose_name='合同类型')),
                ('start_date', models.DateField(verbose_name='合同开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='合同结束日期')),
                ('probation_period', models.IntegerField(default=0, verbose_name='试用期（月）')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('expired', '已到期'), ('terminated', '已终止')], default='draft', max_length=20, verbose_name='状态')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='labor_contracts/', verbose_name='合同文件')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='终止日期')),
                ('termination_reason', models.TextField(blank=True, verbose_name='终止原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labor_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='personnel_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '劳动合同',
                'verbose_name_plural': '劳动合同',
                'db_table': 'personnel_labor_contract',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='考勤日期')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='上班时间')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='下班时间')),
                ('attendance_type', models.CharField(choices=[('check_in', '上班打卡'), ('check_out', '下班打卡'), ('late', '迟到'), ('early_leave', '早退'), ('absent', '缺勤'), ('overtime', '加班')], default='check_in', max_length=20, verbose_name='考勤类型')),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='工作时长（小时）')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='加班时长（小时）')),
                ('is_late', models.BooleanField(default=False, verbose_name='是否迟到')),
                ('is_early_leave', models.BooleanField(default=False, verbose_name='是否早退')),
                ('is_absent', models.BooleanField(default=False, verbose_name='是否缺勤')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='personnel_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'personnel_attendance',
                'ordering': ['-attendance_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='培训成绩')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training_certificates/', verbose_name='证书')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='参与时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='personnel_management.employee', verbose_name='员工')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='personnel_management.training', verbose_name='培训')),
            ],
            options={
                'verbose_name': '培训参与人员',
                'verbose_name_plural': '培训参与人员',
                'db_table': 'personnel_training_participant',
                'unique_together': {('training', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['training_number'], name='personnel_t_trainin_957d55_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['status'], name='personnel_t_status_187e66_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'salary_month'], name='personnel_s_employe_3900f1_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['salary_month'], name='personnel_s_salary__2df21a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'salary_month')},
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['performance_number'], name='personnel_p_perform_f0503a_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['employee', 'period_year'], name='personnel_p_employe_4db5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['status'], name='personnel_p_status_c6311d_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['leave_number'], name='personnel_l_leave_n_a7d4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='personnel_l_employe_137f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='personnel_l_start_d_d4a072_idx'),
        ),
        migrations.AddIndex(
            model_name='laborcontract',
            index=models.Index(fields=['contract_number'], name='personnel_l_contrac_236a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='laborcontract',
            index=models.Index(fields=['employee', 'status'], name='personnel_l_employe_1959ab_idx'),
        ),
        migrations.AddIndex(
            model_name='laborcontract',
            index=models.Index(fields=['start_date', 'end_date'], name='personnel_l_start_d_1c195f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='personnel_e_employe_9b1503_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='personnel_e_status_6657b3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='personnel_e_departm_eb2776_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'attendance_date'], name='personnel_a_employe_28de23_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='personnel_a_attenda_2417c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'attendance_date')},
        ),
    ]
