# Generated by Django 4.2.7 on 2025-11-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outputvaluerecord',
            new_name='settlement__project_3ae14d_idx',
            old_name='settlement__project_c8d1e8_idx',
        ),
        migrations.RenameIndex(
            model_name='outputvaluerecord',
            new_name='settlement__respons_17c0d0_idx',
            old_name='settlement__respons_fb41b4_idx',
        ),
        migrations.RenameIndex(
            model_name='outputvaluerecord',
            new_name='settlement__calcula_0aecb0_idx',
            old_name='settlement__calcula_3f6c51_idx',
        ),
    ]
