# Generated by Django 4.2.7 on 2025-11-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0001_initial'),
        ('project_center', '0018_add_project_tasks'),
        ('settlement_center', '0002_rename_settlement__project_c8d1e8_idx_settlement__project_3ae14d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(max_length=100, unique=True, verbose_name='结算单号')),
                ('settlement_type', models.CharField(choices=[('final', '最终结算'), ('interim', '阶段结算'), ('change', '变更结算'), ('other', '其他')], default='final', max_length=20, verbose_name='结算类型')),
                ('settlement_date', models.DateField(verbose_name='结算日期')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='结算金额')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, help_text='相对于合同金额的增减', max_digits=12, verbose_name='变更金额')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6.0, help_text='默认6%', max_digits=5, verbose_name='税率(%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税额')),
                ('settlement_amount_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='结算金额（含税）')),
                ('total_output_value', models.DecimalField(decimal_places=2, default=0, help_text='项目累计计算的产值', max_digits=12, verbose_name='累计产值')),
                ('confirmed_output_value', models.DecimalField(decimal_places=2, default=0, help_text='本次结算确认的产值', max_digits=12, verbose_name='确认产值')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('finance_review', '财务审核中'), ('manager_approve', '部门经理审批中'), ('general_manager_approve', '总经理审批中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态')),
                ('submitted_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('finance_reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='财务审核时间')),
                ('finance_review_comment', models.TextField(blank=True, verbose_name='财务审核意见')),
                ('manager_reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='部门经理审核时间')),
                ('manager_review_comment', models.TextField(blank=True, verbose_name='部门经理审核意见')),
                ('general_manager_reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='总经理审核时间')),
                ('general_manager_review_comment', models.TextField(blank=True, verbose_name='总经理审核意见')),
                ('confirmed_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('settlement_file', models.FileField(blank=True, null=True, upload_to='settlements/%Y/%m/', verbose_name='结算文件')),
                ('description', models.TextField(blank=True, verbose_name='结算说明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_settlements', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settlements', to='production_management.businesscontract', verbose_name='关联合同')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('finance_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_settlements', to=settings.AUTH_USER_MODEL, verbose_name='财务审核人')),
                ('general_manager_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_reviewed_settlements', to=settings.AUTH_USER_MODEL, verbose_name='总经理')),
                ('manager_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviewed_settlements', to=settings.AUTH_USER_MODEL, verbose_name='部门经理')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='project_center.project', verbose_name='关联项目')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_settlements', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '项目结算',
                'verbose_name_plural': '项目结算',
                'db_table': 'settlement_project_settlement',
                'ordering': ['-settlement_date', '-created_time'],
                'indexes': [models.Index(fields=['settlement_number'], name='settlement__settlem_c4da11_idx'), models.Index(fields=['project', 'status'], name='settlement__project_54b8a4_idx'), models.Index(fields=['settlement_date'], name='settlement__settlem_b628d1_idx'), models.Index(fields=['status'], name='settlement__status_07fc8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(max_length=100, unique=True, verbose_name='结算单号')),
                ('settlement_date', models.DateField(verbose_name='结算日期')),
                ('settlement_batch', models.IntegerField(default=1, help_text='同一合同的第几次结算', verbose_name='结算批次')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('previous_settlement_amount', models.DecimalField(decimal_places=2, default=0, help_text='本次结算前已结算的金额', max_digits=12, verbose_name='已结算金额')),
                ('this_settlement_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本次结算金额')),
                ('total_settlement_amount', models.DecimalField(decimal_places=2, help_text='本次结算后的累计结算金额', max_digits=12, verbose_name='累计结算金额')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='税率(%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税额')),
                ('settlement_amount_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='结算金额（含税）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('confirmed_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('settlement_file', models.FileField(blank=True, null=True, upload_to='contract_settlements/%Y/%m/', verbose_name='结算文件')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='发票号码')),
                ('description', models.TextField(blank=True, verbose_name='结算说明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_settlements', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_contract_settlements', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_settlements', to='production_management.businesscontract', verbose_name='关联合同')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_settlements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_contract_settlements', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '合同结算',
                'verbose_name_plural': '合同结算',
                'db_table': 'settlement_contract_settlement',
                'ordering': ['-settlement_date', '-settlement_batch'],
                'indexes': [models.Index(fields=['settlement_number'], name='settlement__settlem_a98ea7_idx'), models.Index(fields=['contract', 'status'], name='settlement__contrac_c87acd_idx'), models.Index(fields=['settlement_date'], name='settlement__settlem_6e5892_idx'), models.Index(fields=['contract', 'settlement_batch'], name='settlement__contrac_f43d35_idx')],
                'unique_together': {('contract', 'settlement_batch')},
            },
        ),
    ]
