# Generated by Django 4.2.7 on 2025-11-21 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_quality', '0004_opinion_closed_at_opinion_cycle_time_hours_and_more'),
        ('settlement_center', '0003_projectsettlement_contractsettlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettlement',
            name='finance_review_comment',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='finance_reviewed_time',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='finance_reviewer',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='general_manager_review_comment',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='general_manager_reviewed_time',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='general_manager_reviewer',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='manager_review_comment',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='manager_reviewed_time',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='manager_reviewer',
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='client_feedback_comment',
            field=models.TextField(blank=True, verbose_name='甲方反馈意见'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='client_feedback_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='甲方反馈时间'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='client_review_comment',
            field=models.TextField(blank=True, verbose_name='甲方初审意见'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='client_reviewed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='甲方初审时间'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='client_reviewer',
            field=models.CharField(blank=True, max_length=100, verbose_name='甲方初审人'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='reconciliation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_settlements', to=settings.AUTH_USER_MODEL, verbose_name='对账人'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='reconciliation_comment',
            field=models.TextField(blank=True, verbose_name='对账说明'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='reconciliation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='对账时间'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='所有明细项金额之和，自动计算', max_digits=12, verbose_name='结算金额'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='settlement_amount_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='结算金额（含税）'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('client_review', '甲方初审中'), ('client_feedback', '甲方反馈'), ('reconciliation', '对账中'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, verbose_name='明细项编号')),
                ('item_name', models.CharField(max_length=200, verbose_name='明细项名称')),
                ('professional_category', models.CharField(blank=True, max_length=100, verbose_name='专业分类')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='部位名称')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='工程量')),
                ('unit', models.CharField(max_length=30, verbose_name='计量单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='综合单价')),
                ('item_amount', models.DecimalField(decimal_places=2, help_text='工程量 × 综合单价', max_digits=12, verbose_name='明细项金额')),
                ('adjusted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='调整后工程量')),
                ('adjusted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='调整后单价')),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='调整后金额')),
                ('adjustment_reason', models.TextField(blank=True, verbose_name='调整原因')),
                ('adjusted_time', models.DateTimeField(blank=True, null=True, verbose_name='调整时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_settlement_items', to=settings.AUTH_USER_MODEL, verbose_name='调整人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlement_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opinion', models.ForeignKey(blank=True, help_text='从生产管理模块的意见生成', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='production_quality.opinion', verbose_name='关联意见')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlement_center.projectsettlement', verbose_name='关联结算单')),
            ],
            options={
                'verbose_name': '结算明细项',
                'verbose_name_plural': '结算明细项',
                'db_table': 'settlement_settlement_item',
                'ordering': ['settlement', 'order', 'created_time'],
                'indexes': [models.Index(fields=['settlement', 'order'], name='settlement__settlem_77c4e6_idx'), models.Index(fields=['opinion'], name='settlement__opinion_555a3a_idx')],
            },
        ),
    ]
