# Generated by Django 4.2.7 on 2025-11-21 09:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        # ('production_quality', '0004_opinion_closed_at_opinion_cycle_time_hours_and_more'),  # 已删除production_quality模块
        ('production_management', '0001_initial'),
        ('project_center', '0018_add_project_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlement_center', '0004_remove_projectsettlement_finance_review_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_saving_amount', models.DecimalField(decimal_places=2, default=0, help_text='该费率适用的最小节省金额', max_digits=12, verbose_name='节省金额下限')),
                ('max_saving_amount', models.DecimalField(blank=True, decimal_places=2, help_text='该费率适用的最大节省金额（为空表示无上限）', max_digits=12, null=True, verbose_name='节省金额上限')),
                ('service_rate', models.DecimalField(decimal_places=4, help_text='服务费率，例如：0.15 表示 15%', max_digits=5, verbose_name='服务费率')),
                ('rate_description', models.TextField(blank=True, verbose_name='费率说明')),
                ('order', models.IntegerField(default=0, help_text='用于确定费率匹配优先级', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务费率表',
                'verbose_name_plural': '服务费率表',
                'db_table': 'settlement_service_fee_rate',
                'ordering': ['contract', 'order', 'min_saving_amount'],
            },
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='change_amount',
        ),
        migrations.RemoveField(
            model_name='projectsettlement',
            name='settlement_amount',
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='base_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='从合同模块同步的固定服务费（如有）', max_digits=12, verbose_name='基础服务费'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='fee_base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='等于审核后节省总额，只读', max_digits=14, verbose_name='取费基数'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='original_total_saving',
            field=models.DecimalField(decimal_places=2, default=0, help_text='自动计算所有Opinion原始节省金额总和', max_digits=14, verbose_name='原始节省总额'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='reviewed_total_saving',
            field=models.DecimalField(decimal_places=2, default=0, help_text='自动计算所有已确认意见的调整后节省金额总和', max_digits=14, verbose_name='审核后节省总额'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='saving_adjustment_diff',
            field=models.DecimalField(decimal_places=2, default=0, help_text='自动计算：审核后节省总额 - 原始节省总额', max_digits=14, verbose_name='调整差额'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='自动计算：取费基数 × 服务费率', max_digits=14, verbose_name='服务费金额'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='service_fee_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='从合同费率表自动匹配', max_digits=5, null=True, verbose_name='服务费率'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='settlement_period_end',
            field=models.DateField(blank=True, help_text='新增时必填，历史数据可为空', null=True, verbose_name='结算周期结束日期'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='settlement_period_start',
            field=models.DateField(blank=True, help_text='新增时必填，历史数据可为空', null=True, verbose_name='结算周期开始日期'),
        ),
        migrations.AddField(
            model_name='projectsettlement',
            name='total_settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='自动计算：基础服务费 + 服务费金额', max_digits=14, verbose_name='结算总金额'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='adjusted_saving_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='造价工程师手动调整', max_digits=14, null=True, verbose_name='调整后节省金额'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='opinion_number',
            field=models.CharField(blank=True, help_text='从Opinion自动带出，创建时自动填充', max_length=50, verbose_name='意见编号'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='opinion_title',
            field=models.CharField(blank=True, help_text='从Opinion自动带出', max_length=200, verbose_name='意见标题'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='original_saving_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='从Opinion.saving_amount自动带出', max_digits=14, verbose_name='原始节省金额'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='驳回原因'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已确认'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_settlement_items', to=settings.AUTH_USER_MODEL, verbose_name='审核造价工程师'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='reviewed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='用于参考', max_digits=12, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='project',
            field=models.ForeignKey(help_text='仅显示状态为"已完工"的项目', on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='project_center.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='settlement_amount_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='结算总金额 + 税额', max_digits=14, verbose_name='结算总金额（含税）'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='settlement_date',
            field=models.DateField(help_text='默认当前日期', verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='settlement_number',
            field=models.CharField(help_text='格式：VIH-JS-{项目编号}-{序列号}', max_length=100, unique=True, verbose_name='结算单号'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='settlement_type',
            field=models.CharField(choices=[('interim', '阶段结算'), ('final', '最终结算')], default='interim', max_length=20, verbose_name='结算类型'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='默认6%，用于税额计算', max_digits=5, verbose_name='税率(%)'),
        ),
        migrations.AlterUniqueTogether(
            name='settlementitem',
            unique_together={('settlement', 'opinion')},
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['review_status'], name='settlement__review__a86d0d_idx'),
        ),
        migrations.AddField(
            model_name='servicefeerate',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='如果为空，则为全局费率表', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_rates', to='production_management.businesscontract', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='servicefeerate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_fee_rates', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='adjusted_amount',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='adjusted_quantity',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='adjusted_time',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='adjusted_unit_price',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='item_amount',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='settlementitem',
            name='unit_price',
        ),
        migrations.AddIndex(
            model_name='servicefeerate',
            index=models.Index(fields=['contract', 'is_active', 'order'], name='settlement__contrac_67e504_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeerate',
            index=models.Index(fields=['min_saving_amount', 'max_saving_amount'], name='settlement__min_sav_aad638_idx'),
        ),
    ]
