# Generated by Django 4.2.7 on 2025-12-07 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0004_create_design_stage_model'),
        ('settlement_center', '0005_servicefeerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputvaluerecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_value_records_center', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='projectsettlement',
            name='project',
            field=models.ForeignKey(help_text='仅显示状态为"已完工"的项目', on_delete=django.db.models.deletion.PROTECT, related_name='settlements_center', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_plan_id', models.IntegerField(verbose_name='回款计划ID')),
                ('payment_plan_type', models.CharField(choices=[('project', '项目回款计划'), ('business', '商务回款计划')], max_length=50, verbose_name='回款计划类型')),
                ('payment_number', models.CharField(max_length=100, unique=True, verbose_name='回款单号')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='回款金额')),
                ('payment_date', models.DateField(verbose_name='回款日期')),
                ('payment_method', models.CharField(choices=[('bank_transfer', '银行转账'), ('cash', '现金'), ('check', '支票'), ('acceptance', '承兑汇票'), ('other', '其他')], max_length=20, verbose_name='回款方式')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='发票号码')),
                ('bank_account', models.CharField(blank=True, max_length=200, verbose_name='收款账户')),
                ('receipt_voucher', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='收款凭证')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('confirmed_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '回款记录',
                'verbose_name_plural': '回款记录',
                'db_table': 'settlement_payment_record',
                'ordering': ['-payment_date', '-created_time'],
                'indexes': [models.Index(fields=['payment_plan_type', 'payment_plan_id'], name='settlement__payment_71e12c_idx'), models.Index(fields=['payment_number'], name='settlement__payment_1eaf4d_idx'), models.Index(fields=['payment_date'], name='settlement__payment_c62518_idx'), models.Index(fields=['status'], name='settlement__status_76e0b5_idx')],
            },
        ),
    ]
