# Generated by Django 4.2.7 on 2025-12-11 13:42

from django.db import migrations


def rename_indexes_if_exist(apps, schema_editor):
    """只在索引存在时重命名索引"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 检查并重命名索引
        index_renames = [
            ('servicefeejumppointrate', 'settlement__scheme_jump_idx', 'settlement__scheme__43dae4_idx'),
            ('servicefeesegmentedrate', 'settlement__scheme_idx', 'settlement__scheme__73655b_idx'),
            ('servicefeesettlementscheme', 'settlement__contract_idx', 'settlement__contrac_dd6c35_idx'),
            ('servicefeesettlementscheme', 'settlement__project_idx', 'settlement__project_eccc3a_idx'),
            ('servicefeesettlementscheme', 'settlement__method_idx', 'settlement__settlem_3ae77f_idx'),
            ('servicefeesettlementscheme', 'settlement__default_idx', 'settlement__is_defa_776b76_idx'),
            ('servicefeeunitcapdetail', 'settlement__scheme_unit_idx', 'settlement__scheme__1c5edc_idx'),
        ]
        
        for table_name, old_name, new_name in index_renames:
            # 检查索引是否存在
            cursor.execute("""
                SELECT COUNT(*) 
                FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [f'settlement_center_{table_name}', old_name])
            
            if cursor.fetchone()[0] > 0:
                # 索引存在，执行重命名
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def reverse_rename_indexes(apps, schema_editor):
    """反向操作：恢复索引名称"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        index_renames = [
            ('servicefeejumppointrate', 'settlement__scheme__43dae4_idx', 'settlement__scheme_jump_idx'),
            ('servicefeesegmentedrate', 'settlement__scheme__73655b_idx', 'settlement__scheme_idx'),
            ('servicefeesettlementscheme', 'settlement__contrac_dd6c35_idx', 'settlement__contract_idx'),
            ('servicefeesettlementscheme', 'settlement__project_eccc3a_idx', 'settlement__project_idx'),
            ('servicefeesettlementscheme', 'settlement__settlem_3ae77f_idx', 'settlement__method_idx'),
            ('servicefeesettlementscheme', 'settlement__is_defa_776b76_idx', 'settlement__default_idx'),
            ('servicefeeunitcapdetail', 'settlement__scheme__1c5edc_idx', 'settlement__scheme_unit_idx'),
        ]
        
        for table_name, new_name, old_name in index_renames:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [f'settlement_center_{table_name}', new_name])
            
            if cursor.fetchone()[0] > 0:
                cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0008_add_service_fee_scheme_to_project_settlement'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
    ]
