# Generated by Django 4.2.7 on 2025-12-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0010_rename_settlement__scheme_jump_idx_settlement__scheme__43dae4_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicefeejumppointrate',
            new_name='settlement__scheme__43dae4_idx',
            old_name='settlement__scheme_jump_idx',
        ),
        migrations.RenameIndex(
            model_name='servicefeesegmentedrate',
            new_name='settlement__scheme__73655b_idx',
            old_name='settlement__scheme_idx',
        ),
        migrations.RenameIndex(
            model_name='servicefeesettlementscheme',
            new_name='settlement__contrac_dd6c35_idx',
            old_name='settlement__contract_idx',
        ),
        migrations.RenameIndex(
            model_name='servicefeesettlementscheme',
            new_name='settlement__project_eccc3a_idx',
            old_name='settlement__project_idx',
        ),
        migrations.RenameIndex(
            model_name='servicefeesettlementscheme',
            new_name='settlement__settlem_3ae77f_idx',
            old_name='settlement__method_idx',
        ),
        migrations.RenameIndex(
            model_name='servicefeesettlementscheme',
            new_name='settlement__is_defa_776b76_idx',
            old_name='settlement__default_idx',
        ),
        migrations.RenameIndex(
            model_name='servicefeeunitcapdetail',
            new_name='settlement__scheme__1c5edc_idx',
            old_name='settlement__scheme_unit_idx',
        ),
    ]
