# Generated by Django 4.2.7 on 2025-12-13 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0011_rename_settlement__scheme_jump_idx_settlement__scheme__43dae4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='结算方式名称')),
                ('code', models.CharField(choices=[('fixed_total', '总价包干'), ('fixed_unit', '单价包干'), ('segmented_commission', '分段递增提成'), ('jump_point_commission', '跳点提成'), ('cumulative_commission', '累计提成')], help_text='系统识别代码，不可重复', max_length=50, unique=True, verbose_name='结算方式代码')),
                ('description', models.TextField(blank=True, verbose_name='描述说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '结算方式',
                'verbose_name_plural': '结算方式',
                'db_table': 'settlement_settlement_method',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='settlement__code_f627cd_idx'), models.Index(fields=['is_active', 'sort_order'], name='settlement__is_acti_0cff7b_idx')],
            },
        ),
    ]
