# Generated by Django 4.2.7 on 2025-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0012_add_settlement_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeesettlementscheme',
            name='area_scale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='面积规模（平方米），从服务内容移到结算方式', max_digits=15, null=True, verbose_name='面积规模'),
        ),
        migrations.AddField(
            model_name='servicefeesettlementscheme',
            name='cap_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='封顶费金额（元）', max_digits=14, null=True, verbose_name='封顶费'),
        ),
        migrations.AddField(
            model_name='servicefeesettlementscheme',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='服务费金额（元）', max_digits=14, null=True, verbose_name='服务费'),
        ),
        migrations.AlterField(
            model_name='servicefeesettlementscheme',
            name='cap_type',
            field=models.CharField(blank=True, choices=[('total_cap', '总价封顶'), ('unit_cap', '单价封顶'), ('no_cap', '不设置封顶')], help_text='总价封顶或单价封顶（已废弃，使用cap_fee）', max_length=20, null=True, verbose_name='封顶费类型'),
        ),
        migrations.AlterField(
            model_name='servicefeesettlementscheme',
            name='total_cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='封顶费为总价封顶时的金额（已废弃，使用cap_fee）', max_digits=14, null=True, verbose_name='总价封顶金额'),
        ),
        migrations.AlterField(
            model_name='settlementmethod',
            name='code',
            field=models.CharField(choices=[('fixed_total', '总价包干'), ('fixed_unit', '单价包干'), ('segmented_commission', '分段递增提成'), ('segmented_commission_simple', '分段提成'), ('jump_point_commission', '跳点提成'), ('cumulative_commission', '累计提成')], help_text='系统识别代码，不可重复', max_length=50, unique=True, verbose_name='结算方式代码'),
        ),
    ]
