# Generated by Django 4.2.7 on 2025-12-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0014_seed_result_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfiletype',
            name='code',
            field=models.CharField(help_text='唯一标识，如：pre_optimization_disc_application（同一服务类别内唯一）', max_length=100, verbose_name='文件类型代码'),
        ),
    ]
