# Generated by Django 4.2.7 on 2025-12-09 10:20

from django.db import migrations


def fix_missing_file_types(apps, schema_editor):
    """补充缺失的文件类型数据"""
    ResultFileType = apps.get_model('production_management', 'ResultFileType')
    
    # 过程优化缺失的文件类型
    process_optimization_missing = [
        ('review_opinion', '核图意见书', 4),
        ('post_optimization_disc_application', '优化后资料刻盘申请', 5),
        ('post_optimization_materials', '优化后资料', 6),
        ('result_confirmation', '成果确认函', 7),
    ]
    
    # 全过程咨询缺失的文件类型
    full_process_consulting_missing = [
        ('review_opinion', '核图意见书', 5),
        ('result_confirmation', '成果确认函', 7),
    ]
    
    # 创建过程优化缺失的文件类型
    for code, name, order in process_optimization_missing:
        ResultFileType.objects.get_or_create(
            service_category='process_optimization',
            code=code,
            defaults={
                'name': name,
                'order': order,
                'is_active': True,
            }
        )
    
    # 创建全过程咨询缺失的文件类型
    for code, name, order in full_process_consulting_missing:
        ResultFileType.objects.get_or_create(
            service_category='full_process_consulting',
            code=code,
            defaults={
                'name': name,
                'order': order,
                'is_active': True,
            }
        )


def reverse_fix_missing_file_types(apps, schema_editor):
    """回滚：删除补充的文件类型"""
    ResultFileType = apps.get_model('production_management', 'ResultFileType')
    
    # 删除过程优化补充的文件类型
    process_codes = ['review_opinion', 'post_optimization_disc_application', 
                     'post_optimization_materials', 'result_confirmation']
    ResultFileType.objects.filter(
        service_category='process_optimization',
        code__in=process_codes
    ).delete()
    
    # 删除全过程咨询补充的文件类型
    consulting_codes = ['review_opinion', 'result_confirmation']
    ResultFileType.objects.filter(
        service_category='full_process_consulting',
        code__in=consulting_codes
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0015_remove_code_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(fix_missing_file_types, reverse_fix_missing_file_types),
    ]
