# Generated by Django 4.2.7 on 2025-12-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0019_add_contract_service_content'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractservicecontent',
            new_name='contract_se_contrac_35b26d_idx',
            old_name='contract_se_contract_idx',
        ),
    ]
