# Generated by Django 4.2.7 on 2025-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0021_add_contract_types_strategic_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontract',
            name='contract_type',
            field=models.CharField(choices=[('strategic', '战略合同'), ('framework', '框架合同'), ('project', '项目合同'), ('intent', '意向合同'), ('supplement', '补充协议'), ('change', '变更协议'), ('termination', '终止协议'), ('other', '其他')], default='project', max_length=20, verbose_name='合同类型'),
        ),
    ]
