# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0022_alter_businesscontract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontract',
            name='structure_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('shear_wall', '剪力墙结构'),
                    ('frame', '框架结构'),
                    ('steel', '钢结构'),
                    ('other', '其他'),
                ],
                help_text='项目的结构形式，用于合同管理和维护',
                max_length=50,
                null=True,
                verbose_name='结构形式'
            ),
        ),
    ]

