# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0023_add_structure_type_to_business_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontract',
            name='design_unit_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('class_1', '一类设计院'),
                    ('class_2', '二类设计院'),
                    ('class_3', '三类设计院'),
                    ('class_4', '四类设计院'),
                ],
                help_text='设计单位的分类等级，用于合同管理和维护',
                max_length=20,
                null=True,
                verbose_name='设计单位分类'
            ),
        ),
    ]

