# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0024_add_design_unit_category_to_business_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='结构形式编码')),
                ('name', models.CharField(max_length=100, verbose_name='结构形式名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='结构形式描述')),
            ],
            options={
                'verbose_name': '结构形式',
                'verbose_name_plural': '结构形式',
                'db_table': 'production_management_structure_type',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DesignUnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '设计单位分类',
                'verbose_name_plural': '设计单位分类',
                'db_table': 'production_management_design_unit_category',
                'ordering': ['order', 'id'],
            },
        ),
    ]

