# Generated manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0025_add_structure_type_and_design_unit_category_models'),
    ]

    operations = [
        migrations.RunSQL(
            # 删除contract_party表
            sql="DROP TABLE IF EXISTS contract_party CASCADE;",
            reverse_sql="""
                -- 如果需要回滚，可以重新创建表（但通常不需要）
                CREATE TABLE IF NOT EXISTS contract_party (
                    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    party_type varchar(20) NOT NULL DEFAULT 'party_a',
                    party_name varchar(200) NOT NULL,
                    credit_code varchar(50) NOT NULL DEFAULT '',
                    legal_representative varchar(100) NOT NULL DEFAULT '',
                    party_contact varchar(100) NOT NULL DEFAULT '',
                    contact_phone varchar(20) NOT NULL DEFAULT '',
                    contact_email varchar(254) NOT NULL DEFAULT '',
                    address varchar(500) NOT NULL DEFAULT '',
                    "order" integer NOT NULL DEFAULT 0,
                    is_active boolean NOT NULL DEFAULT true,
                    created_time timestamp with time zone NOT NULL,
                    updated_time timestamp with time zone NOT NULL,
                    contract_id bigint NOT NULL
                );
            """
        ),
    ]

