-- Migration: 0027_create_contract_party_with_project_manager
-- 重新创建contract_party表，包含项目负责人字段

BEGIN;

-- Create table contract_party
CREATE TABLE IF NOT EXISTS "contract_party" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "party_type" varchar(20) NOT NULL DEFAULT 'party_a',
    "party_name" varchar(200) NOT NULL,
    "credit_code" varchar(50) NOT NULL DEFAULT '',
    "legal_representative" varchar(100) NOT NULL DEFAULT '',
    "project_manager" varchar(100) NOT NULL DEFAULT '',
    "party_contact" varchar(100) NOT NULL DEFAULT '',
    "contact_phone" varchar(20) NOT NULL DEFAULT '',
    "contact_email" varchar(254) NOT NULL DEFAULT '',
    "address" varchar(500) NOT NULL DEFAULT '',
    "order" integer NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_time" timestamp with time zone NOT NULL,
    "updated_time" timestamp with time zone NOT NULL,
    "contract_id" bigint NOT NULL
);

-- Add foreign key constraint
ALTER TABLE "contract_party" ADD CONSTRAINT "contract_party_contract_id_fk" 
    FOREIGN KEY ("contract_id") REFERENCES "business_contract" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- Create index
CREATE INDEX IF NOT EXISTS "contract_pa_contract_idx" ON "contract_party" ("contract_id", "is_active");

COMMENT ON COLUMN contract_party.party_type IS '单位类型：甲方/乙方/丙方/其他';
COMMENT ON COLUMN contract_party.party_name IS '单位名称';
COMMENT ON COLUMN contract_party.credit_code IS '统一社会信用代码';
COMMENT ON COLUMN contract_party.legal_representative IS '法定代表人';
COMMENT ON COLUMN contract_party.project_manager IS '项目负责人';
COMMENT ON COLUMN contract_party.party_contact IS '联系人';
COMMENT ON COLUMN contract_party.contact_phone IS '联系电话';
COMMENT ON COLUMN contract_party.contact_email IS '联系邮箱';
COMMENT ON COLUMN contract_party.address IS '办公地址';

COMMIT;

