# Generated by Django 4.2.7 on 2025-12-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0027_create_contract_party_with_project_manager'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractparty',
            new_name='contract_pa_contrac_c954c1_idx',
            old_name='contract_pa_contract_idx',
        ),
    ]
