# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0028_rename_contract_pa_contract_idx_contract_pa_contrac_c954c1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontract',
            name='service_type',
            field=models.CharField(
                blank=True,
                choices=[('result_optimization', '结果优化'), ('process_optimization', '过程优化')],
                help_text='服务类型调整（T1）：结果优化：1.0，过程优化：1.5',
                max_length=30,
                null=True,
                verbose_name='服务类型'
            ),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='project_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('residential', '住宅'),
                    ('complex', '综合体'),
                    ('industrial', '工业厂房'),
                    ('office', '写字楼'),
                    ('commercial', '商业'),
                    ('school', '学校'),
                    ('hospital', '医院'),
                    ('municipal', '市政'),
                    ('other', '其他')
                ],
                help_text='项目业态调整（T2）：住宅：1.0，综合体：1.2，工业厂房：1.10，写字楼=1.15，商业=1.3，学校=1.05，医院=1.25，市政=1.4，其他=1.0',
                max_length=30,
                null=True,
                verbose_name='项目业态'
            ),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='service_professions',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='服务专业调整（T3）：结构：0.32；构造：0.48，电气：0.14，给排水：0.06，其他专业每增加一个，调整系数增加0.1，但总系数不超过1.5',
                verbose_name='服务专业'
            ),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='drawing_stage',
            field=models.CharField(
                blank=True,
                choices=[
                    ('construction_unaudited', '施工图（未审图）'),
                    ('construction_audited', '施工图（已审图）'),
                    ('preliminary_scheme', '初步方案'),
                    ('detailed_scheme', '详细方案'),
                    ('preliminary_design', '初步设计'),
                    ('extended_preliminary', '扩初设计'),
                    ('construction_stage', '施工阶段'),
                    ('special_design', '专项设计')
                ],
                help_text='图纸阶段调整（T5）：施工图（未审图）：1.0，施工图（已审图）：0.6，初步方案：1.5，详细方案：1.4，初步设计：1.3，扩初设计：1.2，施工阶段：0.5，专项设计：1.0',
                max_length=30,
                null=True,
                verbose_name='图纸阶段'
            ),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='basement_area',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='用于计算地下面积占比调整（T6）',
                max_digits=12,
                null=True,
                verbose_name='地下室面积（㎡）'
            ),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='total_building_area',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='用于计算地下面积占比调整（T6）',
                max_digits=12,
                null=True,
                verbose_name='总建筑面积（㎡）'
            ),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='comprehensive_adjustment_coefficient',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='自动计算：T1*T2*T3*T4*T5*T6*T7，最大不超过2.0',
                max_digits=5,
                null=True,
                verbose_name='综合调整系数'
            ),
        ),
    ]

