# Generated by Django 6.0 on 2025-12-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0031_remove_contract_service_content'),
    ]

    operations = [
        migrations.RunSQL(
            # 只有当索引存在时才删除
            sql="DROP INDEX IF EXISTS contract_se_contrac_35b26d_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ComprehensiveAdjustmentCoefficient',
            fields=[
            ],
            options={
                'verbose_name': '综合调整系数',
                'verbose_name_plural': '综合调整系数',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production_management.businesscontract',),
        ),
        migrations.AlterField(
            model_name='businesscontract',
            name='project_number',
            field=models.CharField(blank=True, help_text='自动生成：YYYYMMDD-0000，可手动修改。项目编号须保持唯一性', max_length=50, null=True, unique=True, verbose_name='项目编号'),
        ),
        migrations.RunSQL(
            # 只有当表存在时才删除
            sql="DROP TABLE IF EXISTS contract_service_content_service_professions CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            # 只有当表存在时才删除主表
            sql="DROP TABLE IF EXISTS contract_service_content CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
