# Generated by Django 4.2.7 on 2025-12-24 06:56

from django.db import migrations


def safe_delete_contract_service_content(apps, schema_editor):
    """安全删除ContractServiceContent模型（如果表存在）"""
    with schema_editor.connection.cursor() as cursor:
        # 检查并删除关联表
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'contract_service_content_service_professions'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE IF EXISTS contract_service_content_service_professions CASCADE;")
        
        # 检查并删除主表
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'contract_service_content'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE IF EXISTS contract_service_content CASCADE;")


def reverse_safe_delete_contract_service_content(apps, schema_editor):
    """反向操作：不执行任何操作（因为表已被删除）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0032_remove_contractservicecontent_contract_se_contrac_35b26d_idx_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='projectdesignreply',
            index_together=set(),
        ),
        # 先安全删除数据库表
        migrations.RunPython(
            safe_delete_contract_service_content,
            reverse_safe_delete_contract_service_content,
        ),
        # 然后从Django状态中删除模型（不操作数据库）
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='ContractServiceContent',
                ),
            ],
        ),
    ]
