# Generated by Django 4.2.7 on 2026-01-02 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0009_merge_20251208_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0033_alter_projectdesignreply_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to='system_management.department', verbose_name='负责部门'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
