# Generated by Django 4.2.7 on 2026-01-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0034_add_responsible_department_and_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subsidiary',
        ),
    ]
