# Generated by Django 4.2.7 on 2026-01-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0035_remove_subsidiary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
