# Generated by Django 4.2.7 on 2026-01-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0036_remove_alias_and_description_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_stage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_professions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_type',
        ),
    ]
