# Generated by Django 4.2.7 on 2026-01-02 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0037_remove_service_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdvisorSelectedSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(verbose_name='问题描述')),
                ('constraints', models.TextField(blank=True, verbose_name='约束条件')),
                ('solution_title', models.CharField(max_length=200, verbose_name='方案标题')),
                ('solution_description', models.TextField(verbose_name='方案描述')),
                ('solution_index', models.IntegerField(help_text='在AI返回的多个方案中的序号', verbose_name='方案序号')),
                ('savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计节省金额（万元）')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('advantages', models.TextField(blank=True, verbose_name='优势')),
                ('considerations', models.TextField(blank=True, verbose_name='注意事项')),
                ('service_type_id', models.IntegerField(blank=True, null=True, verbose_name='服务类型ID')),
                ('profession_code', models.CharField(blank=True, max_length=50, verbose_name='专业编码')),
                ('budget_impact', models.CharField(blank=True, max_length=20, verbose_name='预算影响')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储完整的方案数据', verbose_name='扩展信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_solutions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI顾问选中方案',
                'verbose_name_plural': 'AI顾问选中方案',
                'db_table': 'production_management_ai_advisor_selected_solution',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['user', '-created_time'], name='production__user_id_b252c6_idx'), models.Index(fields=['service_type_id', 'profession_code'], name='production__service_0325c5_idx')],
            },
        ),
    ]
