# Generated by Django 4.2.7 on 2026-01-02 14:52

import backend.apps.production_management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0038_aiadvisorselectedsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOptimizationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_file', models.FileField(help_text='上传的CAD文件（支持DWG、DXF、PDF格式）', upload_to='pre_optimization_materials/', verbose_name='CAD文件')),
                ('file_name', models.CharField(help_text='原始文件名', max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(help_text='文件大小，单位：字节', verbose_name='文件大小（字节）')),
                ('file_type', models.CharField(help_text='文件扩展名（dwg/dxf/pdf）', max_length=10, verbose_name='文件类型')),
                ('design_unit', models.CharField(blank=True, help_text='从CAD文件中提取的设计单位', max_length=200, verbose_name='设计单位')),
                ('drawing_version', models.CharField(blank=True, help_text='从CAD文件中提取的图纸版本', max_length=50, verbose_name='图纸版本')),
                ('general_description', models.TextField(blank=True, help_text='从CAD文件中提取的总说明', verbose_name='总说明')),
                ('technical_economic_indicators', models.JSONField(blank=True, default=dict, help_text='从CAD文件中提取的技术经济指标表数据', verbose_name='技术经济指标')),
                ('drawing_catalog', models.JSONField(blank=True, default=dict, help_text='从CAD文件中提取的图纸目录信息', verbose_name='图纸目录')),
                ('cad_parse_result', models.JSONField(blank=True, default=dict, help_text='完整的CAD文件解析结果，包含图层、实体、设计参数等', verbose_name='CAD解析结果')),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('success', '解析成功'), ('failed', '解析失败'), ('partial', '部分成功')], default='pending', help_text='CAD文件解析状态', max_length=20, verbose_name='解析状态')),
                ('parse_error', models.TextField(blank=True, help_text='如果解析失败，记录错误信息', verbose_name='解析错误信息')),
                ('parse_progress', models.IntegerField(default=0, help_text='解析进度百分比（0-100）', verbose_name='解析进度')),
                ('description', models.TextField(blank=True, help_text='人工添加的备注说明', verbose_name='备注说明')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('parsed_time', models.DateTimeField(blank=True, null=True, verbose_name='解析完成时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优化前资料',
                'verbose_name_plural': '优化前资料',
                'db_table': 'production_management_pre_optimization_material',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.AddField(
            model_name='aiadvisorselectedsolution',
            name='project',
            field=models.ForeignKey(blank=True, help_text='AI顾问方案关联的项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_advisor_solutions', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='aiadvisorselectedsolution',
            index=models.Index(fields=['project', '-created_time'], name='production__project_49ee83_idx'),
        ),
        migrations.AddField(
            model_name='preoptimizationmaterial',
            name='project',
            field=models.ForeignKey(help_text='关联的项目', on_delete=django.db.models.deletion.CASCADE, related_name='pre_optimization_materials', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='preoptimizationmaterial',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pre_optimization_materials', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddIndex(
            model_name='preoptimizationmaterial',
            index=models.Index(fields=['project', '-uploaded_time'], name='production__project_62591f_idx'),
        ),
        migrations.AddIndex(
            model_name='preoptimizationmaterial',
            index=models.Index(fields=['parse_status', '-uploaded_time'], name='production__parse_s_58e674_idx'),
        ),
        migrations.AddIndex(
            model_name='preoptimizationmaterial',
            index=models.Index(fields=['uploaded_by', '-uploaded_time'], name='production__uploade_c3e7ad_idx'),
        ),
    ]
