# Generated by Django 4.2.7 on 2026-01-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0039_add_pre_optimization_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoptimizationmaterial',
            name='parse_progress_message',
            field=models.CharField(blank=True, default='', help_text='当前解析步骤的描述信息', max_length=200, verbose_name='解析进度消息'),
        ),
    ]
