# Generated by Django 4.2.7 on 2026-01-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0040_add_parse_progress_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preoptimizationmaterial',
            name='project',
        ),
        migrations.RemoveField(
            model_name='preoptimizationmaterial',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='project',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目别名'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_type',
            field=models.ForeignKey(blank=True, db_column='business_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='production_management.businesstype', verbose_name='项目业态'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='project',
            name='design_stage',
            field=models.ForeignKey(blank=True, db_column='design_stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='production_management.designstage', verbose_name='图纸阶段'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_professions',
            field=models.ManyToManyField(blank=True, related_name='projects', to='production_management.serviceprofession', verbose_name='服务专业'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='production_management.servicetype', verbose_name='服务类型'),
        ),
        migrations.DeleteModel(
            name='AIAdvisorSelectedSolution',
        ),
        migrations.DeleteModel(
            name='PreOptimizationMaterial',
        ),
    ]
