-- 生产管理模块 - 项目任务表创建脚本
-- 如果Django迁移无法运行，可以直接执行此SQL脚本创建表

BEGIN;

-- 创建项目任务表
CREATE TABLE IF NOT EXISTS "production_management_task" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(200) NOT NULL,
    "task_type" varchar(64) NOT NULL,
    "description" text NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'pending',
    "assigned_role" varchar(50) NOT NULL DEFAULT '',
    "target_unit" varchar(32) NOT NULL DEFAULT '',
    "due_time" timestamp with time zone NULL,
    "completed_time" timestamp with time zone NULL,
    "cancelled_time" timestamp with time zone NULL,
    "created_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" jsonb NOT NULL DEFAULT '{}',
    "project_id" bigint NOT NULL,
    "assigned_to_id" bigint NULL,
    "completed_by_id" bigint NULL,
    "cancelled_by_id" bigint NULL,
    "created_by_id" bigint NULL
);

-- 创建索引
CREATE INDEX IF NOT EXISTS "production_management_task_project_id_task_type_idx" 
    ON "production_management_task" ("project_id", "task_type");

CREATE INDEX IF NOT EXISTS "production_management_task_project_id_status_idx" 
    ON "production_management_task" ("project_id", "status");

CREATE INDEX IF NOT EXISTS "production_management_task_project_id_idx" 
    ON "production_management_task" ("project_id");

CREATE INDEX IF NOT EXISTS "production_management_task_assigned_to_id_idx" 
    ON "production_management_task" ("assigned_to_id");

CREATE INDEX IF NOT EXISTS "production_management_task_status_idx" 
    ON "production_management_task" ("status");

-- 添加外键约束（如果关联表存在）
-- 注意：如果表不存在，这些外键约束会失败，但不影响表的创建
DO $$
BEGIN
    -- 检查 production_management_project 表是否存在
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'production_management_project') THEN
        -- 添加 project_id 外键
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'production_management_task_project_id_fkey'
        ) THEN
            ALTER TABLE "production_management_task" 
            ADD CONSTRAINT "production_management_task_project_id_fkey" 
            FOREIGN KEY ("project_id") 
            REFERENCES "production_management_project" ("id") 
            ON DELETE CASCADE;
        END IF;
    END IF;

    -- 检查 system_user 表是否存在
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'system_user') THEN
        -- 添加 assigned_to_id 外键
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'production_management_task_assigned_to_id_fkey'
        ) THEN
            ALTER TABLE "production_management_task" 
            ADD CONSTRAINT "production_management_task_assigned_to_id_fkey" 
            FOREIGN KEY ("assigned_to_id") 
            REFERENCES "system_user" ("id") 
            ON DELETE SET NULL;
        END IF;

        -- 添加 completed_by_id 外键
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'production_management_task_completed_by_id_fkey'
        ) THEN
            ALTER TABLE "production_management_task" 
            ADD CONSTRAINT "production_management_task_completed_by_id_fkey" 
            FOREIGN KEY ("completed_by_id") 
            REFERENCES "system_user" ("id") 
            ON DELETE SET NULL;
        END IF;

        -- 添加 cancelled_by_id 外键
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'production_management_task_cancelled_by_id_fkey'
        ) THEN
            ALTER TABLE "production_management_task" 
            ADD CONSTRAINT "production_management_task_cancelled_by_id_fkey" 
            FOREIGN KEY ("cancelled_by_id") 
            REFERENCES "system_user" ("id") 
            ON DELETE SET NULL;
        END IF;

        -- 添加 created_by_id 外键
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'production_management_task_created_by_id_fkey'
        ) THEN
            ALTER TABLE "production_management_task" 
            ADD CONSTRAINT "production_management_task_created_by_id_fkey" 
            FOREIGN KEY ("created_by_id") 
            REFERENCES "system_user" ("id") 
            ON DELETE SET NULL;
        END IF;
    END IF;
END $$;

COMMIT;



















