# Generated by Django 4.2.7 on 2025-12-04 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('生产管理', '生产管理'), ('结算管理', '结算管理'), ('生产质量', '生产质量'), ('客户管理', '客户管理'), ('商机管理', '商机管理'), ('合同管理', '合同管理'), ('人事管理', '人事管理'), ('风险管理', '风险管理'), ('系统管理', '系统管理'), ('权限管理', '权限管理'), ('资源标准', '资源标准'), ('任务协作', '任务协作'), ('交付客户', '交付客户')], max_length=100, verbose_name='功能模块')),
                ('action', models.CharField(max_length=100, verbose_name='操作代码')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=150, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业务权限点',
                'verbose_name_plural': '业务权限点',
                'db_table': 'system_permission_item',
                'ordering': ['module', 'action'],
            },
        ),
    ]
