# Generated by Django 4.2.7 on 2025-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionitem',
            name='module',
            field=models.CharField(choices=[('生产管理', '生产管理'), ('结算管理', '结算管理'), ('回款管理', '回款管理'), ('生产质量', '生产质量'), ('客户管理', '客户管理'), ('商机管理', '商机管理'), ('合同管理', '合同管理'), ('人事管理', '人事管理'), ('风险管理', '风险管理'), ('系统管理', '系统管理'), ('权限管理', '权限管理'), ('资源标准', '资源标准'), ('任务协作', '任务协作'), ('交付客户', '交付客户'), ('档案管理', '档案管理'), ('计划管理', '计划管理'), ('诉讼管理', '诉讼管理'), ('财务管理', '财务管理'), ('行政管理', '行政管理')], max_length=100, verbose_name='功能模块'),
        ),
    ]
