# Generated by Django 4.2.7 on 2025-11-10 08:26

import backend.apps.production_quality.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0001_initial_squashed_0016_projectmeetingrecord_projectdesignreply'),
        ('resource_standard', '0004_systemparameter_professionalcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_number', models.CharField(max_length=50, unique=True, verbose_name='意见编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('in_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('needs_update', '需修改')], default='draft', max_length=20, verbose_name='状态')),
                ('drawing_number', models.CharField(blank=True, max_length=100, verbose_name='图纸编号')),
                ('drawing_version', models.CharField(blank=True, max_length=100, verbose_name='图纸版本')),
                ('location_name', models.CharField(max_length=100, verbose_name='部位名称')),
                ('issue_description', models.TextField(verbose_name='问题描述')),
                ('current_practice', models.TextField(blank=True, verbose_name='现行做法')),
                ('recommendation', models.TextField(verbose_name='优化建议')),
                ('issue_category', models.CharField(choices=[('error', '错误'), ('omission', '遗漏'), ('conflict', '矛盾'), ('defect', '缺陷'), ('improvement', '优化建议')], max_length=20, verbose_name='问题类别')),
                ('severity_level', models.CharField(choices=[('major', '重大'), ('normal', '一般'), ('minor', '轻微')], max_length=20, verbose_name='严重等级')),
                ('reference_codes', models.CharField(blank=True, max_length=255, verbose_name='引用规范')),
                ('calculation_mode', models.CharField(choices=[('auto', '自动计算'), ('manual', '手动输入')], default='auto', max_length=10, verbose_name='计算方式')),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='优化前工程量')),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='优化后工程量')),
                ('measure_unit', models.CharField(blank=True, max_length=30, verbose_name='计量单位')),
                ('unit_price_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='优化前综合单价')),
                ('unit_price_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='优化后综合单价')),
                ('saving_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='节省金额')),
                ('calculation_note', models.TextField(blank=True, verbose_name='计算说明')),
                ('is_template_applied', models.BooleanField(default=False, verbose_name='是否应用模板')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核完成时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions_created', to=settings.AUTH_USER_MODEL, verbose_name='提出人')),
                ('current_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='当前审核人')),
                ('professional_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to='resource_standard.professionalcategory', verbose_name='专业分类')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='project_center.project', verbose_name='关联项目')),
                ('review_points', models.ManyToManyField(blank=True, related_name='opinions', to='resource_standard.standardreviewitem', verbose_name='关联審查要點')),
            ],
            options={
                'verbose_name': '咨询意见',
                'verbose_name_plural': '咨询意见',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='报告编号')),
                ('name', models.CharField(max_length=255, verbose_name='报告名称')),
                ('summary', models.TextField(blank=True, verbose_name='报告摘要')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='报告配置')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('approved', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成者')),
                ('professional_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reports', to='resource_standard.professionalcategory', verbose_name='专业分类')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='project_center.project', verbose_name='关联项目')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reports', to='resource_standard.reporttemplate', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '生产报告',
                'verbose_name_plural': '生产报告',
                'ordering': ['-generated_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='章节标题')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='章节配置')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='production_quality.productionreport', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': '报告章节',
                'verbose_name_plural': '报告章节',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpinionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('current_drawing', '现状图纸'), ('proposed_drawing', '建议图纸'), ('calculation', '计算书'), ('other', '其他附件')], default='other', max_length=20, verbose_name='附件类型')),
                ('file', models.FileField(upload_to=backend.apps.production_quality.models.opinion_attachment_path, verbose_name='附件文件')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='production_quality.opinion', verbose_name='关联意见')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '意见附件',
                'verbose_name_plural': '意见附件',
            },
        ),
        migrations.CreateModel(
            name='ProductionStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_type', models.CharField(choices=[('overview', '总体概览'), ('quality', '质量指标'), ('efficiency', '效率指标'), ('capacity', '产能分析')], max_length=30, verbose_name='统计类型')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now, verbose_name='统计日期')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='统计数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_statistics', to='project_center.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '生产统计',
                'verbose_name_plural': '生产统计',
                'unique_together': {('project', 'statistic_type', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='OpinionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professional_lead', '专业负责人'), ('project_lead', '项目负责人'), ('quality_manager', '质量经理')], max_length=30, verbose_name='审核角色')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '驳回'), ('needs_update', '需修改')], default='pending', max_length=20, verbose_name='审核状态')),
                ('comments', models.TextField(blank=True, verbose_name='审核意见')),
                ('technical_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='技术评分')),
                ('economic_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='经济评分')),
                ('internal_note', models.TextField(blank=True, verbose_name='内部备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='production_quality.opinion', verbose_name='关联意见')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '意见审核记录',
                'verbose_name_plural': '意见审核记录',
                'unique_together': {('opinion', 'reviewer', 'role')},
            },
        ),
    ]
