# Generated by Django 4.2.7 on 2025-11-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_standard', '0004_systemparameter_professionalcategory'),
        ('production_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='review_points',
            field=models.ManyToManyField(blank=True, related_name='opinions', to='resource_standard.standardreviewitem', verbose_name='关联审查要点'),
        ),
    ]
