# Generated by Django 4.2.7 on 2025-11-11 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_quality', '0002_alter_opinion_review_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='actual_complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际完成日期'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='expected_complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划完成日期'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='impact_scope',
            field=models.JSONField(blank=True, default=list, verbose_name='影响范围'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='priority',
            field=models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='response_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='整改要求完成期限'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='source',
            field=models.CharField(choices=[('project_manager', '项目经理'), ('engineer', '专业工程师'), ('quality_audit', '质量巡检'), ('client_feedback', '甲方反馈'), ('other', '其他来源')], default='engineer', max_length=30, verbose_name='意见来源'),
        ),
        migrations.CreateModel(
            name='OpinionWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建意见'), ('updated', '更新内容'), ('submitted', '提交意见'), ('reassigned', '重新指派'), ('reviewed', '审核处理'), ('commented', '追加说明'), ('status_changed', '状态变更'), ('attachment_added', '新增附件'), ('attachment_removed', '移除附件')], max_length=40, verbose_name='操作类型')),
                ('from_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('submitted', '已提交'), ('in_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('needs_update', '需修改')], max_length=20, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('submitted', '已提交'), ('in_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('needs_update', '需修改')], max_length=20, null=True, verbose_name='目标状态')),
                ('operator_role', models.CharField(blank=True, choices=[('proposer', '提出人'), ('professional_engineer', '专业工程师'), ('professional_lead', '专业负责人'), ('project_manager', '项目负责人'), ('cost_engineer', '造价工程师'), ('quality_manager', '质量经理'), ('reviewer', '审核人'), ('observer', '关注人')], max_length=40, null=True, verbose_name='操作角色')),
                ('message', models.TextField(blank=True, verbose_name='备注说明')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='上下文信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='production_quality.opinion', verbose_name='关联意见')),
            ],
            options={
                'verbose_name': '意见流程日志',
                'verbose_name_plural': '意见流程日志',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpinionSavingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('material', '材料'), ('labor', '人工'), ('equipment', '设备'), ('indirect', '间接费用'), ('energy', '能耗'), ('schedule', '工期'), ('other', '其他')], default='other', max_length=20, verbose_name='节省类型')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='单位')),
                ('unit_saving', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单位节省')),
                ('total_saving', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='节省金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_items', to='production_quality.opinion', verbose_name='关联意见')),
            ],
            options={
                'verbose_name': '意见节省分项',
                'verbose_name_plural': '意见节省分项',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpinionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proposer', '提出人'), ('professional_engineer', '专业工程师'), ('professional_lead', '专业负责人'), ('project_manager', '项目负责人'), ('cost_engineer', '造价工程师'), ('quality_manager', '质量经理'), ('reviewer', '审核人'), ('observer', '关注人')], max_length=40, verbose_name='角色')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主责')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='移除时间')),
                ('extra_info', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='production_quality.opinion', verbose_name='关联意见')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_participations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '意见参与人',
                'verbose_name_plural': '意见参与人',
                'ordering': ['-joined_at'],
                'unique_together': {('opinion', 'user', 'role')},
            },
        ),
    ]
