# Generated by Django 4.2.7 on 2025-11-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_quality', '0003_opinion_actual_complete_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结案时间'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='cycle_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='流转耗时（小时）'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='first_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次指派时间'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次响应时间'),
        ),
    ]
