# Generated by Django 4.2.7 on 2025-11-23 06:13

import backend.apps.production_quality.models_startup
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0024_allow_null_structure_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_quality', '0004_opinion_closed_at_opinion_cycle_time_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDrawingDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目录名称')),
                ('path', models.CharField(max_length=500, verbose_name='目录路径')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否模板目录')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drawing_directories', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='production_quality.projectdrawingdirectory', verbose_name='父目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_directories', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '图纸目录',
                'verbose_name_plural': '图纸目录',
                'db_table': 'production_quality_drawing_directory',
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('project_manager_assigned_time', models.DateTimeField(blank=True, null=True, verbose_name='项目经理分配时间')),
                ('drawings_uploaded', models.BooleanField(default=False, verbose_name='图纸是否已上传')),
                ('drawings_upload_time', models.DateTimeField(blank=True, null=True, verbose_name='图纸上传时间')),
                ('team_configured', models.BooleanField(default=False, verbose_name='团队是否已配置')),
                ('team_configured_time', models.DateTimeField(blank=True, null=True, verbose_name='团队配置时间')),
                ('tasks_created', models.BooleanField(default=False, verbose_name='任务是否已创建')),
                ('tasks_created_time', models.DateTimeField(blank=True, null=True, verbose_name='任务创建时间')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='任务总数')),
                ('total_saving_target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='任务节省目标总额')),
                ('contract_saving_target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='合同节省目标')),
                ('submitted_time', models.DateTimeField(blank=True, null=True, verbose_name='提交审批时间')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('rejected_time', models.DateTimeField(blank=True, null=True, verbose_name='驳回时间')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('started_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('status', models.CharField(choices=[('project_received', '项目已接收'), ('drawings_uploading', '图纸载入中'), ('team_configuring', '团队配置中'), ('tasks_creating', '任务清单创建中'), ('waiting_approval', '待审批'), ('approved', '已审批通过'), ('rejected', '已驳回'), ('started', '已启动')], default='project_received', max_length=30, verbose_name='启动状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_startups', to=settings.AUTH_USER_MODEL, verbose_name='审批人（技术部经理）')),
                ('drawings_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawings_startups', to=settings.AUTH_USER_MODEL, verbose_name='图纸上传人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to='project_center.project', verbose_name='项目')),
                ('project_manager_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_startups', to=settings.AUTH_USER_MODEL, verbose_name='分配的项目经理')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_startups', to=settings.AUTH_USER_MODEL, verbose_name='接收人（技术部经理）')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_startups', to=settings.AUTH_USER_MODEL, verbose_name='驳回人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_startups', to=settings.AUTH_USER_MODEL, verbose_name='提交审批人')),
            ],
            options={
                'verbose_name': '项目生产启动',
                'verbose_name_plural': '项目生产启动',
                'db_table': 'production_quality_startup',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStartupApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('pending', '待审批')], default='pending', max_length=20, verbose_name='审批决定')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='production_quality.projectstartup', verbose_name='生产启动')),
            ],
            options={
                'verbose_name': '启动审批记录',
                'verbose_name_plural': '启动审批记录',
                'db_table': 'production_quality_startup_approval',
                'ordering': ['-approval_time', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.apps.production_quality.models_startup.drawing_file_path, verbose_name='图纸文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('dwg', 'DWG'), ('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG'), ('rvt', 'RVT'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=backend.apps.production_quality.models_startup.drawing_file_path, verbose_name='缩略图')),
                ('drawing_number', models.CharField(blank=True, max_length=100, verbose_name='图纸编号')),
                ('drawing_version', models.CharField(blank=True, max_length=50, verbose_name='图纸版本')),
                ('drawing_date', models.DateField(blank=True, null=True, verbose_name='出图日期')),
                ('design_unit', models.CharField(blank=True, max_length=200, verbose_name='设计单位')),
                ('scale', models.CharField(blank=True, max_length=50, verbose_name='比例尺')),
                ('profession_type', models.CharField(blank=True, max_length=50, verbose_name='专业类型')),
                ('recognition_status', models.CharField(choices=[('pending', '待识别'), ('recognized', '已识别'), ('manual', '手动录入'), ('failed', '识别失败')], default='pending', max_length=20, verbose_name='识别状态')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='production_quality.projectdrawingdirectory', verbose_name='所属目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_drawing_files', to='project_center.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawing_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '图纸文件',
                'verbose_name_plural': '图纸文件',
                'db_table': 'production_quality_drawing_file',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=50, verbose_name='任务编码')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_content', models.TextField(verbose_name='任务内容')),
                ('scope', models.JSONField(blank=True, default=list, verbose_name='任务范围（图纸区域）')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='建筑面积（㎡）')),
                ('saving_target_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='每平方米节省金额（元/㎡）')),
                ('saving_target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='节省目标（元）')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划完成日期')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task_breakdowns', to=settings.AUTH_USER_MODEL, verbose_name='分配人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_breakdowns', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_breakdowns', to='project_center.serviceprofession', verbose_name='所属专业')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_breakdowns', to='project_center.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '任务分解',
                'verbose_name_plural': '任务分解',
                'db_table': 'production_quality_task_breakdown',
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'task_code')},
            },
        ),
    ]
