# Generated by Django 4.2.7 on 2025-11-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0001_initial'),
        ('production_quality', '0005_add_production_startup_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='productionstatistic',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_statistics', to='production_management.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='projectdrawingdirectory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_directories', to='production_management.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectdrawingfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_drawing_files', to='production_management.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectstartup',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to='production_management.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projecttaskbreakdown',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_breakdowns', to='production_management.serviceprofession', verbose_name='所属专业'),
        ),
        migrations.AlterField(
            model_name='projecttaskbreakdown',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_breakdowns', to='production_management.project', verbose_name='项目'),
        ),
    ]
